// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flora/pkg/pb/servicecharge/v1 (interfaces: ServiceChargeServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/servicecharge/v1/servicecharge_service_mock.go -package=mock_servicechargev1 github.com/flora/pkg/pb/servicecharge/v1 ServiceChargeServiceServer
//

// Package mock_servicechargev1 is a generated GoMock package.
package mock_servicechargev1

import (
	context "context"
	reflect "reflect"

	servicechargev1 "github.com/flora/pkg/pb/servicecharge/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceChargeServiceServer is a mock of ServiceChargeServiceServer interface.
type MockServiceChargeServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockServiceChargeServiceServerMockRecorder
	isgomock struct{}
}

// MockServiceChargeServiceServerMockRecorder is the mock recorder for MockServiceChargeServiceServer.
type MockServiceChargeServiceServerMockRecorder struct {
	mock *MockServiceChargeServiceServer
}

// NewMockServiceChargeServiceServer creates a new mock instance.
func NewMockServiceChargeServiceServer(ctrl *gomock.Controller) *MockServiceChargeServiceServer {
	mock := &MockServiceChargeServiceServer{ctrl: ctrl}
	mock.recorder = &MockServiceChargeServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceChargeServiceServer) EXPECT() *MockServiceChargeServiceServerMockRecorder {
	return m.recorder
}

// ReserveServiceCharge mocks base method.
func (m *MockServiceChargeServiceServer) ReserveServiceCharge(arg0 context.Context, arg1 *servicechargev1.ReserveServiceChargeRequest) (*servicechargev1.ReserveServiceChargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveServiceCharge", arg0, arg1)
	ret0, _ := ret[0].(*servicechargev1.ReserveServiceChargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveServiceCharge indicates an expected call of ReserveServiceCharge.
func (mr *MockServiceChargeServiceServerMockRecorder) ReserveServiceCharge(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveServiceCharge", reflect.TypeOf((*MockServiceChargeServiceServer)(nil).ReserveServiceCharge), arg0, arg1)
}

// UpdateServiceChargeStatus mocks base method.
func (m *MockServiceChargeServiceServer) UpdateServiceChargeStatus(arg0 context.Context, arg1 *servicechargev1.UpdateServiceChargeStatusRequest) (*servicechargev1.UpdateServiceChargeStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceChargeStatus", arg0, arg1)
	ret0, _ := ret[0].(*servicechargev1.UpdateServiceChargeStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceChargeStatus indicates an expected call of UpdateServiceChargeStatus.
func (mr *MockServiceChargeServiceServerMockRecorder) UpdateServiceChargeStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceChargeStatus", reflect.TypeOf((*MockServiceChargeServiceServer)(nil).UpdateServiceChargeStatus), arg0, arg1)
}

// mustEmbedUnimplementedServiceChargeServiceServer mocks base method.
func (m *MockServiceChargeServiceServer) mustEmbedUnimplementedServiceChargeServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedServiceChargeServiceServer")
}

// mustEmbedUnimplementedServiceChargeServiceServer indicates an expected call of mustEmbedUnimplementedServiceChargeServiceServer.
func (mr *MockServiceChargeServiceServerMockRecorder) mustEmbedUnimplementedServiceChargeServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedServiceChargeServiceServer", reflect.TypeOf((*MockServiceChargeServiceServer)(nil).mustEmbedUnimplementedServiceChargeServiceServer))
}
