// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// Account is an object representing the database table.
type Account struct {
	ID                types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	ExternalAccountID string       `db:"external_account_id" json:"external_account_id" db:"external_account_id"`
	TenantID          types.Uint64 `db:"tenant_id" json:"tenant_id" db:"tenant_id"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`

	R accountR `db:"-" json:"-" db:"-"`
}

// AccountSlice is an alias for a slice of pointers to Account.
// This should almost always be used instead of []*Account.
type AccountSlice []*Account

// Accounts contains methods to work with the accounts table
var Accounts = mysql.NewTablex[*Account, AccountSlice, *AccountSetter]("accounts", buildAccountColumns("accounts"), []string{"id"}, []string{"external_account_id", "tenant_id"})

// AccountsQuery is a query on the accounts table
type AccountsQuery = *mysql.ViewQuery[*Account, AccountSlice]

// accountR is where relationships are stored.
type accountR struct {
	Tenant         *Tenant            `json:"Tenant" db:"Tenant"`                 // fk_accounts_tenant
	OneShotUsages  OneShotUsageSlice  `json:"OneShotUsages" db:"OneShotUsages"`   // fk_one_shot_usages_account
	ServiceCharges ServiceChargeSlice `json:"ServiceCharges" db:"ServiceCharges"` // fk_service_charges_account
	Subscriptions  SubscriptionSlice  `json:"Subscriptions" db:"Subscriptions"`   // fk_subscriptions_account
}

func buildAccountColumns(alias string) accountColumns {
	return accountColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "external_account_id", "tenant_id", "created_at", "updated_at",
		).WithParent("accounts"),
		tableAlias:        alias,
		ID:                mysql.Quote(alias, "id"),
		ExternalAccountID: mysql.Quote(alias, "external_account_id"),
		TenantID:          mysql.Quote(alias, "tenant_id"),
		CreatedAt:         mysql.Quote(alias, "created_at"),
		UpdatedAt:         mysql.Quote(alias, "updated_at"),
	}
}

type accountColumns struct {
	expr.ColumnsExpr
	tableAlias        string
	ID                mysql.Expression
	ExternalAccountID mysql.Expression
	TenantID          mysql.Expression
	CreatedAt         mysql.Expression
	UpdatedAt         mysql.Expression
}

func (c accountColumns) Alias() string {
	return c.tableAlias
}

func (accountColumns) AliasedAs(alias string) accountColumns {
	return buildAccountColumns(alias)
}

// AccountSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AccountSetter struct {
	ID                *types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	ExternalAccountID *string       `db:"external_account_id" json:"external_account_id" db:"external_account_id"`
	TenantID          *types.Uint64 `db:"tenant_id" json:"tenant_id" db:"tenant_id"`
	CreatedAt         *time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt         *time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s AccountSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.ExternalAccountID != nil {
		vals = append(vals, "external_account_id")
	}
	if s.TenantID != nil {
		vals = append(vals, "tenant_id")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AccountSetter) Overwrite(t *Account) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.ExternalAccountID != nil {
		t.ExternalAccountID = func() string {
			if s.ExternalAccountID == nil {
				return *new(string)
			}
			return *s.ExternalAccountID
		}()
	}
	if s.TenantID != nil {
		t.TenantID = func() types.Uint64 {
			if s.TenantID == nil {
				return *new(types.Uint64)
			}
			return *s.TenantID
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *AccountSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Accounts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ExternalAccountID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.ExternalAccountID == nil {
					return *new(string)
				}
				return *s.ExternalAccountID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.TenantID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.TenantID == nil {
					return *new(types.Uint64)
				}
				return *s.TenantID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s AccountSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("accounts")...)
}

func (s AccountSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.ExternalAccountID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "external_account_id")...),
			mysql.Arg(s.ExternalAccountID),
		}})
	}

	if s.TenantID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "tenant_id")...),
			mysql.Arg(s.TenantID),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAccount retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAccount(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*Account, error) {
	if len(cols) == 0 {
		return Accounts.Query(
			sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Accounts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AccountExists checks the presence of a single record by primary key
func AccountExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Account is retrieved from the database
func (o *Account) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, AccountSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Account
func (o *Account) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Account) pkEQ() dialect.Expression {
	return mysql.Quote("accounts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Account
func (o *Account) Update(ctx context.Context, exec bob.Executor, s *AccountSetter) error {
	_, err := Accounts.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Account record with an executor
func (o *Account) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Accounts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Account using the executor
func (o *Account) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AccountSlice is retrieved from the database
func (o AccountSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AccountSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("accounts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AccountSlice) copyMatchingRows(from ...*Account) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AccountSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterUpdateHooks on the slice
				_, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AccountSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AccountSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AccountSetter) error {
	_, err := Accounts.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o AccountSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AccountSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Accounts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Tenant starts a query for related objects on tenants
func (o *Account) Tenant(mods ...bob.Mod[*dialect.SelectQuery]) TenantsQuery {
	return Tenants.Query(append(mods,
		sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(o.TenantID))),
	)...)
}

func (os AccountSlice) Tenant(mods ...bob.Mod[*dialect.SelectQuery]) TenantsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.TenantID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Tenants.Query(append(mods,
		sm.Where(mysql.Group(Tenants.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OneShotUsages starts a query for related objects on one_shot_usages
func (o *Account) OneShotUsages(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	return OneShotUsages.Query(append(mods,
		sm.Where(OneShotUsages.Columns.AccountID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) OneShotUsages(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OneShotUsages.Query(append(mods,
		sm.Where(mysql.Group(OneShotUsages.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

// ServiceCharges starts a query for related objects on service_charges
func (o *Account) ServiceCharges(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargesQuery {
	return ServiceCharges.Query(append(mods,
		sm.Where(ServiceCharges.Columns.AccountID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) ServiceCharges(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceCharges.Query(append(mods,
		sm.Where(mysql.Group(ServiceCharges.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

// Subscriptions starts a query for related objects on subscriptions
func (o *Account) Subscriptions(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	return Subscriptions.Query(append(mods,
		sm.Where(Subscriptions.Columns.AccountID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) Subscriptions(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Subscriptions.Query(append(mods,
		sm.Where(mysql.Group(Subscriptions.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

func attachAccountTenant0(ctx context.Context, exec bob.Executor, count int, account0 *Account, tenant1 *Tenant) (*Account, error) {
	setter := &AccountSetter{
		TenantID: func() *types.Uint64 { return &tenant1.ID }(),
	}

	err := account0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountTenant0: %w", err)
	}

	return account0, nil
}

func (account0 *Account) InsertTenant(ctx context.Context, exec bob.Executor, related *TenantSetter) error {
	var err error

	tenant1, err := Tenants.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAccountTenant0(ctx, exec, 1, account0, tenant1)
	if err != nil {
		return err
	}

	account0.R.Tenant = tenant1

	tenant1.R.Accounts = append(tenant1.R.Accounts, account0)

	return nil
}

func (account0 *Account) AttachTenant(ctx context.Context, exec bob.Executor, tenant1 *Tenant) error {
	var err error

	_, err = attachAccountTenant0(ctx, exec, 1, account0, tenant1)
	if err != nil {
		return err
	}

	account0.R.Tenant = tenant1

	tenant1.R.Accounts = append(tenant1.R.Accounts, account0)

	return nil
}

func insertAccountOneShotUsages0(ctx context.Context, exec bob.Executor, oneShotUsages1 []*OneShotUsageSetter, account0 *Account) (OneShotUsageSlice, error) {
	for i := range oneShotUsages1 {
		oneShotUsages1[i].AccountID = func() *types.Uint64 { return &account0.ID }()
	}

	ret, err := OneShotUsages.Insert(bob.ToMods(oneShotUsages1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountOneShotUsages0: %w", err)
	}

	return ret, nil
}

func attachAccountOneShotUsages0(ctx context.Context, exec bob.Executor, count int, oneShotUsages1 OneShotUsageSlice, account0 *Account) (OneShotUsageSlice, error) {
	setter := &OneShotUsageSetter{
		AccountID: func() *types.Uint64 { return &account0.ID }(),
	}

	err := oneShotUsages1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountOneShotUsages0: %w", err)
	}

	return oneShotUsages1, nil
}

func (account0 *Account) InsertOneShotUsages(ctx context.Context, exec bob.Executor, related ...*OneShotUsageSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	oneShotUsages1, err := insertAccountOneShotUsages0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.OneShotUsages = append(account0.R.OneShotUsages, oneShotUsages1...)

	for _, rel := range oneShotUsages1 {
		rel.R.Account = account0
	}
	return nil
}

func (account0 *Account) AttachOneShotUsages(ctx context.Context, exec bob.Executor, related ...*OneShotUsage) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	oneShotUsages1 := OneShotUsageSlice(related)

	_, err = attachAccountOneShotUsages0(ctx, exec, len(related), oneShotUsages1, account0)
	if err != nil {
		return err
	}

	account0.R.OneShotUsages = append(account0.R.OneShotUsages, oneShotUsages1...)

	for _, rel := range related {
		rel.R.Account = account0
	}

	return nil
}

func insertAccountServiceCharges0(ctx context.Context, exec bob.Executor, serviceCharges1 []*ServiceChargeSetter, account0 *Account) (ServiceChargeSlice, error) {
	for i := range serviceCharges1 {
		serviceCharges1[i].AccountID = func() *types.Uint64 { return &account0.ID }()
	}

	ret, err := ServiceCharges.Insert(bob.ToMods(serviceCharges1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountServiceCharges0: %w", err)
	}

	return ret, nil
}

func attachAccountServiceCharges0(ctx context.Context, exec bob.Executor, count int, serviceCharges1 ServiceChargeSlice, account0 *Account) (ServiceChargeSlice, error) {
	setter := &ServiceChargeSetter{
		AccountID: func() *types.Uint64 { return &account0.ID }(),
	}

	err := serviceCharges1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountServiceCharges0: %w", err)
	}

	return serviceCharges1, nil
}

func (account0 *Account) InsertServiceCharges(ctx context.Context, exec bob.Executor, related ...*ServiceChargeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serviceCharges1, err := insertAccountServiceCharges0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.ServiceCharges = append(account0.R.ServiceCharges, serviceCharges1...)

	for _, rel := range serviceCharges1 {
		rel.R.Account = account0
	}
	return nil
}

func (account0 *Account) AttachServiceCharges(ctx context.Context, exec bob.Executor, related ...*ServiceCharge) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serviceCharges1 := ServiceChargeSlice(related)

	_, err = attachAccountServiceCharges0(ctx, exec, len(related), serviceCharges1, account0)
	if err != nil {
		return err
	}

	account0.R.ServiceCharges = append(account0.R.ServiceCharges, serviceCharges1...)

	for _, rel := range related {
		rel.R.Account = account0
	}

	return nil
}

func insertAccountSubscriptions0(ctx context.Context, exec bob.Executor, subscriptions1 []*SubscriptionSetter, account0 *Account) (SubscriptionSlice, error) {
	for i := range subscriptions1 {
		subscriptions1[i].AccountID = func() *types.Uint64 { return &account0.ID }()
	}

	ret, err := Subscriptions.Insert(bob.ToMods(subscriptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountSubscriptions0: %w", err)
	}

	return ret, nil
}

func attachAccountSubscriptions0(ctx context.Context, exec bob.Executor, count int, subscriptions1 SubscriptionSlice, account0 *Account) (SubscriptionSlice, error) {
	setter := &SubscriptionSetter{
		AccountID: func() *types.Uint64 { return &account0.ID }(),
	}

	err := subscriptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountSubscriptions0: %w", err)
	}

	return subscriptions1, nil
}

func (account0 *Account) InsertSubscriptions(ctx context.Context, exec bob.Executor, related ...*SubscriptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	subscriptions1, err := insertAccountSubscriptions0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.Subscriptions = append(account0.R.Subscriptions, subscriptions1...)

	for _, rel := range subscriptions1 {
		rel.R.Account = account0
	}
	return nil
}

func (account0 *Account) AttachSubscriptions(ctx context.Context, exec bob.Executor, related ...*Subscription) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	subscriptions1 := SubscriptionSlice(related)

	_, err = attachAccountSubscriptions0(ctx, exec, len(related), subscriptions1, account0)
	if err != nil {
		return err
	}

	account0.R.Subscriptions = append(account0.R.Subscriptions, subscriptions1...)

	for _, rel := range related {
		rel.R.Account = account0
	}

	return nil
}
