// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	enums "github.com/flora/api/internal/bob/enums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Account runs hooks after queries
var _ bob.HookableType = &Account{}

// Make sure the type CatalogPrice runs hooks after queries
var _ bob.HookableType = &CatalogPrice{}

// Make sure the type Catalog runs hooks after queries
var _ bob.HookableType = &Catalog{}

// Make sure the type OneShotUsage runs hooks after queries
var _ bob.HookableType = &OneShotUsage{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type ServiceChargeItem runs hooks after queries
var _ bob.HookableType = &ServiceChargeItem{}

// Make sure the type ServiceChargeStatus runs hooks after queries
var _ bob.HookableType = &ServiceChargeStatus{}

// Make sure the type ServiceCharge runs hooks after queries
var _ bob.HookableType = &ServiceCharge{}

// Make sure the type Subscription runs hooks after queries
var _ bob.HookableType = &Subscription{}

// Make sure the type Tenant runs hooks after queries
var _ bob.HookableType = &Tenant{}

// Make sure the type types.Uint64 satisfies database/sql.Scanner
var _ sql.Scanner = (*types.Uint64)(nil)

// Make sure the type types.Uint64 satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.Uint64)

// Make sure the type enums.CatalogPricesBillingType satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.CatalogPricesBillingType)(nil)

// Make sure the type enums.CatalogPricesBillingType satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.CatalogPricesBillingType)

// Make sure the type enums.CatalogPricesBillingCycle satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.CatalogPricesBillingCycle)(nil)

// Make sure the type enums.CatalogPricesBillingCycle satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.CatalogPricesBillingCycle)

// Make sure the type enums.ServiceChargeStatusesStatus satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.ServiceChargeStatusesStatus)(nil)

// Make sure the type enums.ServiceChargeStatusesStatus satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.ServiceChargeStatusesStatus)
