// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// Catalog is an object representing the database table.
type Catalog struct {
	ID        types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	Name      string       `db:"name" json:"name" db:"name"`
	TenantID  types.Uint64 `db:"tenant_id" json:"tenant_id" db:"tenant_id"`
	CreatedAt time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`

	R catalogR `db:"-" json:"-" db:"-"`
}

// CatalogSlice is an alias for a slice of pointers to Catalog.
// This should almost always be used instead of []*Catalog.
type CatalogSlice []*Catalog

// Catalogs contains methods to work with the catalogs table
var Catalogs = mysql.NewTablex[*Catalog, CatalogSlice, *CatalogSetter]("catalogs", buildCatalogColumns("catalogs"), []string{"id"})

// CatalogsQuery is a query on the catalogs table
type CatalogsQuery = *mysql.ViewQuery[*Catalog, CatalogSlice]

// catalogR is where relationships are stored.
type catalogR struct {
	CatalogPrices CatalogPriceSlice `json:"CatalogPrices" db:"CatalogPrices"` // fk_catalog_prices_catalog
	Tenant        *Tenant           `json:"Tenant" db:"Tenant"`               // fk_catalogs_tenant
	OneShotUsages OneShotUsageSlice `json:"OneShotUsages" db:"OneShotUsages"` // fk_one_shot_usages_catalog
	Subscriptions SubscriptionSlice `json:"Subscriptions" db:"Subscriptions"` // fk_subscriptions_catalog
}

func buildCatalogColumns(alias string) catalogColumns {
	return catalogColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "tenant_id", "created_at", "updated_at",
		).WithParent("catalogs"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
		TenantID:   mysql.Quote(alias, "tenant_id"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type catalogColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
	TenantID   mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c catalogColumns) Alias() string {
	return c.tableAlias
}

func (catalogColumns) AliasedAs(alias string) catalogColumns {
	return buildCatalogColumns(alias)
}

// CatalogSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CatalogSetter struct {
	ID        *types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	Name      *string       `db:"name" json:"name" db:"name"`
	TenantID  *types.Uint64 `db:"tenant_id" json:"tenant_id" db:"tenant_id"`
	CreatedAt *time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt *time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s CatalogSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.TenantID != nil {
		vals = append(vals, "tenant_id")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CatalogSetter) Overwrite(t *Catalog) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.TenantID != nil {
		t.TenantID = func() types.Uint64 {
			if s.TenantID == nil {
				return *new(types.Uint64)
			}
			return *s.TenantID
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *CatalogSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Catalogs.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.TenantID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.TenantID == nil {
					return *new(types.Uint64)
				}
				return *s.TenantID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s CatalogSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("catalogs")...)
}

func (s CatalogSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.TenantID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "tenant_id")...),
			mysql.Arg(s.TenantID),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCatalog retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCatalog(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*Catalog, error) {
	if len(cols) == 0 {
		return Catalogs.Query(
			sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Catalogs.Query(
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Catalogs.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CatalogExists checks the presence of a single record by primary key
func CatalogExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return Catalogs.Query(
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Catalog is retrieved from the database
func (o *Catalog) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Catalogs.AfterSelectHooks.RunHooks(ctx, exec, CatalogSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Catalogs.AfterInsertHooks.RunHooks(ctx, exec, CatalogSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Catalogs.AfterUpdateHooks.RunHooks(ctx, exec, CatalogSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Catalogs.AfterDeleteHooks.RunHooks(ctx, exec, CatalogSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Catalog
func (o *Catalog) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Catalog) pkEQ() dialect.Expression {
	return mysql.Quote("catalogs", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Catalog
func (o *Catalog) Update(ctx context.Context, exec bob.Executor, s *CatalogSetter) error {
	_, err := Catalogs.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Catalog record with an executor
func (o *Catalog) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Catalogs.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Catalog using the executor
func (o *Catalog) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Catalogs.Query(
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CatalogSlice is retrieved from the database
func (o CatalogSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Catalogs.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Catalogs.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Catalogs.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Catalogs.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CatalogSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("catalogs", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CatalogSlice) copyMatchingRows(from ...*Catalog) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CatalogSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Catalogs.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Catalog:
				o.copyMatchingRows(retrieved)
			case []*Catalog:
				o.copyMatchingRows(retrieved...)
			case CatalogSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Catalog or a slice of Catalog
				// then run the AfterUpdateHooks on the slice
				_, err = Catalogs.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CatalogSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Catalogs.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Catalog:
				o.copyMatchingRows(retrieved)
			case []*Catalog:
				o.copyMatchingRows(retrieved...)
			case CatalogSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Catalog or a slice of Catalog
				// then run the AfterDeleteHooks on the slice
				_, err = Catalogs.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CatalogSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CatalogSetter) error {
	_, err := Catalogs.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o CatalogSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Catalogs.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CatalogSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Catalogs.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// CatalogPrices starts a query for related objects on catalog_prices
func (o *Catalog) CatalogPrices(mods ...bob.Mod[*dialect.SelectQuery]) CatalogPricesQuery {
	return CatalogPrices.Query(append(mods,
		sm.Where(CatalogPrices.Columns.CatalogID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os CatalogSlice) CatalogPrices(mods ...bob.Mod[*dialect.SelectQuery]) CatalogPricesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return CatalogPrices.Query(append(mods,
		sm.Where(mysql.Group(CatalogPrices.Columns.CatalogID).OP("IN", PKArgExpr)),
	)...)
}

// Tenant starts a query for related objects on tenants
func (o *Catalog) Tenant(mods ...bob.Mod[*dialect.SelectQuery]) TenantsQuery {
	return Tenants.Query(append(mods,
		sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(o.TenantID))),
	)...)
}

func (os CatalogSlice) Tenant(mods ...bob.Mod[*dialect.SelectQuery]) TenantsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.TenantID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Tenants.Query(append(mods,
		sm.Where(mysql.Group(Tenants.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OneShotUsages starts a query for related objects on one_shot_usages
func (o *Catalog) OneShotUsages(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	return OneShotUsages.Query(append(mods,
		sm.Where(OneShotUsages.Columns.CatalogID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os CatalogSlice) OneShotUsages(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OneShotUsages.Query(append(mods,
		sm.Where(mysql.Group(OneShotUsages.Columns.CatalogID).OP("IN", PKArgExpr)),
	)...)
}

// Subscriptions starts a query for related objects on subscriptions
func (o *Catalog) Subscriptions(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	return Subscriptions.Query(append(mods,
		sm.Where(Subscriptions.Columns.CatalogID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os CatalogSlice) Subscriptions(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Subscriptions.Query(append(mods,
		sm.Where(mysql.Group(Subscriptions.Columns.CatalogID).OP("IN", PKArgExpr)),
	)...)
}

func insertCatalogCatalogPrices0(ctx context.Context, exec bob.Executor, catalogPrices1 []*CatalogPriceSetter, catalog0 *Catalog) (CatalogPriceSlice, error) {
	for i := range catalogPrices1 {
		catalogPrices1[i].CatalogID = func() *types.Uint64 { return &catalog0.ID }()
	}

	ret, err := CatalogPrices.Insert(bob.ToMods(catalogPrices1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCatalogCatalogPrices0: %w", err)
	}

	return ret, nil
}

func attachCatalogCatalogPrices0(ctx context.Context, exec bob.Executor, count int, catalogPrices1 CatalogPriceSlice, catalog0 *Catalog) (CatalogPriceSlice, error) {
	setter := &CatalogPriceSetter{
		CatalogID: func() *types.Uint64 { return &catalog0.ID }(),
	}

	err := catalogPrices1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCatalogCatalogPrices0: %w", err)
	}

	return catalogPrices1, nil
}

func (catalog0 *Catalog) InsertCatalogPrices(ctx context.Context, exec bob.Executor, related ...*CatalogPriceSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	catalogPrices1, err := insertCatalogCatalogPrices0(ctx, exec, related, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.CatalogPrices = append(catalog0.R.CatalogPrices, catalogPrices1...)

	for _, rel := range catalogPrices1 {
		rel.R.Catalog = catalog0
	}
	return nil
}

func (catalog0 *Catalog) AttachCatalogPrices(ctx context.Context, exec bob.Executor, related ...*CatalogPrice) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	catalogPrices1 := CatalogPriceSlice(related)

	_, err = attachCatalogCatalogPrices0(ctx, exec, len(related), catalogPrices1, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.CatalogPrices = append(catalog0.R.CatalogPrices, catalogPrices1...)

	for _, rel := range related {
		rel.R.Catalog = catalog0
	}

	return nil
}

func attachCatalogTenant0(ctx context.Context, exec bob.Executor, count int, catalog0 *Catalog, tenant1 *Tenant) (*Catalog, error) {
	setter := &CatalogSetter{
		TenantID: func() *types.Uint64 { return &tenant1.ID }(),
	}

	err := catalog0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCatalogTenant0: %w", err)
	}

	return catalog0, nil
}

func (catalog0 *Catalog) InsertTenant(ctx context.Context, exec bob.Executor, related *TenantSetter) error {
	var err error

	tenant1, err := Tenants.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCatalogTenant0(ctx, exec, 1, catalog0, tenant1)
	if err != nil {
		return err
	}

	catalog0.R.Tenant = tenant1

	tenant1.R.Catalogs = append(tenant1.R.Catalogs, catalog0)

	return nil
}

func (catalog0 *Catalog) AttachTenant(ctx context.Context, exec bob.Executor, tenant1 *Tenant) error {
	var err error

	_, err = attachCatalogTenant0(ctx, exec, 1, catalog0, tenant1)
	if err != nil {
		return err
	}

	catalog0.R.Tenant = tenant1

	tenant1.R.Catalogs = append(tenant1.R.Catalogs, catalog0)

	return nil
}

func insertCatalogOneShotUsages0(ctx context.Context, exec bob.Executor, oneShotUsages1 []*OneShotUsageSetter, catalog0 *Catalog) (OneShotUsageSlice, error) {
	for i := range oneShotUsages1 {
		oneShotUsages1[i].CatalogID = func() *types.Uint64 { return &catalog0.ID }()
	}

	ret, err := OneShotUsages.Insert(bob.ToMods(oneShotUsages1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCatalogOneShotUsages0: %w", err)
	}

	return ret, nil
}

func attachCatalogOneShotUsages0(ctx context.Context, exec bob.Executor, count int, oneShotUsages1 OneShotUsageSlice, catalog0 *Catalog) (OneShotUsageSlice, error) {
	setter := &OneShotUsageSetter{
		CatalogID: func() *types.Uint64 { return &catalog0.ID }(),
	}

	err := oneShotUsages1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCatalogOneShotUsages0: %w", err)
	}

	return oneShotUsages1, nil
}

func (catalog0 *Catalog) InsertOneShotUsages(ctx context.Context, exec bob.Executor, related ...*OneShotUsageSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	oneShotUsages1, err := insertCatalogOneShotUsages0(ctx, exec, related, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.OneShotUsages = append(catalog0.R.OneShotUsages, oneShotUsages1...)

	for _, rel := range oneShotUsages1 {
		rel.R.Catalog = catalog0
	}
	return nil
}

func (catalog0 *Catalog) AttachOneShotUsages(ctx context.Context, exec bob.Executor, related ...*OneShotUsage) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	oneShotUsages1 := OneShotUsageSlice(related)

	_, err = attachCatalogOneShotUsages0(ctx, exec, len(related), oneShotUsages1, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.OneShotUsages = append(catalog0.R.OneShotUsages, oneShotUsages1...)

	for _, rel := range related {
		rel.R.Catalog = catalog0
	}

	return nil
}

func insertCatalogSubscriptions0(ctx context.Context, exec bob.Executor, subscriptions1 []*SubscriptionSetter, catalog0 *Catalog) (SubscriptionSlice, error) {
	for i := range subscriptions1 {
		subscriptions1[i].CatalogID = func() *types.Uint64 { return &catalog0.ID }()
	}

	ret, err := Subscriptions.Insert(bob.ToMods(subscriptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCatalogSubscriptions0: %w", err)
	}

	return ret, nil
}

func attachCatalogSubscriptions0(ctx context.Context, exec bob.Executor, count int, subscriptions1 SubscriptionSlice, catalog0 *Catalog) (SubscriptionSlice, error) {
	setter := &SubscriptionSetter{
		CatalogID: func() *types.Uint64 { return &catalog0.ID }(),
	}

	err := subscriptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCatalogSubscriptions0: %w", err)
	}

	return subscriptions1, nil
}

func (catalog0 *Catalog) InsertSubscriptions(ctx context.Context, exec bob.Executor, related ...*SubscriptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	subscriptions1, err := insertCatalogSubscriptions0(ctx, exec, related, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.Subscriptions = append(catalog0.R.Subscriptions, subscriptions1...)

	for _, rel := range subscriptions1 {
		rel.R.Catalog = catalog0
	}
	return nil
}

func (catalog0 *Catalog) AttachSubscriptions(ctx context.Context, exec bob.Executor, related ...*Subscription) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	subscriptions1 := SubscriptionSlice(related)

	_, err = attachCatalogSubscriptions0(ctx, exec, len(related), subscriptions1, catalog0)
	if err != nil {
		return err
	}

	catalog0.R.Subscriptions = append(catalog0.R.Subscriptions, subscriptions1...)

	for _, rel := range related {
		rel.R.Catalog = catalog0
	}

	return nil
}
