// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	enums "github.com/flora/api/internal/bob/enums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// CatalogPrice is an object representing the database table.
type CatalogPrice struct {
	ID           types.Uint64                              `db:"id,pk,autoincr" json:"id" db:"id"`
	CatalogID    types.Uint64                              `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	Amount       int64                                     `db:"amount" json:"amount" db:"amount"`
	BillingType  enums.CatalogPricesBillingType            `db:"billing_type" json:"billing_type" db:"billing_type"`
	BillingCycle sql.Null[enums.CatalogPricesBillingCycle] `db:"billing_cycle" json:"billing_cycle" db:"billing_cycle"`
	StartDate    time.Time                                 `db:"start_date" json:"start_date" db:"start_date"`
	EndDate      sql.Null[time.Time]                       `db:"end_date" json:"end_date" db:"end_date"`
	CreatedAt    time.Time                                 `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt    time.Time                                 `db:"updated_at" json:"updated_at" db:"updated_at"`

	R catalogPriceR `db:"-" json:"-" db:"-"`
}

// CatalogPriceSlice is an alias for a slice of pointers to CatalogPrice.
// This should almost always be used instead of []*CatalogPrice.
type CatalogPriceSlice []*CatalogPrice

// CatalogPrices contains methods to work with the catalog_prices table
var CatalogPrices = mysql.NewTablex[*CatalogPrice, CatalogPriceSlice, *CatalogPriceSetter]("catalog_prices", buildCatalogPriceColumns("catalog_prices"), []string{"id"})

// CatalogPricesQuery is a query on the catalog_prices table
type CatalogPricesQuery = *mysql.ViewQuery[*CatalogPrice, CatalogPriceSlice]

// catalogPriceR is where relationships are stored.
type catalogPriceR struct {
	Catalog *Catalog `json:"Catalog" db:"Catalog"` // fk_catalog_prices_catalog
}

func buildCatalogPriceColumns(alias string) catalogPriceColumns {
	return catalogPriceColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "catalog_id", "amount", "billing_type", "billing_cycle", "start_date", "end_date", "created_at", "updated_at",
		).WithParent("catalog_prices"),
		tableAlias:   alias,
		ID:           mysql.Quote(alias, "id"),
		CatalogID:    mysql.Quote(alias, "catalog_id"),
		Amount:       mysql.Quote(alias, "amount"),
		BillingType:  mysql.Quote(alias, "billing_type"),
		BillingCycle: mysql.Quote(alias, "billing_cycle"),
		StartDate:    mysql.Quote(alias, "start_date"),
		EndDate:      mysql.Quote(alias, "end_date"),
		CreatedAt:    mysql.Quote(alias, "created_at"),
		UpdatedAt:    mysql.Quote(alias, "updated_at"),
	}
}

type catalogPriceColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           mysql.Expression
	CatalogID    mysql.Expression
	Amount       mysql.Expression
	BillingType  mysql.Expression
	BillingCycle mysql.Expression
	StartDate    mysql.Expression
	EndDate      mysql.Expression
	CreatedAt    mysql.Expression
	UpdatedAt    mysql.Expression
}

func (c catalogPriceColumns) Alias() string {
	return c.tableAlias
}

func (catalogPriceColumns) AliasedAs(alias string) catalogPriceColumns {
	return buildCatalogPriceColumns(alias)
}

// CatalogPriceSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CatalogPriceSetter struct {
	ID           *types.Uint64                              `db:"id,pk,autoincr" json:"id" db:"id"`
	CatalogID    *types.Uint64                              `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	Amount       *int64                                     `db:"amount" json:"amount" db:"amount"`
	BillingType  *enums.CatalogPricesBillingType            `db:"billing_type" json:"billing_type" db:"billing_type"`
	BillingCycle *sql.Null[enums.CatalogPricesBillingCycle] `db:"billing_cycle" json:"billing_cycle" db:"billing_cycle"`
	StartDate    *time.Time                                 `db:"start_date" json:"start_date" db:"start_date"`
	EndDate      *sql.Null[time.Time]                       `db:"end_date" json:"end_date" db:"end_date"`
	CreatedAt    *time.Time                                 `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt    *time.Time                                 `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s CatalogPriceSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.CatalogID != nil {
		vals = append(vals, "catalog_id")
	}
	if s.Amount != nil {
		vals = append(vals, "amount")
	}
	if s.BillingType != nil {
		vals = append(vals, "billing_type")
	}
	if s.BillingCycle != nil {
		vals = append(vals, "billing_cycle")
	}
	if s.StartDate != nil {
		vals = append(vals, "start_date")
	}
	if s.EndDate != nil {
		vals = append(vals, "end_date")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CatalogPriceSetter) Overwrite(t *CatalogPrice) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.CatalogID != nil {
		t.CatalogID = func() types.Uint64 {
			if s.CatalogID == nil {
				return *new(types.Uint64)
			}
			return *s.CatalogID
		}()
	}
	if s.Amount != nil {
		t.Amount = func() int64 {
			if s.Amount == nil {
				return *new(int64)
			}
			return *s.Amount
		}()
	}
	if s.BillingType != nil {
		t.BillingType = func() enums.CatalogPricesBillingType {
			if s.BillingType == nil {
				return *new(enums.CatalogPricesBillingType)
			}
			return *s.BillingType
		}()
	}
	if s.BillingCycle != nil {
		t.BillingCycle = func() sql.Null[enums.CatalogPricesBillingCycle] {
			if s.BillingCycle == nil {
				return *new(sql.Null[enums.CatalogPricesBillingCycle])
			}
			v := s.BillingCycle
			return *v
		}()
	}
	if s.StartDate != nil {
		t.StartDate = func() time.Time {
			if s.StartDate == nil {
				return *new(time.Time)
			}
			return *s.StartDate
		}()
	}
	if s.EndDate != nil {
		t.EndDate = func() sql.Null[time.Time] {
			if s.EndDate == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.EndDate
			return *v
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *CatalogPriceSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CatalogPrices.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CatalogID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.CatalogID == nil {
					return *new(types.Uint64)
				}
				return *s.CatalogID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Amount != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() int64 {
				if s.Amount == nil {
					return *new(int64)
				}
				return *s.Amount
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.BillingType != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() enums.CatalogPricesBillingType {
				if s.BillingType == nil {
					return *new(enums.CatalogPricesBillingType)
				}
				return *s.BillingType
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.BillingCycle != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[enums.CatalogPricesBillingCycle] {
				if s.BillingCycle == nil {
					return *new(sql.Null[enums.CatalogPricesBillingCycle])
				}
				v := s.BillingCycle
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.StartDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.StartDate == nil {
					return *new(time.Time)
				}
				return *s.StartDate
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.EndDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[time.Time] {
				if s.EndDate == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.EndDate
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s CatalogPriceSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("catalog_prices")...)
}

func (s CatalogPriceSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.CatalogID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "catalog_id")...),
			mysql.Arg(s.CatalogID),
		}})
	}

	if s.Amount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "amount")...),
			mysql.Arg(s.Amount),
		}})
	}

	if s.BillingType != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "billing_type")...),
			mysql.Arg(s.BillingType),
		}})
	}

	if s.BillingCycle != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "billing_cycle")...),
			mysql.Arg(s.BillingCycle),
		}})
	}

	if s.StartDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "start_date")...),
			mysql.Arg(s.StartDate),
		}})
	}

	if s.EndDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "end_date")...),
			mysql.Arg(s.EndDate),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCatalogPrice retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCatalogPrice(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*CatalogPrice, error) {
	if len(cols) == 0 {
		return CatalogPrices.Query(
			sm.Where(CatalogPrices.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CatalogPrices.Query(
		sm.Where(CatalogPrices.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(CatalogPrices.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CatalogPriceExists checks the presence of a single record by primary key
func CatalogPriceExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return CatalogPrices.Query(
		sm.Where(CatalogPrices.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CatalogPrice is retrieved from the database
func (o *CatalogPrice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CatalogPrices.AfterSelectHooks.RunHooks(ctx, exec, CatalogPriceSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CatalogPrices.AfterInsertHooks.RunHooks(ctx, exec, CatalogPriceSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CatalogPrices.AfterUpdateHooks.RunHooks(ctx, exec, CatalogPriceSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CatalogPrices.AfterDeleteHooks.RunHooks(ctx, exec, CatalogPriceSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the CatalogPrice
func (o *CatalogPrice) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *CatalogPrice) pkEQ() dialect.Expression {
	return mysql.Quote("catalog_prices", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CatalogPrice
func (o *CatalogPrice) Update(ctx context.Context, exec bob.Executor, s *CatalogPriceSetter) error {
	_, err := CatalogPrices.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single CatalogPrice record with an executor
func (o *CatalogPrice) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CatalogPrices.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CatalogPrice using the executor
func (o *CatalogPrice) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CatalogPrices.Query(
		sm.Where(CatalogPrices.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CatalogPriceSlice is retrieved from the database
func (o CatalogPriceSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CatalogPrices.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CatalogPrices.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CatalogPrices.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CatalogPrices.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CatalogPriceSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("catalog_prices", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CatalogPriceSlice) copyMatchingRows(from ...*CatalogPrice) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CatalogPriceSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CatalogPrices.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CatalogPrice:
				o.copyMatchingRows(retrieved)
			case []*CatalogPrice:
				o.copyMatchingRows(retrieved...)
			case CatalogPriceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CatalogPrice or a slice of CatalogPrice
				// then run the AfterUpdateHooks on the slice
				_, err = CatalogPrices.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CatalogPriceSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CatalogPrices.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CatalogPrice:
				o.copyMatchingRows(retrieved)
			case []*CatalogPrice:
				o.copyMatchingRows(retrieved...)
			case CatalogPriceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CatalogPrice or a slice of CatalogPrice
				// then run the AfterDeleteHooks on the slice
				_, err = CatalogPrices.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CatalogPriceSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CatalogPriceSetter) error {
	_, err := CatalogPrices.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o CatalogPriceSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CatalogPrices.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CatalogPriceSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CatalogPrices.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Catalog starts a query for related objects on catalogs
func (o *CatalogPrice) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	return Catalogs.Query(append(mods,
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(o.CatalogID))),
	)...)
}

func (os CatalogPriceSlice) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.CatalogID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Catalogs.Query(append(mods,
		sm.Where(mysql.Group(Catalogs.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCatalogPriceCatalog0(ctx context.Context, exec bob.Executor, count int, catalogPrice0 *CatalogPrice, catalog1 *Catalog) (*CatalogPrice, error) {
	setter := &CatalogPriceSetter{
		CatalogID: func() *types.Uint64 { return &catalog1.ID }(),
	}

	err := catalogPrice0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCatalogPriceCatalog0: %w", err)
	}

	return catalogPrice0, nil
}

func (catalogPrice0 *CatalogPrice) InsertCatalog(ctx context.Context, exec bob.Executor, related *CatalogSetter) error {
	var err error

	catalog1, err := Catalogs.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCatalogPriceCatalog0(ctx, exec, 1, catalogPrice0, catalog1)
	if err != nil {
		return err
	}

	catalogPrice0.R.Catalog = catalog1

	catalog1.R.CatalogPrices = append(catalog1.R.CatalogPrices, catalogPrice0)

	return nil
}

func (catalogPrice0 *CatalogPrice) AttachCatalog(ctx context.Context, exec bob.Executor, catalog1 *Catalog) error {
	var err error

	_, err = attachCatalogPriceCatalog0(ctx, exec, 1, catalogPrice0, catalog1)
	if err != nil {
		return err
	}

	catalogPrice0.R.Catalog = catalog1

	catalog1.R.CatalogPrices = append(catalog1.R.CatalogPrices, catalogPrice0)

	return nil
}
