// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// OneShotUsage is an object representing the database table.
type OneShotUsage struct {
	ID             types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID      types.Uint64 `db:"account_id" json:"account_id" db:"account_id"`
	CatalogID      types.Uint64 `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	IdempotencyKey string       `db:"idempotency_key" json:"idempotency_key" db:"idempotency_key"`
	UsedAt         time.Time    `db:"used_at" json:"used_at" db:"used_at"`
	CreatedAt      time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`

	R oneShotUsageR `db:"-" json:"-" db:"-"`
}

// OneShotUsageSlice is an alias for a slice of pointers to OneShotUsage.
// This should almost always be used instead of []*OneShotUsage.
type OneShotUsageSlice []*OneShotUsage

// OneShotUsages contains methods to work with the one_shot_usages table
var OneShotUsages = mysql.NewTablex[*OneShotUsage, OneShotUsageSlice, *OneShotUsageSetter]("one_shot_usages", buildOneShotUsageColumns("one_shot_usages"), []string{"id"}, []string{"idempotency_key"})

// OneShotUsagesQuery is a query on the one_shot_usages table
type OneShotUsagesQuery = *mysql.ViewQuery[*OneShotUsage, OneShotUsageSlice]

// oneShotUsageR is where relationships are stored.
type oneShotUsageR struct {
	Account            *Account               `json:"Account" db:"Account"`                       // fk_one_shot_usages_account
	Catalog            *Catalog               `json:"Catalog" db:"Catalog"`                       // fk_one_shot_usages_catalog
	ServiceChargeItems ServiceChargeItemSlice `json:"ServiceChargeItems" db:"ServiceChargeItems"` // fk_service_charge_items_one_shot
}

func buildOneShotUsageColumns(alias string) oneShotUsageColumns {
	return oneShotUsageColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "account_id", "catalog_id", "idempotency_key", "used_at", "created_at", "updated_at",
		).WithParent("one_shot_usages"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		AccountID:      mysql.Quote(alias, "account_id"),
		CatalogID:      mysql.Quote(alias, "catalog_id"),
		IdempotencyKey: mysql.Quote(alias, "idempotency_key"),
		UsedAt:         mysql.Quote(alias, "used_at"),
		CreatedAt:      mysql.Quote(alias, "created_at"),
		UpdatedAt:      mysql.Quote(alias, "updated_at"),
	}
}

type oneShotUsageColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	AccountID      mysql.Expression
	CatalogID      mysql.Expression
	IdempotencyKey mysql.Expression
	UsedAt         mysql.Expression
	CreatedAt      mysql.Expression
	UpdatedAt      mysql.Expression
}

func (c oneShotUsageColumns) Alias() string {
	return c.tableAlias
}

func (oneShotUsageColumns) AliasedAs(alias string) oneShotUsageColumns {
	return buildOneShotUsageColumns(alias)
}

// OneShotUsageSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OneShotUsageSetter struct {
	ID             *types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID      *types.Uint64 `db:"account_id" json:"account_id" db:"account_id"`
	CatalogID      *types.Uint64 `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	IdempotencyKey *string       `db:"idempotency_key" json:"idempotency_key" db:"idempotency_key"`
	UsedAt         *time.Time    `db:"used_at" json:"used_at" db:"used_at"`
	CreatedAt      *time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt      *time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s OneShotUsageSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.AccountID != nil {
		vals = append(vals, "account_id")
	}
	if s.CatalogID != nil {
		vals = append(vals, "catalog_id")
	}
	if s.IdempotencyKey != nil {
		vals = append(vals, "idempotency_key")
	}
	if s.UsedAt != nil {
		vals = append(vals, "used_at")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OneShotUsageSetter) Overwrite(t *OneShotUsage) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.AccountID != nil {
		t.AccountID = func() types.Uint64 {
			if s.AccountID == nil {
				return *new(types.Uint64)
			}
			return *s.AccountID
		}()
	}
	if s.CatalogID != nil {
		t.CatalogID = func() types.Uint64 {
			if s.CatalogID == nil {
				return *new(types.Uint64)
			}
			return *s.CatalogID
		}()
	}
	if s.IdempotencyKey != nil {
		t.IdempotencyKey = func() string {
			if s.IdempotencyKey == nil {
				return *new(string)
			}
			return *s.IdempotencyKey
		}()
	}
	if s.UsedAt != nil {
		t.UsedAt = func() time.Time {
			if s.UsedAt == nil {
				return *new(time.Time)
			}
			return *s.UsedAt
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *OneShotUsageSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OneShotUsages.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.AccountID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.AccountID == nil {
					return *new(types.Uint64)
				}
				return *s.AccountID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CatalogID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.CatalogID == nil {
					return *new(types.Uint64)
				}
				return *s.CatalogID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.IdempotencyKey != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.IdempotencyKey == nil {
					return *new(string)
				}
				return *s.IdempotencyKey
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UsedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UsedAt == nil {
					return *new(time.Time)
				}
				return *s.UsedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s OneShotUsageSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("one_shot_usages")...)
}

func (s OneShotUsageSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.AccountID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "account_id")...),
			mysql.Arg(s.AccountID),
		}})
	}

	if s.CatalogID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "catalog_id")...),
			mysql.Arg(s.CatalogID),
		}})
	}

	if s.IdempotencyKey != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "idempotency_key")...),
			mysql.Arg(s.IdempotencyKey),
		}})
	}

	if s.UsedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "used_at")...),
			mysql.Arg(s.UsedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOneShotUsage retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOneShotUsage(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*OneShotUsage, error) {
	if len(cols) == 0 {
		return OneShotUsages.Query(
			sm.Where(OneShotUsages.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return OneShotUsages.Query(
		sm.Where(OneShotUsages.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(OneShotUsages.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OneShotUsageExists checks the presence of a single record by primary key
func OneShotUsageExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return OneShotUsages.Query(
		sm.Where(OneShotUsages.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OneShotUsage is retrieved from the database
func (o *OneShotUsage) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OneShotUsages.AfterSelectHooks.RunHooks(ctx, exec, OneShotUsageSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OneShotUsages.AfterInsertHooks.RunHooks(ctx, exec, OneShotUsageSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OneShotUsages.AfterUpdateHooks.RunHooks(ctx, exec, OneShotUsageSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OneShotUsages.AfterDeleteHooks.RunHooks(ctx, exec, OneShotUsageSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OneShotUsage
func (o *OneShotUsage) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *OneShotUsage) pkEQ() dialect.Expression {
	return mysql.Quote("one_shot_usages", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OneShotUsage
func (o *OneShotUsage) Update(ctx context.Context, exec bob.Executor, s *OneShotUsageSetter) error {
	_, err := OneShotUsages.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single OneShotUsage record with an executor
func (o *OneShotUsage) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OneShotUsages.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OneShotUsage using the executor
func (o *OneShotUsage) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OneShotUsages.Query(
		sm.Where(OneShotUsages.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OneShotUsageSlice is retrieved from the database
func (o OneShotUsageSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OneShotUsages.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OneShotUsages.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OneShotUsages.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OneShotUsages.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OneShotUsageSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("one_shot_usages", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OneShotUsageSlice) copyMatchingRows(from ...*OneShotUsage) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OneShotUsageSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OneShotUsages.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OneShotUsage:
				o.copyMatchingRows(retrieved)
			case []*OneShotUsage:
				o.copyMatchingRows(retrieved...)
			case OneShotUsageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OneShotUsage or a slice of OneShotUsage
				// then run the AfterUpdateHooks on the slice
				_, err = OneShotUsages.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OneShotUsageSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OneShotUsages.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OneShotUsage:
				o.copyMatchingRows(retrieved)
			case []*OneShotUsage:
				o.copyMatchingRows(retrieved...)
			case OneShotUsageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OneShotUsage or a slice of OneShotUsage
				// then run the AfterDeleteHooks on the slice
				_, err = OneShotUsages.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OneShotUsageSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OneShotUsageSetter) error {
	_, err := OneShotUsages.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o OneShotUsageSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OneShotUsages.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OneShotUsageSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OneShotUsages.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Account starts a query for related objects on accounts
func (o *OneShotUsage) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(o.AccountID))),
	)...)
}

func (os OneShotUsageSlice) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.AccountID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Accounts.Query(append(mods,
		sm.Where(mysql.Group(Accounts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Catalog starts a query for related objects on catalogs
func (o *OneShotUsage) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	return Catalogs.Query(append(mods,
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(o.CatalogID))),
	)...)
}

func (os OneShotUsageSlice) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.CatalogID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Catalogs.Query(append(mods,
		sm.Where(mysql.Group(Catalogs.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ServiceChargeItems starts a query for related objects on service_charge_items
func (o *OneShotUsage) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	return ServiceChargeItems.Query(append(mods,
		sm.Where(ServiceChargeItems.Columns.OneShotUsageID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os OneShotUsageSlice) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceChargeItems.Query(append(mods,
		sm.Where(mysql.Group(ServiceChargeItems.Columns.OneShotUsageID).OP("IN", PKArgExpr)),
	)...)
}

func attachOneShotUsageAccount0(ctx context.Context, exec bob.Executor, count int, oneShotUsage0 *OneShotUsage, account1 *Account) (*OneShotUsage, error) {
	setter := &OneShotUsageSetter{
		AccountID: func() *types.Uint64 { return &account1.ID }(),
	}

	err := oneShotUsage0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOneShotUsageAccount0: %w", err)
	}

	return oneShotUsage0, nil
}

func (oneShotUsage0 *OneShotUsage) InsertAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOneShotUsageAccount0(ctx, exec, 1, oneShotUsage0, account1)
	if err != nil {
		return err
	}

	oneShotUsage0.R.Account = account1

	account1.R.OneShotUsages = append(account1.R.OneShotUsages, oneShotUsage0)

	return nil
}

func (oneShotUsage0 *OneShotUsage) AttachAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachOneShotUsageAccount0(ctx, exec, 1, oneShotUsage0, account1)
	if err != nil {
		return err
	}

	oneShotUsage0.R.Account = account1

	account1.R.OneShotUsages = append(account1.R.OneShotUsages, oneShotUsage0)

	return nil
}

func attachOneShotUsageCatalog0(ctx context.Context, exec bob.Executor, count int, oneShotUsage0 *OneShotUsage, catalog1 *Catalog) (*OneShotUsage, error) {
	setter := &OneShotUsageSetter{
		CatalogID: func() *types.Uint64 { return &catalog1.ID }(),
	}

	err := oneShotUsage0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOneShotUsageCatalog0: %w", err)
	}

	return oneShotUsage0, nil
}

func (oneShotUsage0 *OneShotUsage) InsertCatalog(ctx context.Context, exec bob.Executor, related *CatalogSetter) error {
	var err error

	catalog1, err := Catalogs.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOneShotUsageCatalog0(ctx, exec, 1, oneShotUsage0, catalog1)
	if err != nil {
		return err
	}

	oneShotUsage0.R.Catalog = catalog1

	catalog1.R.OneShotUsages = append(catalog1.R.OneShotUsages, oneShotUsage0)

	return nil
}

func (oneShotUsage0 *OneShotUsage) AttachCatalog(ctx context.Context, exec bob.Executor, catalog1 *Catalog) error {
	var err error

	_, err = attachOneShotUsageCatalog0(ctx, exec, 1, oneShotUsage0, catalog1)
	if err != nil {
		return err
	}

	oneShotUsage0.R.Catalog = catalog1

	catalog1.R.OneShotUsages = append(catalog1.R.OneShotUsages, oneShotUsage0)

	return nil
}

func insertOneShotUsageServiceChargeItems0(ctx context.Context, exec bob.Executor, serviceChargeItems1 []*ServiceChargeItemSetter, oneShotUsage0 *OneShotUsage) (ServiceChargeItemSlice, error) {
	for i := range serviceChargeItems1 {
		serviceChargeItems1[i].OneShotUsageID = func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: oneShotUsage0.ID, Valid: true}
			return &v
		}()
	}

	ret, err := ServiceChargeItems.Insert(bob.ToMods(serviceChargeItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOneShotUsageServiceChargeItems0: %w", err)
	}

	return ret, nil
}

func attachOneShotUsageServiceChargeItems0(ctx context.Context, exec bob.Executor, count int, serviceChargeItems1 ServiceChargeItemSlice, oneShotUsage0 *OneShotUsage) (ServiceChargeItemSlice, error) {
	setter := &ServiceChargeItemSetter{
		OneShotUsageID: func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: oneShotUsage0.ID, Valid: true}
			return &v
		}(),
	}

	err := serviceChargeItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOneShotUsageServiceChargeItems0: %w", err)
	}

	return serviceChargeItems1, nil
}

func (oneShotUsage0 *OneShotUsage) InsertServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serviceChargeItems1, err := insertOneShotUsageServiceChargeItems0(ctx, exec, related, oneShotUsage0)
	if err != nil {
		return err
	}

	oneShotUsage0.R.ServiceChargeItems = append(oneShotUsage0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range serviceChargeItems1 {
		rel.R.OneShotUsage = oneShotUsage0
	}
	return nil
}

func (oneShotUsage0 *OneShotUsage) AttachServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serviceChargeItems1 := ServiceChargeItemSlice(related)

	_, err = attachOneShotUsageServiceChargeItems0(ctx, exec, len(related), serviceChargeItems1, oneShotUsage0)
	if err != nil {
		return err
	}

	oneShotUsage0.R.ServiceChargeItems = append(oneShotUsage0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range related {
		rel.R.OneShotUsage = oneShotUsage0
	}

	return nil
}
