// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
)

// SchemaMigration is an object representing the database table.
type SchemaMigration struct {
	Version int64 `db:"version,pk" json:"version" db:"version"`
	Dirty   bool  `db:"dirty" json:"dirty" db:"dirty"`
}

// SchemaMigrationSlice is an alias for a slice of pointers to SchemaMigration.
// This should almost always be used instead of []*SchemaMigration.
type SchemaMigrationSlice []*SchemaMigration

// SchemaMigrations contains methods to work with the schema_migrations table
var SchemaMigrations = mysql.NewTablex[*SchemaMigration, SchemaMigrationSlice, *SchemaMigrationSetter]("schema_migrations", buildSchemaMigrationColumns("schema_migrations"), []string{"version"})

// SchemaMigrationsQuery is a query on the schema_migrations table
type SchemaMigrationsQuery = *mysql.ViewQuery[*SchemaMigration, SchemaMigrationSlice]

func buildSchemaMigrationColumns(alias string) schemaMigrationColumns {
	return schemaMigrationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"version", "dirty",
		).WithParent("schema_migrations"),
		tableAlias: alias,
		Version:    mysql.Quote(alias, "version"),
		Dirty:      mysql.Quote(alias, "dirty"),
	}
}

type schemaMigrationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	Version    mysql.Expression
	Dirty      mysql.Expression
}

func (c schemaMigrationColumns) Alias() string {
	return c.tableAlias
}

func (schemaMigrationColumns) AliasedAs(alias string) schemaMigrationColumns {
	return buildSchemaMigrationColumns(alias)
}

// SchemaMigrationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SchemaMigrationSetter struct {
	Version *int64 `db:"version,pk" json:"version" db:"version"`
	Dirty   *bool  `db:"dirty" json:"dirty" db:"dirty"`
}

func (s SchemaMigrationSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.Version != nil {
		vals = append(vals, "version")
	}
	if s.Dirty != nil {
		vals = append(vals, "dirty")
	}
	return vals
}

func (s SchemaMigrationSetter) Overwrite(t *SchemaMigration) {
	if s.Version != nil {
		t.Version = func() int64 {
			if s.Version == nil {
				return *new(int64)
			}
			return *s.Version
		}()
	}
	if s.Dirty != nil {
		t.Dirty = func() bool {
			if s.Dirty == nil {
				return *new(bool)
			}
			return *s.Dirty
		}()
	}
}

func (s *SchemaMigrationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SchemaMigrations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Version != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() int64 {
				if s.Version == nil {
					return *new(int64)
				}
				return *s.Version
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Dirty != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() bool {
				if s.Dirty == nil {
					return *new(bool)
				}
				return *s.Dirty
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s SchemaMigrationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("schema_migrations")...)
}

func (s SchemaMigrationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.Version != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "version")...),
			mysql.Arg(s.Version),
		}})
	}

	if s.Dirty != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "dirty")...),
			mysql.Arg(s.Dirty),
		}})
	}

	return exprs
}

// FindSchemaMigration retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSchemaMigration(ctx context.Context, exec bob.Executor, VersionPK int64, cols ...string) (*SchemaMigration, error) {
	if len(cols) == 0 {
		return SchemaMigrations.Query(
			sm.Where(SchemaMigrations.Columns.Version.EQ(mysql.Arg(VersionPK))),
		).One(ctx, exec)
	}

	return SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.Version.EQ(mysql.Arg(VersionPK))),
		sm.Columns(SchemaMigrations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SchemaMigrationExists checks the presence of a single record by primary key
func SchemaMigrationExists(ctx context.Context, exec bob.Executor, VersionPK int64) (bool, error) {
	return SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.Version.EQ(mysql.Arg(VersionPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SchemaMigration is retrieved from the database
func (o *SchemaMigration) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaMigrations.AfterSelectHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SchemaMigrations.AfterInsertHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the SchemaMigration
func (o *SchemaMigration) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.Version)
}

func (o *SchemaMigration) pkEQ() dialect.Expression {
	return mysql.Quote("schema_migrations", "version").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SchemaMigration
func (o *SchemaMigration) Update(ctx context.Context, exec bob.Executor, s *SchemaMigrationSetter) error {
	_, err := SchemaMigrations.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single SchemaMigration record with an executor
func (o *SchemaMigration) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SchemaMigrations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SchemaMigration using the executor
func (o *SchemaMigration) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.Version.EQ(mysql.Arg(o.Version))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SchemaMigrationSlice is retrieved from the database
func (o SchemaMigrationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaMigrations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SchemaMigrations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SchemaMigrationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("schema_migrations", "version").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SchemaMigrationSlice) copyMatchingRows(from ...*SchemaMigration) {
	for i, old := range o {
		for _, new := range from {
			if new.Version != old.Version {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SchemaMigrationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SchemaMigrations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SchemaMigration:
				o.copyMatchingRows(retrieved)
			case []*SchemaMigration:
				o.copyMatchingRows(retrieved...)
			case SchemaMigrationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SchemaMigration or a slice of SchemaMigration
				// then run the AfterUpdateHooks on the slice
				_, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SchemaMigrationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SchemaMigrations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SchemaMigration:
				o.copyMatchingRows(retrieved)
			case []*SchemaMigration:
				o.copyMatchingRows(retrieved...)
			case SchemaMigrationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SchemaMigration or a slice of SchemaMigration
				// then run the AfterDeleteHooks on the slice
				_, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SchemaMigrationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SchemaMigrationSetter) error {
	_, err := SchemaMigrations.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o SchemaMigrationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SchemaMigrations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SchemaMigrationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SchemaMigrations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
