// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// ServiceChargeItem is an object representing the database table.
type ServiceChargeItem struct {
	ID              types.Uint64           `db:"id,pk,autoincr" json:"id" db:"id"`
	Name            string                 `db:"name" json:"name" db:"name"`
	Amount          int64                  `db:"amount" json:"amount" db:"amount"`
	ServiceChargeID types.Uint64           `db:"service_charge_id" json:"service_charge_id" db:"service_charge_id"`
	OneShotUsageID  sql.Null[types.Uint64] `db:"one_shot_usage_id" json:"one_shot_usage_id" db:"one_shot_usage_id"`
	SubscriptionID  sql.Null[types.Uint64] `db:"subscription_id" json:"subscription_id" db:"subscription_id"`
	CreatedAt       time.Time              `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt       time.Time              `db:"updated_at" json:"updated_at" db:"updated_at"`

	R serviceChargeItemR `db:"-" json:"-" db:"-"`
}

// ServiceChargeItemSlice is an alias for a slice of pointers to ServiceChargeItem.
// This should almost always be used instead of []*ServiceChargeItem.
type ServiceChargeItemSlice []*ServiceChargeItem

// ServiceChargeItems contains methods to work with the service_charge_items table
var ServiceChargeItems = mysql.NewTablex[*ServiceChargeItem, ServiceChargeItemSlice, *ServiceChargeItemSetter]("service_charge_items", buildServiceChargeItemColumns("service_charge_items"), []string{"id"})

// ServiceChargeItemsQuery is a query on the service_charge_items table
type ServiceChargeItemsQuery = *mysql.ViewQuery[*ServiceChargeItem, ServiceChargeItemSlice]

// serviceChargeItemR is where relationships are stored.
type serviceChargeItemR struct {
	ServiceCharge *ServiceCharge `json:"ServiceCharge" db:"ServiceCharge"` // fk_service_charge_items_charge
	OneShotUsage  *OneShotUsage  `json:"OneShotUsage" db:"OneShotUsage"`   // fk_service_charge_items_one_shot
	Subscription  *Subscription  `json:"Subscription" db:"Subscription"`   // fk_service_charge_items_subscription
}

func buildServiceChargeItemColumns(alias string) serviceChargeItemColumns {
	return serviceChargeItemColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "amount", "service_charge_id", "one_shot_usage_id", "subscription_id", "created_at", "updated_at",
		).WithParent("service_charge_items"),
		tableAlias:      alias,
		ID:              mysql.Quote(alias, "id"),
		Name:            mysql.Quote(alias, "name"),
		Amount:          mysql.Quote(alias, "amount"),
		ServiceChargeID: mysql.Quote(alias, "service_charge_id"),
		OneShotUsageID:  mysql.Quote(alias, "one_shot_usage_id"),
		SubscriptionID:  mysql.Quote(alias, "subscription_id"),
		CreatedAt:       mysql.Quote(alias, "created_at"),
		UpdatedAt:       mysql.Quote(alias, "updated_at"),
	}
}

type serviceChargeItemColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              mysql.Expression
	Name            mysql.Expression
	Amount          mysql.Expression
	ServiceChargeID mysql.Expression
	OneShotUsageID  mysql.Expression
	SubscriptionID  mysql.Expression
	CreatedAt       mysql.Expression
	UpdatedAt       mysql.Expression
}

func (c serviceChargeItemColumns) Alias() string {
	return c.tableAlias
}

func (serviceChargeItemColumns) AliasedAs(alias string) serviceChargeItemColumns {
	return buildServiceChargeItemColumns(alias)
}

// ServiceChargeItemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ServiceChargeItemSetter struct {
	ID              *types.Uint64           `db:"id,pk,autoincr" json:"id" db:"id"`
	Name            *string                 `db:"name" json:"name" db:"name"`
	Amount          *int64                  `db:"amount" json:"amount" db:"amount"`
	ServiceChargeID *types.Uint64           `db:"service_charge_id" json:"service_charge_id" db:"service_charge_id"`
	OneShotUsageID  *sql.Null[types.Uint64] `db:"one_shot_usage_id" json:"one_shot_usage_id" db:"one_shot_usage_id"`
	SubscriptionID  *sql.Null[types.Uint64] `db:"subscription_id" json:"subscription_id" db:"subscription_id"`
	CreatedAt       *time.Time              `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt       *time.Time              `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s ServiceChargeItemSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Amount != nil {
		vals = append(vals, "amount")
	}
	if s.ServiceChargeID != nil {
		vals = append(vals, "service_charge_id")
	}
	if s.OneShotUsageID != nil {
		vals = append(vals, "one_shot_usage_id")
	}
	if s.SubscriptionID != nil {
		vals = append(vals, "subscription_id")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ServiceChargeItemSetter) Overwrite(t *ServiceChargeItem) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Amount != nil {
		t.Amount = func() int64 {
			if s.Amount == nil {
				return *new(int64)
			}
			return *s.Amount
		}()
	}
	if s.ServiceChargeID != nil {
		t.ServiceChargeID = func() types.Uint64 {
			if s.ServiceChargeID == nil {
				return *new(types.Uint64)
			}
			return *s.ServiceChargeID
		}()
	}
	if s.OneShotUsageID != nil {
		t.OneShotUsageID = func() sql.Null[types.Uint64] {
			if s.OneShotUsageID == nil {
				return *new(sql.Null[types.Uint64])
			}
			v := s.OneShotUsageID
			return *v
		}()
	}
	if s.SubscriptionID != nil {
		t.SubscriptionID = func() sql.Null[types.Uint64] {
			if s.SubscriptionID == nil {
				return *new(sql.Null[types.Uint64])
			}
			v := s.SubscriptionID
			return *v
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *ServiceChargeItemSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ServiceChargeItems.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Amount != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() int64 {
				if s.Amount == nil {
					return *new(int64)
				}
				return *s.Amount
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ServiceChargeID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ServiceChargeID == nil {
					return *new(types.Uint64)
				}
				return *s.ServiceChargeID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.OneShotUsageID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[types.Uint64] {
				if s.OneShotUsageID == nil {
					return *new(sql.Null[types.Uint64])
				}
				v := s.OneShotUsageID
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.SubscriptionID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[types.Uint64] {
				if s.SubscriptionID == nil {
					return *new(sql.Null[types.Uint64])
				}
				v := s.SubscriptionID
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ServiceChargeItemSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("service_charge_items")...)
}

func (s ServiceChargeItemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Amount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "amount")...),
			mysql.Arg(s.Amount),
		}})
	}

	if s.ServiceChargeID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "service_charge_id")...),
			mysql.Arg(s.ServiceChargeID),
		}})
	}

	if s.OneShotUsageID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "one_shot_usage_id")...),
			mysql.Arg(s.OneShotUsageID),
		}})
	}

	if s.SubscriptionID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "subscription_id")...),
			mysql.Arg(s.SubscriptionID),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindServiceChargeItem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindServiceChargeItem(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*ServiceChargeItem, error) {
	if len(cols) == 0 {
		return ServiceChargeItems.Query(
			sm.Where(ServiceChargeItems.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ServiceChargeItems.Query(
		sm.Where(ServiceChargeItems.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(ServiceChargeItems.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ServiceChargeItemExists checks the presence of a single record by primary key
func ServiceChargeItemExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return ServiceChargeItems.Query(
		sm.Where(ServiceChargeItems.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ServiceChargeItem is retrieved from the database
func (o *ServiceChargeItem) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ServiceChargeItems.AfterSelectHooks.RunHooks(ctx, exec, ServiceChargeItemSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ServiceChargeItems.AfterInsertHooks.RunHooks(ctx, exec, ServiceChargeItemSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ServiceChargeItems.AfterUpdateHooks.RunHooks(ctx, exec, ServiceChargeItemSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ServiceChargeItems.AfterDeleteHooks.RunHooks(ctx, exec, ServiceChargeItemSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ServiceChargeItem
func (o *ServiceChargeItem) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *ServiceChargeItem) pkEQ() dialect.Expression {
	return mysql.Quote("service_charge_items", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ServiceChargeItem
func (o *ServiceChargeItem) Update(ctx context.Context, exec bob.Executor, s *ServiceChargeItemSetter) error {
	_, err := ServiceChargeItems.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single ServiceChargeItem record with an executor
func (o *ServiceChargeItem) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ServiceChargeItems.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ServiceChargeItem using the executor
func (o *ServiceChargeItem) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ServiceChargeItems.Query(
		sm.Where(ServiceChargeItems.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ServiceChargeItemSlice is retrieved from the database
func (o ServiceChargeItemSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ServiceChargeItems.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ServiceChargeItems.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ServiceChargeItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ServiceChargeItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ServiceChargeItemSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("service_charge_items", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ServiceChargeItemSlice) copyMatchingRows(from ...*ServiceChargeItem) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ServiceChargeItemSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ServiceChargeItems.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ServiceChargeItem:
				o.copyMatchingRows(retrieved)
			case []*ServiceChargeItem:
				o.copyMatchingRows(retrieved...)
			case ServiceChargeItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ServiceChargeItem or a slice of ServiceChargeItem
				// then run the AfterUpdateHooks on the slice
				_, err = ServiceChargeItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ServiceChargeItemSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ServiceChargeItems.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ServiceChargeItem:
				o.copyMatchingRows(retrieved)
			case []*ServiceChargeItem:
				o.copyMatchingRows(retrieved...)
			case ServiceChargeItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ServiceChargeItem or a slice of ServiceChargeItem
				// then run the AfterDeleteHooks on the slice
				_, err = ServiceChargeItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ServiceChargeItemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ServiceChargeItemSetter) error {
	_, err := ServiceChargeItems.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ServiceChargeItemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ServiceChargeItems.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ServiceChargeItemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ServiceChargeItems.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ServiceCharge starts a query for related objects on service_charges
func (o *ServiceChargeItem) ServiceCharge(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargesQuery {
	return ServiceCharges.Query(append(mods,
		sm.Where(ServiceCharges.Columns.ID.EQ(mysql.Arg(o.ServiceChargeID))),
	)...)
}

func (os ServiceChargeItemSlice) ServiceCharge(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ServiceChargeID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceCharges.Query(append(mods,
		sm.Where(mysql.Group(ServiceCharges.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OneShotUsage starts a query for related objects on one_shot_usages
func (o *ServiceChargeItem) OneShotUsage(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	return OneShotUsages.Query(append(mods,
		sm.Where(OneShotUsages.Columns.ID.EQ(mysql.Arg(o.OneShotUsageID))),
	)...)
}

func (os ServiceChargeItemSlice) OneShotUsage(mods ...bob.Mod[*dialect.SelectQuery]) OneShotUsagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.OneShotUsageID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OneShotUsages.Query(append(mods,
		sm.Where(mysql.Group(OneShotUsages.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Subscription starts a query for related objects on subscriptions
func (o *ServiceChargeItem) Subscription(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	return Subscriptions.Query(append(mods,
		sm.Where(Subscriptions.Columns.ID.EQ(mysql.Arg(o.SubscriptionID))),
	)...)
}

func (os ServiceChargeItemSlice) Subscription(mods ...bob.Mod[*dialect.SelectQuery]) SubscriptionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.SubscriptionID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Subscriptions.Query(append(mods,
		sm.Where(mysql.Group(Subscriptions.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachServiceChargeItemServiceCharge0(ctx context.Context, exec bob.Executor, count int, serviceChargeItem0 *ServiceChargeItem, serviceCharge1 *ServiceCharge) (*ServiceChargeItem, error) {
	setter := &ServiceChargeItemSetter{
		ServiceChargeID: func() *types.Uint64 { return &serviceCharge1.ID }(),
	}

	err := serviceChargeItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeItemServiceCharge0: %w", err)
	}

	return serviceChargeItem0, nil
}

func (serviceChargeItem0 *ServiceChargeItem) InsertServiceCharge(ctx context.Context, exec bob.Executor, related *ServiceChargeSetter) error {
	var err error

	serviceCharge1, err := ServiceCharges.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServiceChargeItemServiceCharge0(ctx, exec, 1, serviceChargeItem0, serviceCharge1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.ServiceCharge = serviceCharge1

	serviceCharge1.R.ServiceChargeItems = append(serviceCharge1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}

func (serviceChargeItem0 *ServiceChargeItem) AttachServiceCharge(ctx context.Context, exec bob.Executor, serviceCharge1 *ServiceCharge) error {
	var err error

	_, err = attachServiceChargeItemServiceCharge0(ctx, exec, 1, serviceChargeItem0, serviceCharge1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.ServiceCharge = serviceCharge1

	serviceCharge1.R.ServiceChargeItems = append(serviceCharge1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}

func attachServiceChargeItemOneShotUsage0(ctx context.Context, exec bob.Executor, count int, serviceChargeItem0 *ServiceChargeItem, oneShotUsage1 *OneShotUsage) (*ServiceChargeItem, error) {
	setter := &ServiceChargeItemSetter{
		OneShotUsageID: func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: oneShotUsage1.ID, Valid: true}
			return &v
		}(),
	}

	err := serviceChargeItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeItemOneShotUsage0: %w", err)
	}

	return serviceChargeItem0, nil
}

func (serviceChargeItem0 *ServiceChargeItem) InsertOneShotUsage(ctx context.Context, exec bob.Executor, related *OneShotUsageSetter) error {
	var err error

	oneShotUsage1, err := OneShotUsages.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServiceChargeItemOneShotUsage0(ctx, exec, 1, serviceChargeItem0, oneShotUsage1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.OneShotUsage = oneShotUsage1

	oneShotUsage1.R.ServiceChargeItems = append(oneShotUsage1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}

func (serviceChargeItem0 *ServiceChargeItem) AttachOneShotUsage(ctx context.Context, exec bob.Executor, oneShotUsage1 *OneShotUsage) error {
	var err error

	_, err = attachServiceChargeItemOneShotUsage0(ctx, exec, 1, serviceChargeItem0, oneShotUsage1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.OneShotUsage = oneShotUsage1

	oneShotUsage1.R.ServiceChargeItems = append(oneShotUsage1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}

func attachServiceChargeItemSubscription0(ctx context.Context, exec bob.Executor, count int, serviceChargeItem0 *ServiceChargeItem, subscription1 *Subscription) (*ServiceChargeItem, error) {
	setter := &ServiceChargeItemSetter{
		SubscriptionID: func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: subscription1.ID, Valid: true}
			return &v
		}(),
	}

	err := serviceChargeItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeItemSubscription0: %w", err)
	}

	return serviceChargeItem0, nil
}

func (serviceChargeItem0 *ServiceChargeItem) InsertSubscription(ctx context.Context, exec bob.Executor, related *SubscriptionSetter) error {
	var err error

	subscription1, err := Subscriptions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServiceChargeItemSubscription0(ctx, exec, 1, serviceChargeItem0, subscription1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.Subscription = subscription1

	subscription1.R.ServiceChargeItems = append(subscription1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}

func (serviceChargeItem0 *ServiceChargeItem) AttachSubscription(ctx context.Context, exec bob.Executor, subscription1 *Subscription) error {
	var err error

	_, err = attachServiceChargeItemSubscription0(ctx, exec, 1, serviceChargeItem0, subscription1)
	if err != nil {
		return err
	}

	serviceChargeItem0.R.Subscription = subscription1

	subscription1.R.ServiceChargeItems = append(subscription1.R.ServiceChargeItems, serviceChargeItem0)

	return nil
}
