// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// ServiceCharge is an object representing the database table.
type ServiceCharge struct {
	ID             types.Uint64           `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID      types.Uint64           `db:"account_id" json:"account_id" db:"account_id"`
	StartDate      time.Time              `db:"start_date" json:"start_date" db:"start_date"`
	EndDate        time.Time              `db:"end_date" json:"end_date" db:"end_date"`
	Amount         int64                  `db:"amount" json:"amount" db:"amount"`
	LatestStatusID sql.Null[types.Uint64] `db:"latest_status_id" json:"latest_status_id" db:"latest_status_id"`
	CreatedAt      time.Time              `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt      time.Time              `db:"updated_at" json:"updated_at" db:"updated_at"`

	R serviceChargeR `db:"-" json:"-" db:"-"`
}

// ServiceChargeSlice is an alias for a slice of pointers to ServiceCharge.
// This should almost always be used instead of []*ServiceCharge.
type ServiceChargeSlice []*ServiceCharge

// ServiceCharges contains methods to work with the service_charges table
var ServiceCharges = mysql.NewTablex[*ServiceCharge, ServiceChargeSlice, *ServiceChargeSetter]("service_charges", buildServiceChargeColumns("service_charges"), []string{"id"})

// ServiceChargesQuery is a query on the service_charges table
type ServiceChargesQuery = *mysql.ViewQuery[*ServiceCharge, ServiceChargeSlice]

// serviceChargeR is where relationships are stored.
type serviceChargeR struct {
	ServiceChargeItems              ServiceChargeItemSlice   `json:"ServiceChargeItems" db:"ServiceChargeItems"`                           // fk_service_charge_items_charge
	ServiceChargeStatuses           ServiceChargeStatusSlice `json:"ServiceChargeStatuses" db:"ServiceChargeStatuses"`                     // fk_service_charge_statuses_charge
	Account                         *Account                 `json:"Account" db:"Account"`                                                 // fk_service_charges_account
	LatestStatusServiceChargeStatus *ServiceChargeStatus     `json:"LatestStatusServiceChargeStatus" db:"LatestStatusServiceChargeStatus"` // fk_service_charges_latest_status
}

func buildServiceChargeColumns(alias string) serviceChargeColumns {
	return serviceChargeColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "account_id", "start_date", "end_date", "amount", "latest_status_id", "created_at", "updated_at",
		).WithParent("service_charges"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		AccountID:      mysql.Quote(alias, "account_id"),
		StartDate:      mysql.Quote(alias, "start_date"),
		EndDate:        mysql.Quote(alias, "end_date"),
		Amount:         mysql.Quote(alias, "amount"),
		LatestStatusID: mysql.Quote(alias, "latest_status_id"),
		CreatedAt:      mysql.Quote(alias, "created_at"),
		UpdatedAt:      mysql.Quote(alias, "updated_at"),
	}
}

type serviceChargeColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	AccountID      mysql.Expression
	StartDate      mysql.Expression
	EndDate        mysql.Expression
	Amount         mysql.Expression
	LatestStatusID mysql.Expression
	CreatedAt      mysql.Expression
	UpdatedAt      mysql.Expression
}

func (c serviceChargeColumns) Alias() string {
	return c.tableAlias
}

func (serviceChargeColumns) AliasedAs(alias string) serviceChargeColumns {
	return buildServiceChargeColumns(alias)
}

// ServiceChargeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ServiceChargeSetter struct {
	ID             *types.Uint64           `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID      *types.Uint64           `db:"account_id" json:"account_id" db:"account_id"`
	StartDate      *time.Time              `db:"start_date" json:"start_date" db:"start_date"`
	EndDate        *time.Time              `db:"end_date" json:"end_date" db:"end_date"`
	Amount         *int64                  `db:"amount" json:"amount" db:"amount"`
	LatestStatusID *sql.Null[types.Uint64] `db:"latest_status_id" json:"latest_status_id" db:"latest_status_id"`
	CreatedAt      *time.Time              `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt      *time.Time              `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s ServiceChargeSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.AccountID != nil {
		vals = append(vals, "account_id")
	}
	if s.StartDate != nil {
		vals = append(vals, "start_date")
	}
	if s.EndDate != nil {
		vals = append(vals, "end_date")
	}
	if s.Amount != nil {
		vals = append(vals, "amount")
	}
	if s.LatestStatusID != nil {
		vals = append(vals, "latest_status_id")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ServiceChargeSetter) Overwrite(t *ServiceCharge) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.AccountID != nil {
		t.AccountID = func() types.Uint64 {
			if s.AccountID == nil {
				return *new(types.Uint64)
			}
			return *s.AccountID
		}()
	}
	if s.StartDate != nil {
		t.StartDate = func() time.Time {
			if s.StartDate == nil {
				return *new(time.Time)
			}
			return *s.StartDate
		}()
	}
	if s.EndDate != nil {
		t.EndDate = func() time.Time {
			if s.EndDate == nil {
				return *new(time.Time)
			}
			return *s.EndDate
		}()
	}
	if s.Amount != nil {
		t.Amount = func() int64 {
			if s.Amount == nil {
				return *new(int64)
			}
			return *s.Amount
		}()
	}
	if s.LatestStatusID != nil {
		t.LatestStatusID = func() sql.Null[types.Uint64] {
			if s.LatestStatusID == nil {
				return *new(sql.Null[types.Uint64])
			}
			v := s.LatestStatusID
			return *v
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *ServiceChargeSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ServiceCharges.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.AccountID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.AccountID == nil {
					return *new(types.Uint64)
				}
				return *s.AccountID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.StartDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.StartDate == nil {
					return *new(time.Time)
				}
				return *s.StartDate
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.EndDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.EndDate == nil {
					return *new(time.Time)
				}
				return *s.EndDate
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Amount != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() int64 {
				if s.Amount == nil {
					return *new(int64)
				}
				return *s.Amount
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.LatestStatusID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[types.Uint64] {
				if s.LatestStatusID == nil {
					return *new(sql.Null[types.Uint64])
				}
				v := s.LatestStatusID
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ServiceChargeSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("service_charges")...)
}

func (s ServiceChargeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.AccountID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "account_id")...),
			mysql.Arg(s.AccountID),
		}})
	}

	if s.StartDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "start_date")...),
			mysql.Arg(s.StartDate),
		}})
	}

	if s.EndDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "end_date")...),
			mysql.Arg(s.EndDate),
		}})
	}

	if s.Amount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "amount")...),
			mysql.Arg(s.Amount),
		}})
	}

	if s.LatestStatusID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "latest_status_id")...),
			mysql.Arg(s.LatestStatusID),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindServiceCharge retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindServiceCharge(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*ServiceCharge, error) {
	if len(cols) == 0 {
		return ServiceCharges.Query(
			sm.Where(ServiceCharges.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ServiceCharges.Query(
		sm.Where(ServiceCharges.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(ServiceCharges.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ServiceChargeExists checks the presence of a single record by primary key
func ServiceChargeExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return ServiceCharges.Query(
		sm.Where(ServiceCharges.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ServiceCharge is retrieved from the database
func (o *ServiceCharge) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ServiceCharges.AfterSelectHooks.RunHooks(ctx, exec, ServiceChargeSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ServiceCharges.AfterInsertHooks.RunHooks(ctx, exec, ServiceChargeSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ServiceCharges.AfterUpdateHooks.RunHooks(ctx, exec, ServiceChargeSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ServiceCharges.AfterDeleteHooks.RunHooks(ctx, exec, ServiceChargeSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ServiceCharge
func (o *ServiceCharge) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *ServiceCharge) pkEQ() dialect.Expression {
	return mysql.Quote("service_charges", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ServiceCharge
func (o *ServiceCharge) Update(ctx context.Context, exec bob.Executor, s *ServiceChargeSetter) error {
	_, err := ServiceCharges.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single ServiceCharge record with an executor
func (o *ServiceCharge) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ServiceCharges.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ServiceCharge using the executor
func (o *ServiceCharge) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ServiceCharges.Query(
		sm.Where(ServiceCharges.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ServiceChargeSlice is retrieved from the database
func (o ServiceChargeSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ServiceCharges.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ServiceCharges.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ServiceCharges.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ServiceCharges.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ServiceChargeSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("service_charges", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ServiceChargeSlice) copyMatchingRows(from ...*ServiceCharge) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ServiceChargeSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ServiceCharges.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ServiceCharge:
				o.copyMatchingRows(retrieved)
			case []*ServiceCharge:
				o.copyMatchingRows(retrieved...)
			case ServiceChargeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ServiceCharge or a slice of ServiceCharge
				// then run the AfterUpdateHooks on the slice
				_, err = ServiceCharges.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ServiceChargeSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ServiceCharges.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ServiceCharge:
				o.copyMatchingRows(retrieved)
			case []*ServiceCharge:
				o.copyMatchingRows(retrieved...)
			case ServiceChargeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ServiceCharge or a slice of ServiceCharge
				// then run the AfterDeleteHooks on the slice
				_, err = ServiceCharges.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ServiceChargeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ServiceChargeSetter) error {
	_, err := ServiceCharges.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ServiceChargeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ServiceCharges.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ServiceChargeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ServiceCharges.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ServiceChargeItems starts a query for related objects on service_charge_items
func (o *ServiceCharge) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	return ServiceChargeItems.Query(append(mods,
		sm.Where(ServiceChargeItems.Columns.ServiceChargeID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os ServiceChargeSlice) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceChargeItems.Query(append(mods,
		sm.Where(mysql.Group(ServiceChargeItems.Columns.ServiceChargeID).OP("IN", PKArgExpr)),
	)...)
}

// ServiceChargeStatuses starts a query for related objects on service_charge_statuses
func (o *ServiceCharge) ServiceChargeStatuses(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeStatusesQuery {
	return ServiceChargeStatuses.Query(append(mods,
		sm.Where(ServiceChargeStatuses.Columns.ServiceChargeID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os ServiceChargeSlice) ServiceChargeStatuses(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeStatusesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceChargeStatuses.Query(append(mods,
		sm.Where(mysql.Group(ServiceChargeStatuses.Columns.ServiceChargeID).OP("IN", PKArgExpr)),
	)...)
}

// Account starts a query for related objects on accounts
func (o *ServiceCharge) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(o.AccountID))),
	)...)
}

func (os ServiceChargeSlice) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.AccountID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Accounts.Query(append(mods,
		sm.Where(mysql.Group(Accounts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// LatestStatusServiceChargeStatus starts a query for related objects on service_charge_statuses
func (o *ServiceCharge) LatestStatusServiceChargeStatus(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeStatusesQuery {
	return ServiceChargeStatuses.Query(append(mods,
		sm.Where(ServiceChargeStatuses.Columns.ID.EQ(mysql.Arg(o.LatestStatusID))),
	)...)
}

func (os ServiceChargeSlice) LatestStatusServiceChargeStatus(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeStatusesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.LatestStatusID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceChargeStatuses.Query(append(mods,
		sm.Where(mysql.Group(ServiceChargeStatuses.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertServiceChargeServiceChargeItems0(ctx context.Context, exec bob.Executor, serviceChargeItems1 []*ServiceChargeItemSetter, serviceCharge0 *ServiceCharge) (ServiceChargeItemSlice, error) {
	for i := range serviceChargeItems1 {
		serviceChargeItems1[i].ServiceChargeID = func() *types.Uint64 { return &serviceCharge0.ID }()
	}

	ret, err := ServiceChargeItems.Insert(bob.ToMods(serviceChargeItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertServiceChargeServiceChargeItems0: %w", err)
	}

	return ret, nil
}

func attachServiceChargeServiceChargeItems0(ctx context.Context, exec bob.Executor, count int, serviceChargeItems1 ServiceChargeItemSlice, serviceCharge0 *ServiceCharge) (ServiceChargeItemSlice, error) {
	setter := &ServiceChargeItemSetter{
		ServiceChargeID: func() *types.Uint64 { return &serviceCharge0.ID }(),
	}

	err := serviceChargeItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeServiceChargeItems0: %w", err)
	}

	return serviceChargeItems1, nil
}

func (serviceCharge0 *ServiceCharge) InsertServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serviceChargeItems1, err := insertServiceChargeServiceChargeItems0(ctx, exec, related, serviceCharge0)
	if err != nil {
		return err
	}

	serviceCharge0.R.ServiceChargeItems = append(serviceCharge0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range serviceChargeItems1 {
		rel.R.ServiceCharge = serviceCharge0
	}
	return nil
}

func (serviceCharge0 *ServiceCharge) AttachServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serviceChargeItems1 := ServiceChargeItemSlice(related)

	_, err = attachServiceChargeServiceChargeItems0(ctx, exec, len(related), serviceChargeItems1, serviceCharge0)
	if err != nil {
		return err
	}

	serviceCharge0.R.ServiceChargeItems = append(serviceCharge0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range related {
		rel.R.ServiceCharge = serviceCharge0
	}

	return nil
}

func insertServiceChargeServiceChargeStatuses0(ctx context.Context, exec bob.Executor, serviceChargeStatuses1 []*ServiceChargeStatusSetter, serviceCharge0 *ServiceCharge) (ServiceChargeStatusSlice, error) {
	for i := range serviceChargeStatuses1 {
		serviceChargeStatuses1[i].ServiceChargeID = func() *types.Uint64 { return &serviceCharge0.ID }()
	}

	ret, err := ServiceChargeStatuses.Insert(bob.ToMods(serviceChargeStatuses1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertServiceChargeServiceChargeStatuses0: %w", err)
	}

	return ret, nil
}

func attachServiceChargeServiceChargeStatuses0(ctx context.Context, exec bob.Executor, count int, serviceChargeStatuses1 ServiceChargeStatusSlice, serviceCharge0 *ServiceCharge) (ServiceChargeStatusSlice, error) {
	setter := &ServiceChargeStatusSetter{
		ServiceChargeID: func() *types.Uint64 { return &serviceCharge0.ID }(),
	}

	err := serviceChargeStatuses1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeServiceChargeStatuses0: %w", err)
	}

	return serviceChargeStatuses1, nil
}

func (serviceCharge0 *ServiceCharge) InsertServiceChargeStatuses(ctx context.Context, exec bob.Executor, related ...*ServiceChargeStatusSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serviceChargeStatuses1, err := insertServiceChargeServiceChargeStatuses0(ctx, exec, related, serviceCharge0)
	if err != nil {
		return err
	}

	serviceCharge0.R.ServiceChargeStatuses = append(serviceCharge0.R.ServiceChargeStatuses, serviceChargeStatuses1...)

	for _, rel := range serviceChargeStatuses1 {
		rel.R.ServiceCharge = serviceCharge0
	}
	return nil
}

func (serviceCharge0 *ServiceCharge) AttachServiceChargeStatuses(ctx context.Context, exec bob.Executor, related ...*ServiceChargeStatus) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serviceChargeStatuses1 := ServiceChargeStatusSlice(related)

	_, err = attachServiceChargeServiceChargeStatuses0(ctx, exec, len(related), serviceChargeStatuses1, serviceCharge0)
	if err != nil {
		return err
	}

	serviceCharge0.R.ServiceChargeStatuses = append(serviceCharge0.R.ServiceChargeStatuses, serviceChargeStatuses1...)

	for _, rel := range related {
		rel.R.ServiceCharge = serviceCharge0
	}

	return nil
}

func attachServiceChargeAccount0(ctx context.Context, exec bob.Executor, count int, serviceCharge0 *ServiceCharge, account1 *Account) (*ServiceCharge, error) {
	setter := &ServiceChargeSetter{
		AccountID: func() *types.Uint64 { return &account1.ID }(),
	}

	err := serviceCharge0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeAccount0: %w", err)
	}

	return serviceCharge0, nil
}

func (serviceCharge0 *ServiceCharge) InsertAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServiceChargeAccount0(ctx, exec, 1, serviceCharge0, account1)
	if err != nil {
		return err
	}

	serviceCharge0.R.Account = account1

	account1.R.ServiceCharges = append(account1.R.ServiceCharges, serviceCharge0)

	return nil
}

func (serviceCharge0 *ServiceCharge) AttachAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachServiceChargeAccount0(ctx, exec, 1, serviceCharge0, account1)
	if err != nil {
		return err
	}

	serviceCharge0.R.Account = account1

	account1.R.ServiceCharges = append(account1.R.ServiceCharges, serviceCharge0)

	return nil
}

func attachServiceChargeLatestStatusServiceChargeStatus0(ctx context.Context, exec bob.Executor, count int, serviceCharge0 *ServiceCharge, serviceChargeStatus1 *ServiceChargeStatus) (*ServiceCharge, error) {
	setter := &ServiceChargeSetter{
		LatestStatusID: func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: serviceChargeStatus1.ID, Valid: true}
			return &v
		}(),
	}

	err := serviceCharge0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServiceChargeLatestStatusServiceChargeStatus0: %w", err)
	}

	return serviceCharge0, nil
}

func (serviceCharge0 *ServiceCharge) InsertLatestStatusServiceChargeStatus(ctx context.Context, exec bob.Executor, related *ServiceChargeStatusSetter) error {
	var err error

	serviceChargeStatus1, err := ServiceChargeStatuses.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServiceChargeLatestStatusServiceChargeStatus0(ctx, exec, 1, serviceCharge0, serviceChargeStatus1)
	if err != nil {
		return err
	}

	serviceCharge0.R.LatestStatusServiceChargeStatus = serviceChargeStatus1

	serviceChargeStatus1.R.LatestStatusServiceCharges = append(serviceChargeStatus1.R.LatestStatusServiceCharges, serviceCharge0)

	return nil
}

func (serviceCharge0 *ServiceCharge) AttachLatestStatusServiceChargeStatus(ctx context.Context, exec bob.Executor, serviceChargeStatus1 *ServiceChargeStatus) error {
	var err error

	_, err = attachServiceChargeLatestStatusServiceChargeStatus0(ctx, exec, 1, serviceCharge0, serviceChargeStatus1)
	if err != nil {
		return err
	}

	serviceCharge0.R.LatestStatusServiceChargeStatus = serviceChargeStatus1

	serviceChargeStatus1.R.LatestStatusServiceCharges = append(serviceChargeStatus1.R.LatestStatusServiceCharges, serviceCharge0)

	return nil
}
