// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// Subscription is an object representing the database table.
type Subscription struct {
	ID              types.Uint64        `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID       types.Uint64        `db:"account_id" json:"account_id" db:"account_id"`
	CatalogID       types.Uint64        `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	StartDate       time.Time           `db:"start_date" json:"start_date" db:"start_date"`
	EndDate         sql.Null[time.Time] `db:"end_date" json:"end_date" db:"end_date"`
	IdempotencyKey  string              `db:"idempotency_key" json:"idempotency_key" db:"idempotency_key"`
	NextBillingDate time.Time           `db:"next_billing_date" json:"next_billing_date" db:"next_billing_date"`
	CreatedAt       time.Time           `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt       time.Time           `db:"updated_at" json:"updated_at" db:"updated_at"`

	R subscriptionR `db:"-" json:"-" db:"-"`
}

// SubscriptionSlice is an alias for a slice of pointers to Subscription.
// This should almost always be used instead of []*Subscription.
type SubscriptionSlice []*Subscription

// Subscriptions contains methods to work with the subscriptions table
var Subscriptions = mysql.NewTablex[*Subscription, SubscriptionSlice, *SubscriptionSetter]("subscriptions", buildSubscriptionColumns("subscriptions"), []string{"id"}, []string{"idempotency_key"})

// SubscriptionsQuery is a query on the subscriptions table
type SubscriptionsQuery = *mysql.ViewQuery[*Subscription, SubscriptionSlice]

// subscriptionR is where relationships are stored.
type subscriptionR struct {
	ServiceChargeItems ServiceChargeItemSlice `json:"ServiceChargeItems" db:"ServiceChargeItems"` // fk_service_charge_items_subscription
	Account            *Account               `json:"Account" db:"Account"`                       // fk_subscriptions_account
	Catalog            *Catalog               `json:"Catalog" db:"Catalog"`                       // fk_subscriptions_catalog
}

func buildSubscriptionColumns(alias string) subscriptionColumns {
	return subscriptionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "account_id", "catalog_id", "start_date", "end_date", "idempotency_key", "next_billing_date", "created_at", "updated_at",
		).WithParent("subscriptions"),
		tableAlias:      alias,
		ID:              mysql.Quote(alias, "id"),
		AccountID:       mysql.Quote(alias, "account_id"),
		CatalogID:       mysql.Quote(alias, "catalog_id"),
		StartDate:       mysql.Quote(alias, "start_date"),
		EndDate:         mysql.Quote(alias, "end_date"),
		IdempotencyKey:  mysql.Quote(alias, "idempotency_key"),
		NextBillingDate: mysql.Quote(alias, "next_billing_date"),
		CreatedAt:       mysql.Quote(alias, "created_at"),
		UpdatedAt:       mysql.Quote(alias, "updated_at"),
	}
}

type subscriptionColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              mysql.Expression
	AccountID       mysql.Expression
	CatalogID       mysql.Expression
	StartDate       mysql.Expression
	EndDate         mysql.Expression
	IdempotencyKey  mysql.Expression
	NextBillingDate mysql.Expression
	CreatedAt       mysql.Expression
	UpdatedAt       mysql.Expression
}

func (c subscriptionColumns) Alias() string {
	return c.tableAlias
}

func (subscriptionColumns) AliasedAs(alias string) subscriptionColumns {
	return buildSubscriptionColumns(alias)
}

// SubscriptionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SubscriptionSetter struct {
	ID              *types.Uint64        `db:"id,pk,autoincr" json:"id" db:"id"`
	AccountID       *types.Uint64        `db:"account_id" json:"account_id" db:"account_id"`
	CatalogID       *types.Uint64        `db:"catalog_id" json:"catalog_id" db:"catalog_id"`
	StartDate       *time.Time           `db:"start_date" json:"start_date" db:"start_date"`
	EndDate         *sql.Null[time.Time] `db:"end_date" json:"end_date" db:"end_date"`
	IdempotencyKey  *string              `db:"idempotency_key" json:"idempotency_key" db:"idempotency_key"`
	NextBillingDate *time.Time           `db:"next_billing_date" json:"next_billing_date" db:"next_billing_date"`
	CreatedAt       *time.Time           `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt       *time.Time           `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s SubscriptionSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.AccountID != nil {
		vals = append(vals, "account_id")
	}
	if s.CatalogID != nil {
		vals = append(vals, "catalog_id")
	}
	if s.StartDate != nil {
		vals = append(vals, "start_date")
	}
	if s.EndDate != nil {
		vals = append(vals, "end_date")
	}
	if s.IdempotencyKey != nil {
		vals = append(vals, "idempotency_key")
	}
	if s.NextBillingDate != nil {
		vals = append(vals, "next_billing_date")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s SubscriptionSetter) Overwrite(t *Subscription) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.AccountID != nil {
		t.AccountID = func() types.Uint64 {
			if s.AccountID == nil {
				return *new(types.Uint64)
			}
			return *s.AccountID
		}()
	}
	if s.CatalogID != nil {
		t.CatalogID = func() types.Uint64 {
			if s.CatalogID == nil {
				return *new(types.Uint64)
			}
			return *s.CatalogID
		}()
	}
	if s.StartDate != nil {
		t.StartDate = func() time.Time {
			if s.StartDate == nil {
				return *new(time.Time)
			}
			return *s.StartDate
		}()
	}
	if s.EndDate != nil {
		t.EndDate = func() sql.Null[time.Time] {
			if s.EndDate == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.EndDate
			return *v
		}()
	}
	if s.IdempotencyKey != nil {
		t.IdempotencyKey = func() string {
			if s.IdempotencyKey == nil {
				return *new(string)
			}
			return *s.IdempotencyKey
		}()
	}
	if s.NextBillingDate != nil {
		t.NextBillingDate = func() time.Time {
			if s.NextBillingDate == nil {
				return *new(time.Time)
			}
			return *s.NextBillingDate
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *SubscriptionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Subscriptions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.AccountID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.AccountID == nil {
					return *new(types.Uint64)
				}
				return *s.AccountID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CatalogID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.CatalogID == nil {
					return *new(types.Uint64)
				}
				return *s.CatalogID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.StartDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.StartDate == nil {
					return *new(time.Time)
				}
				return *s.StartDate
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.EndDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() sql.Null[time.Time] {
				if s.EndDate == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.EndDate
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.IdempotencyKey != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.IdempotencyKey == nil {
					return *new(string)
				}
				return *s.IdempotencyKey
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.NextBillingDate != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.NextBillingDate == nil {
					return *new(time.Time)
				}
				return *s.NextBillingDate
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s SubscriptionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("subscriptions")...)
}

func (s SubscriptionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.AccountID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "account_id")...),
			mysql.Arg(s.AccountID),
		}})
	}

	if s.CatalogID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "catalog_id")...),
			mysql.Arg(s.CatalogID),
		}})
	}

	if s.StartDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "start_date")...),
			mysql.Arg(s.StartDate),
		}})
	}

	if s.EndDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "end_date")...),
			mysql.Arg(s.EndDate),
		}})
	}

	if s.IdempotencyKey != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "idempotency_key")...),
			mysql.Arg(s.IdempotencyKey),
		}})
	}

	if s.NextBillingDate != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "next_billing_date")...),
			mysql.Arg(s.NextBillingDate),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindSubscription retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSubscription(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*Subscription, error) {
	if len(cols) == 0 {
		return Subscriptions.Query(
			sm.Where(Subscriptions.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Subscriptions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SubscriptionExists checks the presence of a single record by primary key
func SubscriptionExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Subscription is retrieved from the database
func (o *Subscription) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Subscription
func (o *Subscription) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Subscription) pkEQ() dialect.Expression {
	return mysql.Quote("subscriptions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Subscription
func (o *Subscription) Update(ctx context.Context, exec bob.Executor, s *SubscriptionSetter) error {
	_, err := Subscriptions.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Subscription record with an executor
func (o *Subscription) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Subscriptions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Subscription using the executor
func (o *Subscription) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SubscriptionSlice is retrieved from the database
func (o SubscriptionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SubscriptionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("subscriptions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SubscriptionSlice) copyMatchingRows(from ...*Subscription) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterUpdateHooks on the slice
				_, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterDeleteHooks on the slice
				_, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SubscriptionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SubscriptionSetter) error {
	_, err := Subscriptions.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o SubscriptionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SubscriptionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Subscriptions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ServiceChargeItems starts a query for related objects on service_charge_items
func (o *Subscription) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	return ServiceChargeItems.Query(append(mods,
		sm.Where(ServiceChargeItems.Columns.SubscriptionID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os SubscriptionSlice) ServiceChargeItems(mods ...bob.Mod[*dialect.SelectQuery]) ServiceChargeItemsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ServiceChargeItems.Query(append(mods,
		sm.Where(mysql.Group(ServiceChargeItems.Columns.SubscriptionID).OP("IN", PKArgExpr)),
	)...)
}

// Account starts a query for related objects on accounts
func (o *Subscription) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.ID.EQ(mysql.Arg(o.AccountID))),
	)...)
}

func (os SubscriptionSlice) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.AccountID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Accounts.Query(append(mods,
		sm.Where(mysql.Group(Accounts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Catalog starts a query for related objects on catalogs
func (o *Subscription) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	return Catalogs.Query(append(mods,
		sm.Where(Catalogs.Columns.ID.EQ(mysql.Arg(o.CatalogID))),
	)...)
}

func (os SubscriptionSlice) Catalog(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.CatalogID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Catalogs.Query(append(mods,
		sm.Where(mysql.Group(Catalogs.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertSubscriptionServiceChargeItems0(ctx context.Context, exec bob.Executor, serviceChargeItems1 []*ServiceChargeItemSetter, subscription0 *Subscription) (ServiceChargeItemSlice, error) {
	for i := range serviceChargeItems1 {
		serviceChargeItems1[i].SubscriptionID = func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: subscription0.ID, Valid: true}
			return &v
		}()
	}

	ret, err := ServiceChargeItems.Insert(bob.ToMods(serviceChargeItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertSubscriptionServiceChargeItems0: %w", err)
	}

	return ret, nil
}

func attachSubscriptionServiceChargeItems0(ctx context.Context, exec bob.Executor, count int, serviceChargeItems1 ServiceChargeItemSlice, subscription0 *Subscription) (ServiceChargeItemSlice, error) {
	setter := &ServiceChargeItemSetter{
		SubscriptionID: func() *sql.Null[types.Uint64] {
			v := sql.Null[types.Uint64]{V: subscription0.ID, Valid: true}
			return &v
		}(),
	}

	err := serviceChargeItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachSubscriptionServiceChargeItems0: %w", err)
	}

	return serviceChargeItems1, nil
}

func (subscription0 *Subscription) InsertServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serviceChargeItems1, err := insertSubscriptionServiceChargeItems0(ctx, exec, related, subscription0)
	if err != nil {
		return err
	}

	subscription0.R.ServiceChargeItems = append(subscription0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range serviceChargeItems1 {
		rel.R.Subscription = subscription0
	}
	return nil
}

func (subscription0 *Subscription) AttachServiceChargeItems(ctx context.Context, exec bob.Executor, related ...*ServiceChargeItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serviceChargeItems1 := ServiceChargeItemSlice(related)

	_, err = attachSubscriptionServiceChargeItems0(ctx, exec, len(related), serviceChargeItems1, subscription0)
	if err != nil {
		return err
	}

	subscription0.R.ServiceChargeItems = append(subscription0.R.ServiceChargeItems, serviceChargeItems1...)

	for _, rel := range related {
		rel.R.Subscription = subscription0
	}

	return nil
}

func attachSubscriptionAccount0(ctx context.Context, exec bob.Executor, count int, subscription0 *Subscription, account1 *Account) (*Subscription, error) {
	setter := &SubscriptionSetter{
		AccountID: func() *types.Uint64 { return &account1.ID }(),
	}

	err := subscription0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSubscriptionAccount0: %w", err)
	}

	return subscription0, nil
}

func (subscription0 *Subscription) InsertAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSubscriptionAccount0(ctx, exec, 1, subscription0, account1)
	if err != nil {
		return err
	}

	subscription0.R.Account = account1

	account1.R.Subscriptions = append(account1.R.Subscriptions, subscription0)

	return nil
}

func (subscription0 *Subscription) AttachAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachSubscriptionAccount0(ctx, exec, 1, subscription0, account1)
	if err != nil {
		return err
	}

	subscription0.R.Account = account1

	account1.R.Subscriptions = append(account1.R.Subscriptions, subscription0)

	return nil
}

func attachSubscriptionCatalog0(ctx context.Context, exec bob.Executor, count int, subscription0 *Subscription, catalog1 *Catalog) (*Subscription, error) {
	setter := &SubscriptionSetter{
		CatalogID: func() *types.Uint64 { return &catalog1.ID }(),
	}

	err := subscription0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSubscriptionCatalog0: %w", err)
	}

	return subscription0, nil
}

func (subscription0 *Subscription) InsertCatalog(ctx context.Context, exec bob.Executor, related *CatalogSetter) error {
	var err error

	catalog1, err := Catalogs.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSubscriptionCatalog0(ctx, exec, 1, subscription0, catalog1)
	if err != nil {
		return err
	}

	subscription0.R.Catalog = catalog1

	catalog1.R.Subscriptions = append(catalog1.R.Subscriptions, subscription0)

	return nil
}

func (subscription0 *Subscription) AttachCatalog(ctx context.Context, exec bob.Executor, catalog1 *Catalog) error {
	var err error

	_, err = attachSubscriptionCatalog0(ctx, exec, 1, subscription0, catalog1)
	if err != nil {
		return err
	}

	subscription0.R.Catalog = catalog1

	catalog1.R.Subscriptions = append(catalog1.R.Subscriptions, subscription0)

	return nil
}
