// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// Tenant is an object representing the database table.
type Tenant struct {
	ID        types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	Name      string       `db:"name" json:"name" db:"name"`
	CreatedAt time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`

	R tenantR `db:"-" json:"-" db:"-"`
}

// TenantSlice is an alias for a slice of pointers to Tenant.
// This should almost always be used instead of []*Tenant.
type TenantSlice []*Tenant

// Tenants contains methods to work with the tenants table
var Tenants = mysql.NewTablex[*Tenant, TenantSlice, *TenantSetter]("tenants", buildTenantColumns("tenants"), []string{"id"})

// TenantsQuery is a query on the tenants table
type TenantsQuery = *mysql.ViewQuery[*Tenant, TenantSlice]

// tenantR is where relationships are stored.
type tenantR struct {
	Accounts AccountSlice `json:"Accounts" db:"Accounts"` // fk_accounts_tenant
	Catalogs CatalogSlice `json:"Catalogs" db:"Catalogs"` // fk_catalogs_tenant
}

func buildTenantColumns(alias string) tenantColumns {
	return tenantColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "created_at", "updated_at",
		).WithParent("tenants"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type tenantColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c tenantColumns) Alias() string {
	return c.tableAlias
}

func (tenantColumns) AliasedAs(alias string) tenantColumns {
	return buildTenantColumns(alias)
}

// TenantSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TenantSetter struct {
	ID        *types.Uint64 `db:"id,pk,autoincr" json:"id" db:"id"`
	Name      *string       `db:"name" json:"name" db:"name"`
	CreatedAt *time.Time    `db:"created_at" json:"created_at" db:"created_at"`
	UpdatedAt *time.Time    `db:"updated_at" json:"updated_at" db:"updated_at"`
}

func (s TenantSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TenantSetter) Overwrite(t *Tenant) {
	if s.ID != nil {
		t.ID = func() types.Uint64 {
			if s.ID == nil {
				return *new(types.Uint64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *TenantSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tenants.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() types.Uint64 {
				if s.ID == nil {
					return *new(types.Uint64)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt != nil) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TenantSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("tenants")...)
}

func (s TenantSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTenant retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTenant(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*Tenant, error) {
	if len(cols) == 0 {
		return Tenants.Query(
			sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Tenants.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TenantExists checks the presence of a single record by primary key
func TenantExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Tenant is retrieved from the database
func (o *Tenant) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tenants.AfterSelectHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tenants.AfterInsertHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, TenantSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Tenant
func (o *Tenant) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Tenant) pkEQ() dialect.Expression {
	return mysql.Quote("tenants", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Tenant
func (o *Tenant) Update(ctx context.Context, exec bob.Executor, s *TenantSetter) error {
	_, err := Tenants.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Tenant record with an executor
func (o *Tenant) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tenants.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Tenant using the executor
func (o *Tenant) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TenantSlice is retrieved from the database
func (o TenantSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tenants.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tenants.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TenantSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("tenants", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TenantSlice) copyMatchingRows(from ...*Tenant) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TenantSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tenants.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tenant:
				o.copyMatchingRows(retrieved)
			case []*Tenant:
				o.copyMatchingRows(retrieved...)
			case TenantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tenant or a slice of Tenant
				// then run the AfterUpdateHooks on the slice
				_, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TenantSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tenants.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tenant:
				o.copyMatchingRows(retrieved)
			case []*Tenant:
				o.copyMatchingRows(retrieved...)
			case TenantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tenant or a slice of Tenant
				// then run the AfterDeleteHooks on the slice
				_, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TenantSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TenantSetter) error {
	_, err := Tenants.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o TenantSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tenants.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TenantSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tenants.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Accounts starts a query for related objects on accounts
func (o *Tenant) Accounts(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.TenantID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os TenantSlice) Accounts(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Accounts.Query(append(mods,
		sm.Where(mysql.Group(Accounts.Columns.TenantID).OP("IN", PKArgExpr)),
	)...)
}

// Catalogs starts a query for related objects on catalogs
func (o *Tenant) Catalogs(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	return Catalogs.Query(append(mods,
		sm.Where(Catalogs.Columns.TenantID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os TenantSlice) Catalogs(mods ...bob.Mod[*dialect.SelectQuery]) CatalogsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Catalogs.Query(append(mods,
		sm.Where(mysql.Group(Catalogs.Columns.TenantID).OP("IN", PKArgExpr)),
	)...)
}

func insertTenantAccounts0(ctx context.Context, exec bob.Executor, accounts1 []*AccountSetter, tenant0 *Tenant) (AccountSlice, error) {
	for i := range accounts1 {
		accounts1[i].TenantID = func() *types.Uint64 { return &tenant0.ID }()
	}

	ret, err := Accounts.Insert(bob.ToMods(accounts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTenantAccounts0: %w", err)
	}

	return ret, nil
}

func attachTenantAccounts0(ctx context.Context, exec bob.Executor, count int, accounts1 AccountSlice, tenant0 *Tenant) (AccountSlice, error) {
	setter := &AccountSetter{
		TenantID: func() *types.Uint64 { return &tenant0.ID }(),
	}

	err := accounts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTenantAccounts0: %w", err)
	}

	return accounts1, nil
}

func (tenant0 *Tenant) InsertAccounts(ctx context.Context, exec bob.Executor, related ...*AccountSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	accounts1, err := insertTenantAccounts0(ctx, exec, related, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Accounts = append(tenant0.R.Accounts, accounts1...)

	for _, rel := range accounts1 {
		rel.R.Tenant = tenant0
	}
	return nil
}

func (tenant0 *Tenant) AttachAccounts(ctx context.Context, exec bob.Executor, related ...*Account) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	accounts1 := AccountSlice(related)

	_, err = attachTenantAccounts0(ctx, exec, len(related), accounts1, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Accounts = append(tenant0.R.Accounts, accounts1...)

	for _, rel := range related {
		rel.R.Tenant = tenant0
	}

	return nil
}

func insertTenantCatalogs0(ctx context.Context, exec bob.Executor, catalogs1 []*CatalogSetter, tenant0 *Tenant) (CatalogSlice, error) {
	for i := range catalogs1 {
		catalogs1[i].TenantID = func() *types.Uint64 { return &tenant0.ID }()
	}

	ret, err := Catalogs.Insert(bob.ToMods(catalogs1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTenantCatalogs0: %w", err)
	}

	return ret, nil
}

func attachTenantCatalogs0(ctx context.Context, exec bob.Executor, count int, catalogs1 CatalogSlice, tenant0 *Tenant) (CatalogSlice, error) {
	setter := &CatalogSetter{
		TenantID: func() *types.Uint64 { return &tenant0.ID }(),
	}

	err := catalogs1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTenantCatalogs0: %w", err)
	}

	return catalogs1, nil
}

func (tenant0 *Tenant) InsertCatalogs(ctx context.Context, exec bob.Executor, related ...*CatalogSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	catalogs1, err := insertTenantCatalogs0(ctx, exec, related, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Catalogs = append(tenant0.R.Catalogs, catalogs1...)

	for _, rel := range catalogs1 {
		rel.R.Tenant = tenant0
	}
	return nil
}

func (tenant0 *Tenant) AttachCatalogs(ctx context.Context, exec bob.Executor, related ...*Catalog) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	catalogs1 := CatalogSlice(related)

	_, err = attachTenantCatalogs0(ctx, exec, len(related), catalogs1, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Catalogs = append(tenant0.R.Catalogs, catalogs1...)

	for _, rel := range related {
		rel.R.Tenant = tenant0
	}

	return nil
}
