// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flora/pkg/pb/subscription/v1 (interfaces: SubscriptionServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/subscription/v1/subscription_service_mock.go -package=mock_subscriptionv1 github.com/flora/pkg/pb/subscription/v1 SubscriptionServiceServer
//

// Package mock_subscriptionv1 is a generated GoMock package.
package mock_subscriptionv1

import (
	context "context"
	reflect "reflect"

	subscriptionv1 "github.com/flora/pkg/pb/subscription/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionServiceServer is a mock of SubscriptionServiceServer interface.
type MockSubscriptionServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceServerMockRecorder
	isgomock struct{}
}

// MockSubscriptionServiceServerMockRecorder is the mock recorder for MockSubscriptionServiceServer.
type MockSubscriptionServiceServerMockRecorder struct {
	mock *MockSubscriptionServiceServer
}

// NewMockSubscriptionServiceServer creates a new mock instance.
func NewMockSubscriptionServiceServer(ctrl *gomock.Controller) *MockSubscriptionServiceServer {
	mock := &MockSubscriptionServiceServer{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionServiceServer) EXPECT() *MockSubscriptionServiceServerMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionServiceServer) CreateSubscription(arg0 context.Context, arg1 *subscriptionv1.CreateSubscriptionRequest) (*subscriptionv1.CreateSubscriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", arg0, arg1)
	ret0, _ := ret[0].(*subscriptionv1.CreateSubscriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionServiceServerMockRecorder) CreateSubscription(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionServiceServer)(nil).CreateSubscription), arg0, arg1)
}

// mustEmbedUnimplementedSubscriptionServiceServer mocks base method.
func (m *MockSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSubscriptionServiceServer")
}

// mustEmbedUnimplementedSubscriptionServiceServer indicates an expected call of mustEmbedUnimplementedSubscriptionServiceServer.
func (mr *MockSubscriptionServiceServerMockRecorder) mustEmbedUnimplementedSubscriptionServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSubscriptionServiceServer", reflect.TypeOf((*MockSubscriptionServiceServer)(nil).mustEmbedUnimplementedSubscriptionServiceServer))
}
