// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	factory "github.com/flora/api/internal/bob/factory"
	models "github.com/flora/api/internal/bob/models"
	"github.com/stephenafamo/bob"
)

func TestAccountUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.Account) factory.AccountModSlice
	}{
		{
			name:        "ErrUniquePrimary",
			expectedErr: AccountErrors.ErrUniquePrimary,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Account) factory.AccountModSlice {
				shouldUpdate := false
				updateMods := make(factory.AccountModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewAccountWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.AccountModSlice{
					factory.AccountMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueUqAccountsExternalTenant",
			expectedErr: AccountErrors.ErrUniqueUqAccountsExternalTenant,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Account) factory.AccountModSlice {
				shouldUpdate := false
				updateMods := make(factory.AccountModSlice, 0, 2)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewAccountWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.AccountModSlice{
					factory.AccountMods.ExternalAccountID(obj.ExternalAccountID),
					factory.AccountMods.TenantID(obj.TenantID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewAccountWithContext(ctx, factory.AccountMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewAccountWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewAccountWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
