// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CatalogPriceErrors = &catalogPriceErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "catalog_prices",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type catalogPriceErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
