// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SchemaMigrationErrors = &schemaMigrationErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "schema_migrations",
		columns: []string{"version"},
		s:       "PRIMARY",
	},
}

type schemaMigrationErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
