// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ServiceChargeStatusErrors = &serviceChargeStatusErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "service_charge_statuses",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type serviceChargeStatusErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
