// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ServiceChargeErrors = &serviceChargeErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "service_charges",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type serviceChargeErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
