// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SubscriptionErrors = &subscriptionErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "subscriptions",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueIdempotencyKey: &UniqueConstraintError{
		schema:  "",
		table:   "subscriptions",
		columns: []string{"idempotency_key"},
		s:       "idempotency_key",
	},
}

type subscriptionErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueIdempotencyKey *UniqueConstraintError
}
