// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TenantErrors = &tenantErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "tenants",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type tenantErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
