// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Accounts = Table[
	accountColumns,
	accountIndexes,
	accountForeignKeys,
	accountUniques,
	accountChecks,
]{
	Schema: "",
	Name:   "accounts",
	Columns: accountColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		ExternalAccountID: column{
			Name:      "external_account_id",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TenantID: column{
			Name:      "tenant_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: accountIndexes{
		IdxAccountsTenantID: index{
			Type: "BTREE",
			Name: "idx_accounts_tenant_id",
			Columns: []indexColumn{
				{
					Name:         "tenant_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		UqAccountsExternalTenant: index{
			Type: "BTREE",
			Name: "uq_accounts_external_tenant",
			Columns: []indexColumn{
				{
					Name:         "external_account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "tenant_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: accountForeignKeys{
		FKAccountsTenant: foreignKey{
			constraint: constraint{
				Name:    "fk_accounts_tenant",
				Columns: []string{"tenant_id"},
				Comment: "",
			},
			ForeignTable:   "tenants",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: accountUniques{
		UqAccountsExternalTenant: constraint{
			Name:    "uq_accounts_external_tenant",
			Columns: []string{"external_account_id", "tenant_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type accountColumns struct {
	ID                column
	ExternalAccountID column
	TenantID          column
	CreatedAt         column
	UpdatedAt         column
}

func (c accountColumns) AsSlice() []column {
	return []column{
		c.ID, c.ExternalAccountID, c.TenantID, c.CreatedAt, c.UpdatedAt,
	}
}

type accountIndexes struct {
	IdxAccountsTenantID      index
	PRIMARY                  index
	UqAccountsExternalTenant index
}

func (i accountIndexes) AsSlice() []index {
	return []index{
		i.IdxAccountsTenantID, i.PRIMARY, i.UqAccountsExternalTenant,
	}
}

type accountForeignKeys struct {
	FKAccountsTenant foreignKey
}

func (f accountForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKAccountsTenant,
	}
}

type accountUniques struct {
	UqAccountsExternalTenant constraint
}

func (u accountUniques) AsSlice() []constraint {
	return []constraint{
		u.UqAccountsExternalTenant,
	}
}

type accountChecks struct{}

func (c accountChecks) AsSlice() []check {
	return []check{}
}
