// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Catalogs = Table[
	catalogColumns,
	catalogIndexes,
	catalogForeignKeys,
	catalogUniques,
	catalogChecks,
]{
	Schema: "",
	Name:   "catalogs",
	Columns: catalogColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TenantID: column{
			Name:      "tenant_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: catalogIndexes{
		IdxCatalogsTenantID: index{
			Type: "BTREE",
			Name: "idx_catalogs_tenant_id",
			Columns: []indexColumn{
				{
					Name:         "tenant_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: catalogForeignKeys{
		FKCatalogsTenant: foreignKey{
			constraint: constraint{
				Name:    "fk_catalogs_tenant",
				Columns: []string{"tenant_id"},
				Comment: "",
			},
			ForeignTable:   "tenants",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type catalogColumns struct {
	ID        column
	Name      column
	TenantID  column
	CreatedAt column
	UpdatedAt column
}

func (c catalogColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.TenantID, c.CreatedAt, c.UpdatedAt,
	}
}

type catalogIndexes struct {
	IdxCatalogsTenantID index
	PRIMARY             index
}

func (i catalogIndexes) AsSlice() []index {
	return []index{
		i.IdxCatalogsTenantID, i.PRIMARY,
	}
}

type catalogForeignKeys struct {
	FKCatalogsTenant foreignKey
}

func (f catalogForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKCatalogsTenant,
	}
}

type catalogUniques struct{}

func (u catalogUniques) AsSlice() []constraint {
	return []constraint{}
}

type catalogChecks struct{}

func (c catalogChecks) AsSlice() []check {
	return []check{}
}
