// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var OneShotUsages = Table[
	oneShotUsageColumns,
	oneShotUsageIndexes,
	oneShotUsageForeignKeys,
	oneShotUsageUniques,
	oneShotUsageChecks,
]{
	Schema: "",
	Name:   "one_shot_usages",
	Columns: oneShotUsageColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		AccountID: column{
			Name:      "account_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CatalogID: column{
			Name:      "catalog_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IdempotencyKey: column{
			Name:      "idempotency_key",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UsedAt: column{
			Name:      "used_at",
			DBType:    "timestamp",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: oneShotUsageIndexes{
		IdempotencyKey: index{
			Type: "BTREE",
			Name: "idempotency_key",
			Columns: []indexColumn{
				{
					Name:         "idempotency_key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		IdxOneShotUsagesAccountID: index{
			Type: "BTREE",
			Name: "idx_one_shot_usages_account_id",
			Columns: []indexColumn{
				{
					Name:         "account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxOneShotUsagesCatalogID: index{
			Type: "BTREE",
			Name: "idx_one_shot_usages_catalog_id",
			Columns: []indexColumn{
				{
					Name:         "catalog_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: oneShotUsageForeignKeys{
		FKOneShotUsagesAccount: foreignKey{
			constraint: constraint{
				Name:    "fk_one_shot_usages_account",
				Columns: []string{"account_id"},
				Comment: "",
			},
			ForeignTable:   "accounts",
			ForeignColumns: []string{"id"},
		},
		FKOneShotUsagesCatalog: foreignKey{
			constraint: constraint{
				Name:    "fk_one_shot_usages_catalog",
				Columns: []string{"catalog_id"},
				Comment: "",
			},
			ForeignTable:   "catalogs",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: oneShotUsageUniques{
		IdempotencyKey: constraint{
			Name:    "idempotency_key",
			Columns: []string{"idempotency_key"},
			Comment: "",
		},
	},

	Comment: "",
}

type oneShotUsageColumns struct {
	ID             column
	AccountID      column
	CatalogID      column
	IdempotencyKey column
	UsedAt         column
	CreatedAt      column
	UpdatedAt      column
}

func (c oneShotUsageColumns) AsSlice() []column {
	return []column{
		c.ID, c.AccountID, c.CatalogID, c.IdempotencyKey, c.UsedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type oneShotUsageIndexes struct {
	IdempotencyKey            index
	IdxOneShotUsagesAccountID index
	IdxOneShotUsagesCatalogID index
	PRIMARY                   index
}

func (i oneShotUsageIndexes) AsSlice() []index {
	return []index{
		i.IdempotencyKey, i.IdxOneShotUsagesAccountID, i.IdxOneShotUsagesCatalogID, i.PRIMARY,
	}
}

type oneShotUsageForeignKeys struct {
	FKOneShotUsagesAccount foreignKey
	FKOneShotUsagesCatalog foreignKey
}

func (f oneShotUsageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKOneShotUsagesAccount, f.FKOneShotUsagesCatalog,
	}
}

type oneShotUsageUniques struct {
	IdempotencyKey constraint
}

func (u oneShotUsageUniques) AsSlice() []constraint {
	return []constraint{
		u.IdempotencyKey,
	}
}

type oneShotUsageChecks struct{}

func (c oneShotUsageChecks) AsSlice() []check {
	return []check{}
}
