// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SchemaMigrations = Table[
	schemaMigrationColumns,
	schemaMigrationIndexes,
	schemaMigrationForeignKeys,
	schemaMigrationUniques,
	schemaMigrationChecks,
]{
	Schema: "",
	Name:   "schema_migrations",
	Columns: schemaMigrationColumns{
		Version: column{
			Name:      "version",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Dirty: column{
			Name:      "dirty",
			DBType:    "tinyint(1)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: schemaMigrationIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "version",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"version"},
		Comment: "",
	},

	Comment: "",
}

type schemaMigrationColumns struct {
	Version column
	Dirty   column
}

func (c schemaMigrationColumns) AsSlice() []column {
	return []column{
		c.Version, c.Dirty,
	}
}

type schemaMigrationIndexes struct {
	PRIMARY index
}

func (i schemaMigrationIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type schemaMigrationForeignKeys struct{}

func (f schemaMigrationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type schemaMigrationUniques struct{}

func (u schemaMigrationUniques) AsSlice() []constraint {
	return []constraint{}
}

type schemaMigrationChecks struct{}

func (c schemaMigrationChecks) AsSlice() []check {
	return []check{}
}
