// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ServiceChargeStatuses = Table[
	serviceChargeStatusColumns,
	serviceChargeStatusIndexes,
	serviceChargeStatusForeignKeys,
	serviceChargeStatusUniques,
	serviceChargeStatusChecks,
]{
	Schema: "",
	Name:   "service_charge_statuses",
	Columns: serviceChargeStatusColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "enum('RESERVED','COMPLETED','FAILED','CANCELLED')",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ServiceChargeID: column{
			Name:      "service_charge_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: serviceChargeStatusIndexes{
		IdxServiceChargeStatusesServiceChargeID: index{
			Type: "BTREE",
			Name: "idx_service_charge_statuses_service_charge_id",
			Columns: []indexColumn{
				{
					Name:         "service_charge_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: serviceChargeStatusForeignKeys{
		FKServiceChargeStatusesCharge: foreignKey{
			constraint: constraint{
				Name:    "fk_service_charge_statuses_charge",
				Columns: []string{"service_charge_id"},
				Comment: "",
			},
			ForeignTable:   "service_charges",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type serviceChargeStatusColumns struct {
	ID              column
	Name            column
	Status          column
	ServiceChargeID column
	CreatedAt       column
}

func (c serviceChargeStatusColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Status, c.ServiceChargeID, c.CreatedAt,
	}
}

type serviceChargeStatusIndexes struct {
	IdxServiceChargeStatusesServiceChargeID index
	PRIMARY                                 index
}

func (i serviceChargeStatusIndexes) AsSlice() []index {
	return []index{
		i.IdxServiceChargeStatusesServiceChargeID, i.PRIMARY,
	}
}

type serviceChargeStatusForeignKeys struct {
	FKServiceChargeStatusesCharge foreignKey
}

func (f serviceChargeStatusForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKServiceChargeStatusesCharge,
	}
}

type serviceChargeStatusUniques struct{}

func (u serviceChargeStatusUniques) AsSlice() []constraint {
	return []constraint{}
}

type serviceChargeStatusChecks struct{}

func (c serviceChargeStatusChecks) AsSlice() []check {
	return []check{}
}
