// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Subscriptions = Table[
	subscriptionColumns,
	subscriptionIndexes,
	subscriptionForeignKeys,
	subscriptionUniques,
	subscriptionChecks,
]{
	Schema: "",
	Name:   "subscriptions",
	Columns: subscriptionColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		AccountID: column{
			Name:      "account_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CatalogID: column{
			Name:      "catalog_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartDate: column{
			Name:      "start_date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EndDate: column{
			Name:      "end_date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IdempotencyKey: column{
			Name:      "idempotency_key",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		NextBillingDate: column{
			Name:      "next_billing_date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: subscriptionIndexes{
		IdempotencyKey: index{
			Type: "BTREE",
			Name: "idempotency_key",
			Columns: []indexColumn{
				{
					Name:         "idempotency_key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		IdxSubscriptionsAccountID: index{
			Type: "BTREE",
			Name: "idx_subscriptions_account_id",
			Columns: []indexColumn{
				{
					Name:         "account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxSubscriptionsCatalogID: index{
			Type: "BTREE",
			Name: "idx_subscriptions_catalog_id",
			Columns: []indexColumn{
				{
					Name:         "catalog_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxSubscriptionsNextBillingDate: index{
			Type: "BTREE",
			Name: "idx_subscriptions_next_billing_date",
			Columns: []indexColumn{
				{
					Name:         "next_billing_date",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: subscriptionForeignKeys{
		FKSubscriptionsAccount: foreignKey{
			constraint: constraint{
				Name:    "fk_subscriptions_account",
				Columns: []string{"account_id"},
				Comment: "",
			},
			ForeignTable:   "accounts",
			ForeignColumns: []string{"id"},
		},
		FKSubscriptionsCatalog: foreignKey{
			constraint: constraint{
				Name:    "fk_subscriptions_catalog",
				Columns: []string{"catalog_id"},
				Comment: "",
			},
			ForeignTable:   "catalogs",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: subscriptionUniques{
		IdempotencyKey: constraint{
			Name:    "idempotency_key",
			Columns: []string{"idempotency_key"},
			Comment: "",
		},
	},

	Comment: "",
}

type subscriptionColumns struct {
	ID              column
	AccountID       column
	CatalogID       column
	StartDate       column
	EndDate         column
	IdempotencyKey  column
	NextBillingDate column
	CreatedAt       column
	UpdatedAt       column
}

func (c subscriptionColumns) AsSlice() []column {
	return []column{
		c.ID, c.AccountID, c.CatalogID, c.StartDate, c.EndDate, c.IdempotencyKey, c.NextBillingDate, c.CreatedAt, c.UpdatedAt,
	}
}

type subscriptionIndexes struct {
	IdempotencyKey                  index
	IdxSubscriptionsAccountID       index
	IdxSubscriptionsCatalogID       index
	IdxSubscriptionsNextBillingDate index
	PRIMARY                         index
}

func (i subscriptionIndexes) AsSlice() []index {
	return []index{
		i.IdempotencyKey, i.IdxSubscriptionsAccountID, i.IdxSubscriptionsCatalogID, i.IdxSubscriptionsNextBillingDate, i.PRIMARY,
	}
}

type subscriptionForeignKeys struct {
	FKSubscriptionsAccount foreignKey
	FKSubscriptionsCatalog foreignKey
}

func (f subscriptionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKSubscriptionsAccount, f.FKSubscriptionsCatalog,
	}
}

type subscriptionUniques struct {
	IdempotencyKey constraint
}

func (u subscriptionUniques) AsSlice() []constraint {
	return []constraint{
		u.IdempotencyKey,
	}
}

type subscriptionChecks struct{}

func (c subscriptionChecks) AsSlice() []check {
	return []check{}
}
