// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: servicecharge/v1/servicecharge.proto

package servicechargev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceChargeService_ReserveServiceCharge_FullMethodName      = "/servicecharge.v1.ServiceChargeService/ReserveServiceCharge"
	ServiceChargeService_UpdateServiceChargeStatus_FullMethodName = "/servicecharge.v1.ServiceChargeService/UpdateServiceChargeStatus"
)

// ServiceChargeServiceClient is the client API for ServiceChargeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceChargeServiceClient interface {
	ReserveServiceCharge(ctx context.Context, in *ReserveServiceChargeRequest, opts ...grpc.CallOption) (*ReserveServiceChargeResponse, error)
	UpdateServiceChargeStatus(ctx context.Context, in *UpdateServiceChargeStatusRequest, opts ...grpc.CallOption) (*UpdateServiceChargeStatusResponse, error)
}

type serviceChargeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceChargeServiceClient(cc grpc.ClientConnInterface) ServiceChargeServiceClient {
	return &serviceChargeServiceClient{cc}
}

func (c *serviceChargeServiceClient) ReserveServiceCharge(ctx context.Context, in *ReserveServiceChargeRequest, opts ...grpc.CallOption) (*ReserveServiceChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveServiceChargeResponse)
	err := c.cc.Invoke(ctx, ServiceChargeService_ReserveServiceCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceChargeServiceClient) UpdateServiceChargeStatus(ctx context.Context, in *UpdateServiceChargeStatusRequest, opts ...grpc.CallOption) (*UpdateServiceChargeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceChargeStatusResponse)
	err := c.cc.Invoke(ctx, ServiceChargeService_UpdateServiceChargeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceChargeServiceServer is the server API for ServiceChargeService service.
// All implementations must embed UnimplementedServiceChargeServiceServer
// for forward compatibility.
type ServiceChargeServiceServer interface {
	ReserveServiceCharge(context.Context, *ReserveServiceChargeRequest) (*ReserveServiceChargeResponse, error)
	UpdateServiceChargeStatus(context.Context, *UpdateServiceChargeStatusRequest) (*UpdateServiceChargeStatusResponse, error)
	mustEmbedUnimplementedServiceChargeServiceServer()
}

// UnimplementedServiceChargeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceChargeServiceServer struct{}

func (UnimplementedServiceChargeServiceServer) ReserveServiceCharge(context.Context, *ReserveServiceChargeRequest) (*ReserveServiceChargeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveServiceCharge not implemented")
}
func (UnimplementedServiceChargeServiceServer) UpdateServiceChargeStatus(context.Context, *UpdateServiceChargeStatusRequest) (*UpdateServiceChargeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServiceChargeStatus not implemented")
}
func (UnimplementedServiceChargeServiceServer) mustEmbedUnimplementedServiceChargeServiceServer() {}
func (UnimplementedServiceChargeServiceServer) testEmbeddedByValue()                              {}

// UnsafeServiceChargeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceChargeServiceServer will
// result in compilation errors.
type UnsafeServiceChargeServiceServer interface {
	mustEmbedUnimplementedServiceChargeServiceServer()
}

func RegisterServiceChargeServiceServer(s grpc.ServiceRegistrar, srv ServiceChargeServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceChargeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceChargeService_ServiceDesc, srv)
}

func _ServiceChargeService_ReserveServiceCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveServiceChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceChargeServiceServer).ReserveServiceCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceChargeService_ReserveServiceCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceChargeServiceServer).ReserveServiceCharge(ctx, req.(*ReserveServiceChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceChargeService_UpdateServiceChargeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceChargeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceChargeServiceServer).UpdateServiceChargeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceChargeService_UpdateServiceChargeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceChargeServiceServer).UpdateServiceChargeStatus(ctx, req.(*UpdateServiceChargeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceChargeService_ServiceDesc is the grpc.ServiceDesc for ServiceChargeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceChargeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicecharge.v1.ServiceChargeService",
	HandlerType: (*ServiceChargeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveServiceCharge",
			Handler:    _ServiceChargeService_ReserveServiceCharge_Handler,
		},
		{
			MethodName: "UpdateServiceChargeStatus",
			Handler:    _ServiceChargeService_UpdateServiceChargeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicecharge/v1/servicecharge.proto",
}
