// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servicecharge/v1/servicecharge.proto

package servicechargev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceChargeStatus int32

const (
	ServiceChargeStatus_SERVICE_CHARGE_STATUS_UNSPECIFIED ServiceChargeStatus = 0
	ServiceChargeStatus_SERVICE_CHARGE_STATUS_RESERVED    ServiceChargeStatus = 1
	ServiceChargeStatus_SERVICE_CHARGE_STATUS_COMPLETED   ServiceChargeStatus = 2
	ServiceChargeStatus_SERVICE_CHARGE_STATUS_FAILED      ServiceChargeStatus = 3
	ServiceChargeStatus_SERVICE_CHARGE_STATUS_CANCELLED   ServiceChargeStatus = 4
)

// Enum value maps for ServiceChargeStatus.
var (
	ServiceChargeStatus_name = map[int32]string{
		0: "SERVICE_CHARGE_STATUS_UNSPECIFIED",
		1: "SERVICE_CHARGE_STATUS_RESERVED",
		2: "SERVICE_CHARGE_STATUS_COMPLETED",
		3: "SERVICE_CHARGE_STATUS_FAILED",
		4: "SERVICE_CHARGE_STATUS_CANCELLED",
	}
	ServiceChargeStatus_value = map[string]int32{
		"SERVICE_CHARGE_STATUS_UNSPECIFIED": 0,
		"SERVICE_CHARGE_STATUS_RESERVED":    1,
		"SERVICE_CHARGE_STATUS_COMPLETED":   2,
		"SERVICE_CHARGE_STATUS_FAILED":      3,
		"SERVICE_CHARGE_STATUS_CANCELLED":   4,
	}
)

func (x ServiceChargeStatus) Enum() *ServiceChargeStatus {
	p := new(ServiceChargeStatus)
	*p = x
	return p
}

func (x ServiceChargeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceChargeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_servicecharge_v1_servicecharge_proto_enumTypes[0].Descriptor()
}

func (ServiceChargeStatus) Type() protoreflect.EnumType {
	return &file_servicecharge_v1_servicecharge_proto_enumTypes[0]
}

func (x ServiceChargeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceChargeStatus.Descriptor instead.
func (ServiceChargeStatus) EnumDescriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{0}
}

type ReserveServiceChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Items         []*ServiceChargeItem   `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveServiceChargeRequest) Reset() {
	*x = ReserveServiceChargeRequest{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveServiceChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveServiceChargeRequest) ProtoMessage() {}

func (x *ReserveServiceChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveServiceChargeRequest.ProtoReflect.Descriptor instead.
func (*ReserveServiceChargeRequest) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveServiceChargeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReserveServiceChargeRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ReserveServiceChargeRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ReserveServiceChargeRequest) GetItems() []*ServiceChargeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveServiceChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceCharge *ServiceCharge         `protobuf:"bytes,1,opt,name=service_charge,json=serviceCharge,proto3" json:"service_charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveServiceChargeResponse) Reset() {
	*x = ReserveServiceChargeResponse{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveServiceChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveServiceChargeResponse) ProtoMessage() {}

func (x *ReserveServiceChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveServiceChargeResponse.ProtoReflect.Descriptor instead.
func (*ReserveServiceChargeResponse) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveServiceChargeResponse) GetServiceCharge() *ServiceCharge {
	if x != nil {
		return x.ServiceCharge
	}
	return nil
}

type UpdateServiceChargeStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceChargeId string                 `protobuf:"bytes,1,opt,name=service_charge_id,json=serviceChargeId,proto3" json:"service_charge_id,omitempty"`
	Status          ServiceChargeStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=servicecharge.v1.ServiceChargeStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateServiceChargeStatusRequest) Reset() {
	*x = UpdateServiceChargeStatusRequest{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceChargeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceChargeStatusRequest) ProtoMessage() {}

func (x *UpdateServiceChargeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceChargeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceChargeStatusRequest) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServiceChargeStatusRequest) GetServiceChargeId() string {
	if x != nil {
		return x.ServiceChargeId
	}
	return ""
}

func (x *UpdateServiceChargeStatusRequest) GetStatus() ServiceChargeStatus {
	if x != nil {
		return x.Status
	}
	return ServiceChargeStatus_SERVICE_CHARGE_STATUS_UNSPECIFIED
}

type UpdateServiceChargeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceCharge *ServiceCharge         `protobuf:"bytes,1,opt,name=service_charge,json=serviceCharge,proto3" json:"service_charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceChargeStatusResponse) Reset() {
	*x = UpdateServiceChargeStatusResponse{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceChargeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceChargeStatusResponse) ProtoMessage() {}

func (x *UpdateServiceChargeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceChargeStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceChargeStatusResponse) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServiceChargeStatusResponse) GetServiceCharge() *ServiceCharge {
	if x != nil {
		return x.ServiceCharge
	}
	return nil
}

type ServiceCharge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Items         []*ServiceChargeItem   `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	LatestStatus  ServiceChargeStatus    `protobuf:"varint,6,opt,name=latest_status,json=latestStatus,proto3,enum=servicecharge.v1.ServiceChargeStatus" json:"latest_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCharge) Reset() {
	*x = ServiceCharge{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCharge) ProtoMessage() {}

func (x *ServiceCharge) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCharge.ProtoReflect.Descriptor instead.
func (*ServiceCharge) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceCharge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceCharge) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ServiceCharge) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ServiceCharge) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ServiceCharge) GetItems() []*ServiceChargeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ServiceCharge) GetLatestStatus() ServiceChargeStatus {
	if x != nil {
		return x.LatestStatus
	}
	return ServiceChargeStatus_SERVICE_CHARGE_STATUS_UNSPECIFIED
}

type ServiceChargeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        *ServiceChargeSource   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChargeItem) Reset() {
	*x = ServiceChargeItem{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChargeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChargeItem) ProtoMessage() {}

func (x *ServiceChargeItem) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChargeItem.ProtoReflect.Descriptor instead.
func (*ServiceChargeItem) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceChargeItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceChargeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceChargeItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ServiceChargeItem) GetSource() *ServiceChargeSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type ServiceChargeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ServiceChargeSource_OneShotUsageId
	//	*ServiceChargeSource_SubscriptionId
	//	*ServiceChargeSource_ManualReason
	Source        isServiceChargeSource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChargeSource) Reset() {
	*x = ServiceChargeSource{}
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChargeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChargeSource) ProtoMessage() {}

func (x *ServiceChargeSource) ProtoReflect() protoreflect.Message {
	mi := &file_servicecharge_v1_servicecharge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChargeSource.ProtoReflect.Descriptor instead.
func (*ServiceChargeSource) Descriptor() ([]byte, []int) {
	return file_servicecharge_v1_servicecharge_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceChargeSource) GetSource() isServiceChargeSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ServiceChargeSource) GetOneShotUsageId() string {
	if x != nil {
		if x, ok := x.Source.(*ServiceChargeSource_OneShotUsageId); ok {
			return x.OneShotUsageId
		}
	}
	return ""
}

func (x *ServiceChargeSource) GetSubscriptionId() string {
	if x != nil {
		if x, ok := x.Source.(*ServiceChargeSource_SubscriptionId); ok {
			return x.SubscriptionId
		}
	}
	return ""
}

func (x *ServiceChargeSource) GetManualReason() string {
	if x != nil {
		if x, ok := x.Source.(*ServiceChargeSource_ManualReason); ok {
			return x.ManualReason
		}
	}
	return ""
}

type isServiceChargeSource_Source interface {
	isServiceChargeSource_Source()
}

type ServiceChargeSource_OneShotUsageId struct {
	OneShotUsageId string `protobuf:"bytes,1,opt,name=one_shot_usage_id,json=oneShotUsageId,proto3,oneof"`
}

type ServiceChargeSource_SubscriptionId struct {
	SubscriptionId string `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3,oneof"`
}

type ServiceChargeSource_ManualReason struct {
	ManualReason string `protobuf:"bytes,3,opt,name=manual_reason,json=manualReason,proto3,oneof"`
}

func (*ServiceChargeSource_OneShotUsageId) isServiceChargeSource_Source() {}

func (*ServiceChargeSource_SubscriptionId) isServiceChargeSource_Source() {}

func (*ServiceChargeSource_ManualReason) isServiceChargeSource_Source() {}

var File_servicecharge_v1_servicecharge_proto protoreflect.FileDescriptor

const file_servicecharge_v1_servicecharge_proto_rawDesc = "" +
	"\n" +
	"$servicecharge/v1/servicecharge.proto\x12\x10servicecharge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\x1bReserveServiceChargeRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x129\n" +
	"\x05items\x18\x04 \x03(\v2#.servicecharge.v1.ServiceChargeItemR\x05items\"f\n" +
	"\x1cReserveServiceChargeResponse\x12F\n" +
	"\x0eservice_charge\x18\x01 \x01(\v2\x1f.servicecharge.v1.ServiceChargeR\rserviceCharge\"\x8d\x01\n" +
	" UpdateServiceChargeStatusRequest\x12*\n" +
	"\x11service_charge_id\x18\x01 \x01(\tR\x0fserviceChargeId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.servicecharge.v1.ServiceChargeStatusR\x06status\"k\n" +
	"!UpdateServiceChargeStatusResponse\x12F\n" +
	"\x0eservice_charge\x18\x01 \x01(\v2\x1f.servicecharge.v1.ServiceChargeR\rserviceCharge\"\xb7\x02\n" +
	"\rServiceCharge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x129\n" +
	"\x05items\x18\x05 \x03(\v2#.servicecharge.v1.ServiceChargeItemR\x05items\x12J\n" +
	"\rlatest_status\x18\x06 \x01(\x0e2%.servicecharge.v1.ServiceChargeStatusR\flatestStatus\"\x8e\x01\n" +
	"\x11ServiceChargeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12=\n" +
	"\x06source\x18\x04 \x01(\v2%.servicecharge.v1.ServiceChargeSourceR\x06source\"\x9e\x01\n" +
	"\x13ServiceChargeSource\x12+\n" +
	"\x11one_shot_usage_id\x18\x01 \x01(\tH\x00R\x0eoneShotUsageId\x12)\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tH\x00R\x0esubscriptionId\x12%\n" +
	"\rmanual_reason\x18\x03 \x01(\tH\x00R\fmanualReasonB\b\n" +
	"\x06source*\xcc\x01\n" +
	"\x13ServiceChargeStatus\x12%\n" +
	"!SERVICE_CHARGE_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSERVICE_CHARGE_STATUS_RESERVED\x10\x01\x12#\n" +
	"\x1fSERVICE_CHARGE_STATUS_COMPLETED\x10\x02\x12 \n" +
	"\x1cSERVICE_CHARGE_STATUS_FAILED\x10\x03\x12#\n" +
	"\x1fSERVICE_CHARGE_STATUS_CANCELLED\x10\x042\x94\x02\n" +
	"\x14ServiceChargeService\x12u\n" +
	"\x14ReserveServiceCharge\x12-.servicecharge.v1.ReserveServiceChargeRequest\x1a..servicecharge.v1.ReserveServiceChargeResponse\x12\x84\x01\n" +
	"\x19UpdateServiceChargeStatus\x122.servicecharge.v1.UpdateServiceChargeStatusRequest\x1a3.servicecharge.v1.UpdateServiceChargeStatusResponseB\xc5\x01\n" +
	"\x14com.servicecharge.v1B\x12ServicechargeProtoP\x01Z8github.com/flora/pkg/pb/servicecharge/v1;servicechargev1\xa2\x02\x03SXX\xaa\x02\x10Servicecharge.V1\xca\x02\x10Servicecharge\\V1\xe2\x02\x1cServicecharge\\V1\\GPBMetadata\xea\x02\x11Servicecharge::V1b\x06proto3"

var (
	file_servicecharge_v1_servicecharge_proto_rawDescOnce sync.Once
	file_servicecharge_v1_servicecharge_proto_rawDescData []byte
)

func file_servicecharge_v1_servicecharge_proto_rawDescGZIP() []byte {
	file_servicecharge_v1_servicecharge_proto_rawDescOnce.Do(func() {
		file_servicecharge_v1_servicecharge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicecharge_v1_servicecharge_proto_rawDesc), len(file_servicecharge_v1_servicecharge_proto_rawDesc)))
	})
	return file_servicecharge_v1_servicecharge_proto_rawDescData
}

var file_servicecharge_v1_servicecharge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servicecharge_v1_servicecharge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_servicecharge_v1_servicecharge_proto_goTypes = []any{
	(ServiceChargeStatus)(0),                  // 0: servicecharge.v1.ServiceChargeStatus
	(*ReserveServiceChargeRequest)(nil),       // 1: servicecharge.v1.ReserveServiceChargeRequest
	(*ReserveServiceChargeResponse)(nil),      // 2: servicecharge.v1.ReserveServiceChargeResponse
	(*UpdateServiceChargeStatusRequest)(nil),  // 3: servicecharge.v1.UpdateServiceChargeStatusRequest
	(*UpdateServiceChargeStatusResponse)(nil), // 4: servicecharge.v1.UpdateServiceChargeStatusResponse
	(*ServiceCharge)(nil),                     // 5: servicecharge.v1.ServiceCharge
	(*ServiceChargeItem)(nil),                 // 6: servicecharge.v1.ServiceChargeItem
	(*ServiceChargeSource)(nil),               // 7: servicecharge.v1.ServiceChargeSource
	(*timestamppb.Timestamp)(nil),             // 8: google.protobuf.Timestamp
}
var file_servicecharge_v1_servicecharge_proto_depIdxs = []int32{
	8,  // 0: servicecharge.v1.ReserveServiceChargeRequest.start_date:type_name -> google.protobuf.Timestamp
	8,  // 1: servicecharge.v1.ReserveServiceChargeRequest.end_date:type_name -> google.protobuf.Timestamp
	6,  // 2: servicecharge.v1.ReserveServiceChargeRequest.items:type_name -> servicecharge.v1.ServiceChargeItem
	5,  // 3: servicecharge.v1.ReserveServiceChargeResponse.service_charge:type_name -> servicecharge.v1.ServiceCharge
	0,  // 4: servicecharge.v1.UpdateServiceChargeStatusRequest.status:type_name -> servicecharge.v1.ServiceChargeStatus
	5,  // 5: servicecharge.v1.UpdateServiceChargeStatusResponse.service_charge:type_name -> servicecharge.v1.ServiceCharge
	8,  // 6: servicecharge.v1.ServiceCharge.start_date:type_name -> google.protobuf.Timestamp
	8,  // 7: servicecharge.v1.ServiceCharge.end_date:type_name -> google.protobuf.Timestamp
	6,  // 8: servicecharge.v1.ServiceCharge.items:type_name -> servicecharge.v1.ServiceChargeItem
	0,  // 9: servicecharge.v1.ServiceCharge.latest_status:type_name -> servicecharge.v1.ServiceChargeStatus
	7,  // 10: servicecharge.v1.ServiceChargeItem.source:type_name -> servicecharge.v1.ServiceChargeSource
	1,  // 11: servicecharge.v1.ServiceChargeService.ReserveServiceCharge:input_type -> servicecharge.v1.ReserveServiceChargeRequest
	3,  // 12: servicecharge.v1.ServiceChargeService.UpdateServiceChargeStatus:input_type -> servicecharge.v1.UpdateServiceChargeStatusRequest
	2,  // 13: servicecharge.v1.ServiceChargeService.ReserveServiceCharge:output_type -> servicecharge.v1.ReserveServiceChargeResponse
	4,  // 14: servicecharge.v1.ServiceChargeService.UpdateServiceChargeStatus:output_type -> servicecharge.v1.UpdateServiceChargeStatusResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_servicecharge_v1_servicecharge_proto_init() }
func file_servicecharge_v1_servicecharge_proto_init() {
	if File_servicecharge_v1_servicecharge_proto != nil {
		return
	}
	file_servicecharge_v1_servicecharge_proto_msgTypes[6].OneofWrappers = []any{
		(*ServiceChargeSource_OneShotUsageId)(nil),
		(*ServiceChargeSource_SubscriptionId)(nil),
		(*ServiceChargeSource_ManualReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicecharge_v1_servicecharge_proto_rawDesc), len(file_servicecharge_v1_servicecharge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicecharge_v1_servicecharge_proto_goTypes,
		DependencyIndexes: file_servicecharge_v1_servicecharge_proto_depIdxs,
		EnumInfos:         file_servicecharge_v1_servicecharge_proto_enumTypes,
		MessageInfos:      file_servicecharge_v1_servicecharge_proto_msgTypes,
	}.Build()
	File_servicecharge_v1_servicecharge_proto = out.File
	file_servicecharge_v1_servicecharge_proto_goTypes = nil
	file_servicecharge_v1_servicecharge_proto_depIdxs = nil
}
