// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/flora/api/internal/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type AccountMod interface {
	Apply(context.Context, *AccountTemplate)
}

type AccountModFunc func(context.Context, *AccountTemplate)

func (f AccountModFunc) Apply(ctx context.Context, n *AccountTemplate) {
	f(ctx, n)
}

type AccountModSlice []AccountMod

func (mods AccountModSlice) Apply(ctx context.Context, n *AccountTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AccountTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AccountTemplate struct {
	ID                func() types.Uint64
	ExternalAccountID func() string
	TenantID          func() types.Uint64
	CreatedAt         func() time.Time
	UpdatedAt         func() time.Time

	r accountR
	f *Factory

	alreadyPersisted bool
}

type accountR struct {
	Tenant         *accountRTenantR
	OneShotUsages  []*accountROneShotUsagesR
	ServiceCharges []*accountRServiceChargesR
	Subscriptions  []*accountRSubscriptionsR
}

type accountRTenantR struct {
	o *TenantTemplate
}
type accountROneShotUsagesR struct {
	number int
	o      *OneShotUsageTemplate
}
type accountRServiceChargesR struct {
	number int
	o      *ServiceChargeTemplate
}
type accountRSubscriptionsR struct {
	number int
	o      *SubscriptionTemplate
}

// Apply mods to the AccountTemplate
func (o *AccountTemplate) Apply(ctx context.Context, mods ...AccountMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Account
// according to the relationships in the template. Nothing is inserted into the db
func (t AccountTemplate) setModelRels(o *models.Account) {
	if t.r.Tenant != nil {
		rel := t.r.Tenant.o.Build()
		rel.R.Accounts = append(rel.R.Accounts, o)
		o.TenantID = rel.ID // h2
		o.R.Tenant = rel
	}

	if t.r.OneShotUsages != nil {
		rel := models.OneShotUsageSlice{}
		for _, r := range t.r.OneShotUsages {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.AccountID = o.ID // h2
				rel.R.Account = o
			}
			rel = append(rel, related...)
		}
		o.R.OneShotUsages = rel
	}

	if t.r.ServiceCharges != nil {
		rel := models.ServiceChargeSlice{}
		for _, r := range t.r.ServiceCharges {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.AccountID = o.ID // h2
				rel.R.Account = o
			}
			rel = append(rel, related...)
		}
		o.R.ServiceCharges = rel
	}

	if t.r.Subscriptions != nil {
		rel := models.SubscriptionSlice{}
		for _, r := range t.r.Subscriptions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.AccountID = o.ID // h2
				rel.R.Account = o
			}
			rel = append(rel, related...)
		}
		o.R.Subscriptions = rel
	}
}

// BuildSetter returns an *models.AccountSetter
// this does nothing with the relationship templates
func (o AccountTemplate) BuildSetter() *models.AccountSetter {
	m := &models.AccountSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *types.Uint64 { return &val }()
	}
	if o.ExternalAccountID != nil {
		val := o.ExternalAccountID()
		m.ExternalAccountID = func() *string { return &val }()
	}
	if o.TenantID != nil {
		val := o.TenantID()
		m.TenantID = func() *types.Uint64 { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.AccountSetter
// this does nothing with the relationship templates
func (o AccountTemplate) BuildManySetter(number int) []*models.AccountSetter {
	m := make([]*models.AccountSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Account
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AccountTemplate.Create
func (o AccountTemplate) Build() *models.Account {
	m := &models.Account{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ExternalAccountID != nil {
		m.ExternalAccountID = o.ExternalAccountID()
	}
	if o.TenantID != nil {
		m.TenantID = o.TenantID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AccountSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AccountTemplate.CreateMany
func (o AccountTemplate) BuildMany(number int) models.AccountSlice {
	m := make(models.AccountSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAccount(m *models.AccountSetter) {
	if !(m.ExternalAccountID != nil) {
		val := random_string(nil, "255")
		m.ExternalAccountID = func() *string { return &val }()
	}
	if !(m.TenantID != nil) {
		val := random_types_Uint64(nil)
		m.TenantID = func() *types.Uint64 { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Account
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AccountTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Account) error {
	var err error

	isOneShotUsagesDone, _ := accountRelOneShotUsagesCtx.Value(ctx)
	if !isOneShotUsagesDone && o.r.OneShotUsages != nil {
		ctx = accountRelOneShotUsagesCtx.WithValue(ctx, true)
		for _, r := range o.r.OneShotUsages {
			if r.o.alreadyPersisted {
				m.R.OneShotUsages = append(m.R.OneShotUsages, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOneShotUsages(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isServiceChargesDone, _ := accountRelServiceChargesCtx.Value(ctx)
	if !isServiceChargesDone && o.r.ServiceCharges != nil {
		ctx = accountRelServiceChargesCtx.WithValue(ctx, true)
		for _, r := range o.r.ServiceCharges {
			if r.o.alreadyPersisted {
				m.R.ServiceCharges = append(m.R.ServiceCharges, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachServiceCharges(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSubscriptionsDone, _ := accountRelSubscriptionsCtx.Value(ctx)
	if !isSubscriptionsDone && o.r.Subscriptions != nil {
		ctx = accountRelSubscriptionsCtx.WithValue(ctx, true)
		for _, r := range o.r.Subscriptions {
			if r.o.alreadyPersisted {
				m.R.Subscriptions = append(m.R.Subscriptions, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSubscriptions(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AccountTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Account, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAccount(opt)

	if o.r.Tenant == nil {
		AccountMods.WithNewTenant().Apply(ctx, o)
	}

	var rel0 *models.Tenant

	if o.r.Tenant.o.alreadyPersisted {
		rel0 = o.r.Tenant.o.Build()
	} else {
		rel0, err = o.r.Tenant.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.TenantID = func() *types.Uint64 { return &rel0.ID }()

	m, err := models.Accounts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Tenant = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AccountTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Account {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AccountTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Account {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AccountTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AccountSlice, error) {
	var err error
	m := make(models.AccountSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AccountTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AccountSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AccountTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AccountSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Account has methods that act as mods for the AccountTemplate
var AccountMods accountMods

type accountMods struct{}

func (m accountMods) RandomizeAllColumns(f *faker.Faker) AccountMod {
	return AccountModSlice{
		AccountMods.RandomID(f),
		AccountMods.RandomExternalAccountID(f),
		AccountMods.RandomTenantID(f),
		AccountMods.RandomCreatedAt(f),
		AccountMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m accountMods) ID(val types.Uint64) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m accountMods) IDFunc(f func() types.Uint64) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetID() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomID(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) ExternalAccountID(val string) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ExternalAccountID = func() string { return val }
	})
}

// Set the Column from the function
func (m accountMods) ExternalAccountIDFunc(f func() string) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ExternalAccountID = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetExternalAccountID() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ExternalAccountID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomExternalAccountID(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ExternalAccountID = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m accountMods) TenantID(val types.Uint64) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.TenantID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m accountMods) TenantIDFunc(f func() types.Uint64) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.TenantID = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetTenantID() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.TenantID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomTenantID(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.TenantID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) CreatedAt(val time.Time) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m accountMods) CreatedAtFunc(f func() time.Time) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetCreatedAt() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomCreatedAt(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) UpdatedAt(val time.Time) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m accountMods) UpdatedAtFunc(f func() time.Time) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetUpdatedAt() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomUpdatedAt(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m accountMods) WithParentsCascading() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		if isDone, _ := accountWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = accountWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewTenantWithContext(ctx, TenantMods.WithParentsCascading())
			m.WithTenant(related).Apply(ctx, o)
		}
	})
}

func (m accountMods) WithTenant(rel *TenantTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Tenant = &accountRTenantR{
			o: rel,
		}
	})
}

func (m accountMods) WithNewTenant(mods ...TenantMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewTenantWithContext(ctx, mods...)

		m.WithTenant(related).Apply(ctx, o)
	})
}

func (m accountMods) WithExistingTenant(em *models.Tenant) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Tenant = &accountRTenantR{
			o: o.f.FromExistingTenant(em),
		}
	})
}

func (m accountMods) WithoutTenant() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Tenant = nil
	})
}

func (m accountMods) WithOneShotUsages(number int, related *OneShotUsageTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.OneShotUsages = []*accountROneShotUsagesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m accountMods) WithNewOneShotUsages(number int, mods ...OneShotUsageMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewOneShotUsageWithContext(ctx, mods...)
		m.WithOneShotUsages(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddOneShotUsages(number int, related *OneShotUsageTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.OneShotUsages = append(o.r.OneShotUsages, &accountROneShotUsagesR{
			number: number,
			o:      related,
		})
	})
}

func (m accountMods) AddNewOneShotUsages(number int, mods ...OneShotUsageMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewOneShotUsageWithContext(ctx, mods...)
		m.AddOneShotUsages(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddExistingOneShotUsages(existingModels ...*models.OneShotUsage) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		for _, em := range existingModels {
			o.r.OneShotUsages = append(o.r.OneShotUsages, &accountROneShotUsagesR{
				o: o.f.FromExistingOneShotUsage(em),
			})
		}
	})
}

func (m accountMods) WithoutOneShotUsages() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.OneShotUsages = nil
	})
}

func (m accountMods) WithServiceCharges(number int, related *ServiceChargeTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.ServiceCharges = []*accountRServiceChargesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m accountMods) WithNewServiceCharges(number int, mods ...ServiceChargeMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewServiceChargeWithContext(ctx, mods...)
		m.WithServiceCharges(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddServiceCharges(number int, related *ServiceChargeTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.ServiceCharges = append(o.r.ServiceCharges, &accountRServiceChargesR{
			number: number,
			o:      related,
		})
	})
}

func (m accountMods) AddNewServiceCharges(number int, mods ...ServiceChargeMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewServiceChargeWithContext(ctx, mods...)
		m.AddServiceCharges(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddExistingServiceCharges(existingModels ...*models.ServiceCharge) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		for _, em := range existingModels {
			o.r.ServiceCharges = append(o.r.ServiceCharges, &accountRServiceChargesR{
				o: o.f.FromExistingServiceCharge(em),
			})
		}
	})
}

func (m accountMods) WithoutServiceCharges() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.ServiceCharges = nil
	})
}

func (m accountMods) WithSubscriptions(number int, related *SubscriptionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Subscriptions = []*accountRSubscriptionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m accountMods) WithNewSubscriptions(number int, mods ...SubscriptionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewSubscriptionWithContext(ctx, mods...)
		m.WithSubscriptions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddSubscriptions(number int, related *SubscriptionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Subscriptions = append(o.r.Subscriptions, &accountRSubscriptionsR{
			number: number,
			o:      related,
		})
	})
}

func (m accountMods) AddNewSubscriptions(number int, mods ...SubscriptionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewSubscriptionWithContext(ctx, mods...)
		m.AddSubscriptions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddExistingSubscriptions(existingModels ...*models.Subscription) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		for _, em := range existingModels {
			o.r.Subscriptions = append(o.r.Subscriptions, &accountRSubscriptionsR{
				o: o.f.FromExistingSubscription(em),
			})
		}
	})
}

func (m accountMods) WithoutSubscriptions() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Subscriptions = nil
	})
}
