// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for accounts
	accountWithParentsCascadingCtx = newContextual[bool]("accountWithParentsCascading")
	accountRelTenantCtx            = newContextual[bool]("accounts.tenants.fk_accounts_tenant")
	accountRelOneShotUsagesCtx     = newContextual[bool]("accounts.one_shot_usages.fk_one_shot_usages_account")
	accountRelServiceChargesCtx    = newContextual[bool]("accounts.service_charges.fk_service_charges_account")
	accountRelSubscriptionsCtx     = newContextual[bool]("accounts.subscriptions.fk_subscriptions_account")

	// Relationship Contexts for catalog_prices
	catalogPriceWithParentsCascadingCtx = newContextual[bool]("catalogPriceWithParentsCascading")
	catalogPriceRelCatalogCtx           = newContextual[bool]("catalog_prices.catalogs.fk_catalog_prices_catalog")

	// Relationship Contexts for catalogs
	catalogWithParentsCascadingCtx = newContextual[bool]("catalogWithParentsCascading")
	catalogRelCatalogPricesCtx     = newContextual[bool]("catalog_prices.catalogs.fk_catalog_prices_catalog")
	catalogRelTenantCtx            = newContextual[bool]("catalogs.tenants.fk_catalogs_tenant")
	catalogRelOneShotUsagesCtx     = newContextual[bool]("catalogs.one_shot_usages.fk_one_shot_usages_catalog")
	catalogRelSubscriptionsCtx     = newContextual[bool]("catalogs.subscriptions.fk_subscriptions_catalog")

	// Relationship Contexts for one_shot_usages
	oneShotUsageWithParentsCascadingCtx  = newContextual[bool]("oneShotUsageWithParentsCascading")
	oneShotUsageRelAccountCtx            = newContextual[bool]("accounts.one_shot_usages.fk_one_shot_usages_account")
	oneShotUsageRelCatalogCtx            = newContextual[bool]("catalogs.one_shot_usages.fk_one_shot_usages_catalog")
	oneShotUsageRelServiceChargeItemsCtx = newContextual[bool]("one_shot_usages.service_charge_items.fk_service_charge_items_one_shot")

	// Relationship Contexts for schema_migrations
	schemaMigrationWithParentsCascadingCtx = newContextual[bool]("schemaMigrationWithParentsCascading")

	// Relationship Contexts for service_charge_items
	serviceChargeItemWithParentsCascadingCtx = newContextual[bool]("serviceChargeItemWithParentsCascading")
	serviceChargeItemRelServiceChargeCtx     = newContextual[bool]("service_charge_items.service_charges.fk_service_charge_items_charge")
	serviceChargeItemRelOneShotUsageCtx      = newContextual[bool]("one_shot_usages.service_charge_items.fk_service_charge_items_one_shot")
	serviceChargeItemRelSubscriptionCtx      = newContextual[bool]("service_charge_items.subscriptions.fk_service_charge_items_subscription")

	// Relationship Contexts for service_charge_statuses
	serviceChargeStatusWithParentsCascadingCtx          = newContextual[bool]("serviceChargeStatusWithParentsCascading")
	serviceChargeStatusRelServiceChargeCtx              = newContextual[bool]("service_charge_statuses.service_charges.fk_service_charge_statuses_charge")
	serviceChargeStatusRelLatestStatusServiceChargesCtx = newContextual[bool]("service_charge_statuses.service_charges.fk_service_charges_latest_status")

	// Relationship Contexts for service_charges
	serviceChargeWithParentsCascadingCtx               = newContextual[bool]("serviceChargeWithParentsCascading")
	serviceChargeRelServiceChargeItemsCtx              = newContextual[bool]("service_charge_items.service_charges.fk_service_charge_items_charge")
	serviceChargeRelServiceChargeStatusesCtx           = newContextual[bool]("service_charge_statuses.service_charges.fk_service_charge_statuses_charge")
	serviceChargeRelAccountCtx                         = newContextual[bool]("accounts.service_charges.fk_service_charges_account")
	serviceChargeRelLatestStatusServiceChargeStatusCtx = newContextual[bool]("service_charge_statuses.service_charges.fk_service_charges_latest_status")

	// Relationship Contexts for subscriptions
	subscriptionWithParentsCascadingCtx  = newContextual[bool]("subscriptionWithParentsCascading")
	subscriptionRelServiceChargeItemsCtx = newContextual[bool]("service_charge_items.subscriptions.fk_service_charge_items_subscription")
	subscriptionRelAccountCtx            = newContextual[bool]("accounts.subscriptions.fk_subscriptions_account")
	subscriptionRelCatalogCtx            = newContextual[bool]("catalogs.subscriptions.fk_subscriptions_catalog")

	// Relationship Contexts for tenants
	tenantWithParentsCascadingCtx = newContextual[bool]("tenantWithParentsCascading")
	tenantRelAccountsCtx          = newContextual[bool]("accounts.tenants.fk_accounts_tenant")
	tenantRelCatalogsCtx          = newContextual[bool]("catalogs.tenants.fk_catalogs_tenant")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
