// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"strconv"
	"strings"
	"time"

	enums "github.com/flora/api/internal/bob/enums"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob/types"
)

var defaultFaker = faker.New()

func random_bool(f *faker.Faker, limits ...string) bool {
	if f == nil {
		f = &defaultFaker
	}

	return f.Bool()
}

func random_enums_CatalogPricesBillingCycle(f *faker.Faker, limits ...string) enums.CatalogPricesBillingCycle {
	if f == nil {
		f = &defaultFaker
	}

	var e enums.CatalogPricesBillingCycle
	all := e.All()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_enums_CatalogPricesBillingType(f *faker.Faker, limits ...string) enums.CatalogPricesBillingType {
	if f == nil {
		f = &defaultFaker
	}

	var e enums.CatalogPricesBillingType
	all := e.All()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_enums_ServiceChargeStatusesStatus(f *faker.Faker, limits ...string) enums.ServiceChargeStatusesStatus {
	if f == nil {
		f = &defaultFaker
	}

	var e enums.ServiceChargeStatusesStatus
	all := e.All()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_int64(f *faker.Faker, limits ...string) int64 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int64()
}

func random_string(f *faker.Faker, limits ...string) string {
	if f == nil {
		f = &defaultFaker
	}

	val := strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
	if len(limits) == 0 {
		return val
	}
	limitInt, _ := strconv.Atoi(limits[0])
	if limitInt > 0 && limitInt < len(val) {
		val = val[:limitInt]
	}
	return val
}

func random_time_Time(f *faker.Faker, limits ...string) time.Time {
	if f == nil {
		f = &defaultFaker
	}

	year := time.Hour * 24 * 365
	min := time.Now().Add(-year)
	max := time.Now().Add(year)
	return f.Time().TimeBetween(min, max)
}

func random_types_Uint64(f *faker.Faker, limits ...string) types.Uint64 {
	if f == nil {
		f = &defaultFaker
	}

	return types.Uint64(f.UInt64())
}
