// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	enums "github.com/flora/api/internal/bob/enums"
	models "github.com/flora/api/internal/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type CatalogPriceMod interface {
	Apply(context.Context, *CatalogPriceTemplate)
}

type CatalogPriceModFunc func(context.Context, *CatalogPriceTemplate)

func (f CatalogPriceModFunc) Apply(ctx context.Context, n *CatalogPriceTemplate) {
	f(ctx, n)
}

type CatalogPriceModSlice []CatalogPriceMod

func (mods CatalogPriceModSlice) Apply(ctx context.Context, n *CatalogPriceTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CatalogPriceTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CatalogPriceTemplate struct {
	ID           func() types.Uint64
	CatalogID    func() types.Uint64
	Amount       func() int64
	BillingType  func() enums.CatalogPricesBillingType
	BillingCycle func() sql.Null[enums.CatalogPricesBillingCycle]
	StartDate    func() time.Time
	EndDate      func() sql.Null[time.Time]
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time

	r catalogPriceR
	f *Factory

	alreadyPersisted bool
}

type catalogPriceR struct {
	Catalog *catalogPriceRCatalogR
}

type catalogPriceRCatalogR struct {
	o *CatalogTemplate
}

// Apply mods to the CatalogPriceTemplate
func (o *CatalogPriceTemplate) Apply(ctx context.Context, mods ...CatalogPriceMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.CatalogPrice
// according to the relationships in the template. Nothing is inserted into the db
func (t CatalogPriceTemplate) setModelRels(o *models.CatalogPrice) {
	if t.r.Catalog != nil {
		rel := t.r.Catalog.o.Build()
		rel.R.CatalogPrices = append(rel.R.CatalogPrices, o)
		o.CatalogID = rel.ID // h2
		o.R.Catalog = rel
	}
}

// BuildSetter returns an *models.CatalogPriceSetter
// this does nothing with the relationship templates
func (o CatalogPriceTemplate) BuildSetter() *models.CatalogPriceSetter {
	m := &models.CatalogPriceSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *types.Uint64 { return &val }()
	}
	if o.CatalogID != nil {
		val := o.CatalogID()
		m.CatalogID = func() *types.Uint64 { return &val }()
	}
	if o.Amount != nil {
		val := o.Amount()
		m.Amount = func() *int64 { return &val }()
	}
	if o.BillingType != nil {
		val := o.BillingType()
		m.BillingType = func() *enums.CatalogPricesBillingType { return &val }()
	}
	if o.BillingCycle != nil {
		val := o.BillingCycle()
		m.BillingCycle = func() *sql.Null[enums.CatalogPricesBillingCycle] { v := val; return &v }()
	}
	if o.StartDate != nil {
		val := o.StartDate()
		m.StartDate = func() *time.Time { return &val }()
	}
	if o.EndDate != nil {
		val := o.EndDate()
		m.EndDate = func() *sql.Null[time.Time] { v := val; return &v }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.CatalogPriceSetter
// this does nothing with the relationship templates
func (o CatalogPriceTemplate) BuildManySetter(number int) []*models.CatalogPriceSetter {
	m := make([]*models.CatalogPriceSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.CatalogPrice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CatalogPriceTemplate.Create
func (o CatalogPriceTemplate) Build() *models.CatalogPrice {
	m := &models.CatalogPrice{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CatalogID != nil {
		m.CatalogID = o.CatalogID()
	}
	if o.Amount != nil {
		m.Amount = o.Amount()
	}
	if o.BillingType != nil {
		m.BillingType = o.BillingType()
	}
	if o.BillingCycle != nil {
		m.BillingCycle = o.BillingCycle()
	}
	if o.StartDate != nil {
		m.StartDate = o.StartDate()
	}
	if o.EndDate != nil {
		m.EndDate = o.EndDate()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CatalogPriceSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CatalogPriceTemplate.CreateMany
func (o CatalogPriceTemplate) BuildMany(number int) models.CatalogPriceSlice {
	m := make(models.CatalogPriceSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCatalogPrice(m *models.CatalogPriceSetter) {
	if !(m.CatalogID != nil) {
		val := random_types_Uint64(nil)
		m.CatalogID = func() *types.Uint64 { return &val }()
	}
	if !(m.Amount != nil) {
		val := random_int64(nil)
		m.Amount = func() *int64 { return &val }()
	}
	if !(m.BillingType != nil) {
		val := random_enums_CatalogPricesBillingType(nil)
		m.BillingType = func() *enums.CatalogPricesBillingType { return &val }()
	}
	if !(m.StartDate != nil) {
		val := random_time_Time(nil)
		m.StartDate = func() *time.Time { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.CatalogPrice
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CatalogPriceTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.CatalogPrice) error {
	var err error

	return err
}

// Create builds a catalogPrice and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CatalogPriceTemplate) Create(ctx context.Context, exec bob.Executor) (*models.CatalogPrice, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCatalogPrice(opt)

	if o.r.Catalog == nil {
		CatalogPriceMods.WithNewCatalog().Apply(ctx, o)
	}

	var rel0 *models.Catalog

	if o.r.Catalog.o.alreadyPersisted {
		rel0 = o.r.Catalog.o.Build()
	} else {
		rel0, err = o.r.Catalog.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CatalogID = func() *types.Uint64 { return &rel0.ID }()

	m, err := models.CatalogPrices.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Catalog = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a catalogPrice and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CatalogPriceTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.CatalogPrice {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a catalogPrice and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CatalogPriceTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.CatalogPrice {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple catalogPrices and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CatalogPriceTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CatalogPriceSlice, error) {
	var err error
	m := make(models.CatalogPriceSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple catalogPrices and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CatalogPriceTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CatalogPriceSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple catalogPrices and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CatalogPriceTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CatalogPriceSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CatalogPrice has methods that act as mods for the CatalogPriceTemplate
var CatalogPriceMods catalogPriceMods

type catalogPriceMods struct{}

func (m catalogPriceMods) RandomizeAllColumns(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModSlice{
		CatalogPriceMods.RandomID(f),
		CatalogPriceMods.RandomCatalogID(f),
		CatalogPriceMods.RandomAmount(f),
		CatalogPriceMods.RandomBillingType(f),
		CatalogPriceMods.RandomBillingCycle(f),
		CatalogPriceMods.RandomStartDate(f),
		CatalogPriceMods.RandomEndDate(f),
		CatalogPriceMods.RandomCreatedAt(f),
		CatalogPriceMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m catalogPriceMods) ID(val types.Uint64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.ID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) IDFunc(f func() types.Uint64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetID() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomID(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.ID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) CatalogID(val types.Uint64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CatalogID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) CatalogIDFunc(f func() types.Uint64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CatalogID = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetCatalogID() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CatalogID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomCatalogID(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CatalogID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) Amount(val int64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.Amount = func() int64 { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) AmountFunc(f func() int64) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.Amount = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetAmount() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.Amount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomAmount(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.Amount = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) BillingType(val enums.CatalogPricesBillingType) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingType = func() enums.CatalogPricesBillingType { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) BillingTypeFunc(f func() enums.CatalogPricesBillingType) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingType = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetBillingType() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomBillingType(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingType = func() enums.CatalogPricesBillingType {
			return random_enums_CatalogPricesBillingType(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) BillingCycle(val sql.Null[enums.CatalogPricesBillingCycle]) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingCycle = func() sql.Null[enums.CatalogPricesBillingCycle] { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) BillingCycleFunc(f func() sql.Null[enums.CatalogPricesBillingCycle]) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingCycle = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetBillingCycle() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingCycle = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m catalogPriceMods) RandomBillingCycle(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingCycle = func() sql.Null[enums.CatalogPricesBillingCycle] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_enums_CatalogPricesBillingCycle(f)
			return sql.Null[enums.CatalogPricesBillingCycle]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m catalogPriceMods) RandomBillingCycleNotNull(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.BillingCycle = func() sql.Null[enums.CatalogPricesBillingCycle] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_enums_CatalogPricesBillingCycle(f)
			return sql.Null[enums.CatalogPricesBillingCycle]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) StartDate(val time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.StartDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) StartDateFunc(f func() time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.StartDate = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetStartDate() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.StartDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomStartDate(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.StartDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) EndDate(val sql.Null[time.Time]) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.EndDate = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) EndDateFunc(f func() sql.Null[time.Time]) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.EndDate = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetEndDate() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.EndDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m catalogPriceMods) RandomEndDate(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.EndDate = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m catalogPriceMods) RandomEndDateNotNull(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.EndDate = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) CreatedAt(val time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) CreatedAtFunc(f func() time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetCreatedAt() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomCreatedAt(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m catalogPriceMods) UpdatedAt(val time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m catalogPriceMods) UpdatedAtFunc(f func() time.Time) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m catalogPriceMods) UnsetUpdatedAt() CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogPriceMods) RandomUpdatedAt(f *faker.Faker) CatalogPriceMod {
	return CatalogPriceModFunc(func(_ context.Context, o *CatalogPriceTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m catalogPriceMods) WithParentsCascading() CatalogPriceMod {
	return CatalogPriceModFunc(func(ctx context.Context, o *CatalogPriceTemplate) {
		if isDone, _ := catalogPriceWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = catalogPriceWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewCatalogWithContext(ctx, CatalogMods.WithParentsCascading())
			m.WithCatalog(related).Apply(ctx, o)
		}
	})
}

func (m catalogPriceMods) WithCatalog(rel *CatalogTemplate) CatalogPriceMod {
	return CatalogPriceModFunc(func(ctx context.Context, o *CatalogPriceTemplate) {
		o.r.Catalog = &catalogPriceRCatalogR{
			o: rel,
		}
	})
}

func (m catalogPriceMods) WithNewCatalog(mods ...CatalogMod) CatalogPriceMod {
	return CatalogPriceModFunc(func(ctx context.Context, o *CatalogPriceTemplate) {
		related := o.f.NewCatalogWithContext(ctx, mods...)

		m.WithCatalog(related).Apply(ctx, o)
	})
}

func (m catalogPriceMods) WithExistingCatalog(em *models.Catalog) CatalogPriceMod {
	return CatalogPriceModFunc(func(ctx context.Context, o *CatalogPriceTemplate) {
		o.r.Catalog = &catalogPriceRCatalogR{
			o: o.f.FromExistingCatalog(em),
		}
	})
}

func (m catalogPriceMods) WithoutCatalog() CatalogPriceMod {
	return CatalogPriceModFunc(func(ctx context.Context, o *CatalogPriceTemplate) {
		o.r.Catalog = nil
	})
}
