// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/flora/api/internal/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type CatalogMod interface {
	Apply(context.Context, *CatalogTemplate)
}

type CatalogModFunc func(context.Context, *CatalogTemplate)

func (f CatalogModFunc) Apply(ctx context.Context, n *CatalogTemplate) {
	f(ctx, n)
}

type CatalogModSlice []CatalogMod

func (mods CatalogModSlice) Apply(ctx context.Context, n *CatalogTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CatalogTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CatalogTemplate struct {
	ID        func() types.Uint64
	Name      func() string
	TenantID  func() types.Uint64
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r catalogR
	f *Factory

	alreadyPersisted bool
}

type catalogR struct {
	CatalogPrices []*catalogRCatalogPricesR
	Tenant        *catalogRTenantR
	OneShotUsages []*catalogROneShotUsagesR
	Subscriptions []*catalogRSubscriptionsR
}

type catalogRCatalogPricesR struct {
	number int
	o      *CatalogPriceTemplate
}
type catalogRTenantR struct {
	o *TenantTemplate
}
type catalogROneShotUsagesR struct {
	number int
	o      *OneShotUsageTemplate
}
type catalogRSubscriptionsR struct {
	number int
	o      *SubscriptionTemplate
}

// Apply mods to the CatalogTemplate
func (o *CatalogTemplate) Apply(ctx context.Context, mods ...CatalogMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Catalog
// according to the relationships in the template. Nothing is inserted into the db
func (t CatalogTemplate) setModelRels(o *models.Catalog) {
	if t.r.CatalogPrices != nil {
		rel := models.CatalogPriceSlice{}
		for _, r := range t.r.CatalogPrices {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CatalogID = o.ID // h2
				rel.R.Catalog = o
			}
			rel = append(rel, related...)
		}
		o.R.CatalogPrices = rel
	}

	if t.r.Tenant != nil {
		rel := t.r.Tenant.o.Build()
		rel.R.Catalogs = append(rel.R.Catalogs, o)
		o.TenantID = rel.ID // h2
		o.R.Tenant = rel
	}

	if t.r.OneShotUsages != nil {
		rel := models.OneShotUsageSlice{}
		for _, r := range t.r.OneShotUsages {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CatalogID = o.ID // h2
				rel.R.Catalog = o
			}
			rel = append(rel, related...)
		}
		o.R.OneShotUsages = rel
	}

	if t.r.Subscriptions != nil {
		rel := models.SubscriptionSlice{}
		for _, r := range t.r.Subscriptions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CatalogID = o.ID // h2
				rel.R.Catalog = o
			}
			rel = append(rel, related...)
		}
		o.R.Subscriptions = rel
	}
}

// BuildSetter returns an *models.CatalogSetter
// this does nothing with the relationship templates
func (o CatalogTemplate) BuildSetter() *models.CatalogSetter {
	m := &models.CatalogSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *types.Uint64 { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.TenantID != nil {
		val := o.TenantID()
		m.TenantID = func() *types.Uint64 { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.CatalogSetter
// this does nothing with the relationship templates
func (o CatalogTemplate) BuildManySetter(number int) []*models.CatalogSetter {
	m := make([]*models.CatalogSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Catalog
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CatalogTemplate.Create
func (o CatalogTemplate) Build() *models.Catalog {
	m := &models.Catalog{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.TenantID != nil {
		m.TenantID = o.TenantID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CatalogSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CatalogTemplate.CreateMany
func (o CatalogTemplate) BuildMany(number int) models.CatalogSlice {
	m := make(models.CatalogSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCatalog(m *models.CatalogSetter) {
	if !(m.Name != nil) {
		val := random_string(nil, "255")
		m.Name = func() *string { return &val }()
	}
	if !(m.TenantID != nil) {
		val := random_types_Uint64(nil)
		m.TenantID = func() *types.Uint64 { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Catalog
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CatalogTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Catalog) error {
	var err error

	isCatalogPricesDone, _ := catalogRelCatalogPricesCtx.Value(ctx)
	if !isCatalogPricesDone && o.r.CatalogPrices != nil {
		ctx = catalogRelCatalogPricesCtx.WithValue(ctx, true)
		for _, r := range o.r.CatalogPrices {
			if r.o.alreadyPersisted {
				m.R.CatalogPrices = append(m.R.CatalogPrices, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCatalogPrices(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOneShotUsagesDone, _ := catalogRelOneShotUsagesCtx.Value(ctx)
	if !isOneShotUsagesDone && o.r.OneShotUsages != nil {
		ctx = catalogRelOneShotUsagesCtx.WithValue(ctx, true)
		for _, r := range o.r.OneShotUsages {
			if r.o.alreadyPersisted {
				m.R.OneShotUsages = append(m.R.OneShotUsages, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOneShotUsages(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSubscriptionsDone, _ := catalogRelSubscriptionsCtx.Value(ctx)
	if !isSubscriptionsDone && o.r.Subscriptions != nil {
		ctx = catalogRelSubscriptionsCtx.WithValue(ctx, true)
		for _, r := range o.r.Subscriptions {
			if r.o.alreadyPersisted {
				m.R.Subscriptions = append(m.R.Subscriptions, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSubscriptions(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a catalog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CatalogTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Catalog, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCatalog(opt)

	if o.r.Tenant == nil {
		CatalogMods.WithNewTenant().Apply(ctx, o)
	}

	var rel1 *models.Tenant

	if o.r.Tenant.o.alreadyPersisted {
		rel1 = o.r.Tenant.o.Build()
	} else {
		rel1, err = o.r.Tenant.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.TenantID = func() *types.Uint64 { return &rel1.ID }()

	m, err := models.Catalogs.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Tenant = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a catalog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CatalogTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Catalog {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a catalog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CatalogTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Catalog {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple catalogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CatalogTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CatalogSlice, error) {
	var err error
	m := make(models.CatalogSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple catalogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CatalogTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CatalogSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple catalogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CatalogTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CatalogSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Catalog has methods that act as mods for the CatalogTemplate
var CatalogMods catalogMods

type catalogMods struct{}

func (m catalogMods) RandomizeAllColumns(f *faker.Faker) CatalogMod {
	return CatalogModSlice{
		CatalogMods.RandomID(f),
		CatalogMods.RandomName(f),
		CatalogMods.RandomTenantID(f),
		CatalogMods.RandomCreatedAt(f),
		CatalogMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m catalogMods) ID(val types.Uint64) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.ID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m catalogMods) IDFunc(f func() types.Uint64) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m catalogMods) UnsetID() CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogMods) RandomID(f *faker.Faker) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.ID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m catalogMods) Name(val string) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m catalogMods) NameFunc(f func() string) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m catalogMods) UnsetName() CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogMods) RandomName(f *faker.Faker) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m catalogMods) TenantID(val types.Uint64) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.TenantID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m catalogMods) TenantIDFunc(f func() types.Uint64) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.TenantID = f
	})
}

// Clear any values for the column
func (m catalogMods) UnsetTenantID() CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.TenantID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogMods) RandomTenantID(f *faker.Faker) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.TenantID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m catalogMods) CreatedAt(val time.Time) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m catalogMods) CreatedAtFunc(f func() time.Time) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m catalogMods) UnsetCreatedAt() CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogMods) RandomCreatedAt(f *faker.Faker) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m catalogMods) UpdatedAt(val time.Time) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m catalogMods) UpdatedAtFunc(f func() time.Time) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m catalogMods) UnsetUpdatedAt() CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m catalogMods) RandomUpdatedAt(f *faker.Faker) CatalogMod {
	return CatalogModFunc(func(_ context.Context, o *CatalogTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m catalogMods) WithParentsCascading() CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		if isDone, _ := catalogWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = catalogWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewTenantWithContext(ctx, TenantMods.WithParentsCascading())
			m.WithTenant(related).Apply(ctx, o)
		}
	})
}

func (m catalogMods) WithTenant(rel *TenantTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Tenant = &catalogRTenantR{
			o: rel,
		}
	})
}

func (m catalogMods) WithNewTenant(mods ...TenantMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewTenantWithContext(ctx, mods...)

		m.WithTenant(related).Apply(ctx, o)
	})
}

func (m catalogMods) WithExistingTenant(em *models.Tenant) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Tenant = &catalogRTenantR{
			o: o.f.FromExistingTenant(em),
		}
	})
}

func (m catalogMods) WithoutTenant() CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Tenant = nil
	})
}

func (m catalogMods) WithCatalogPrices(number int, related *CatalogPriceTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.CatalogPrices = []*catalogRCatalogPricesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m catalogMods) WithNewCatalogPrices(number int, mods ...CatalogPriceMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewCatalogPriceWithContext(ctx, mods...)
		m.WithCatalogPrices(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddCatalogPrices(number int, related *CatalogPriceTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.CatalogPrices = append(o.r.CatalogPrices, &catalogRCatalogPricesR{
			number: number,
			o:      related,
		})
	})
}

func (m catalogMods) AddNewCatalogPrices(number int, mods ...CatalogPriceMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewCatalogPriceWithContext(ctx, mods...)
		m.AddCatalogPrices(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddExistingCatalogPrices(existingModels ...*models.CatalogPrice) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		for _, em := range existingModels {
			o.r.CatalogPrices = append(o.r.CatalogPrices, &catalogRCatalogPricesR{
				o: o.f.FromExistingCatalogPrice(em),
			})
		}
	})
}

func (m catalogMods) WithoutCatalogPrices() CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.CatalogPrices = nil
	})
}

func (m catalogMods) WithOneShotUsages(number int, related *OneShotUsageTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.OneShotUsages = []*catalogROneShotUsagesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m catalogMods) WithNewOneShotUsages(number int, mods ...OneShotUsageMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewOneShotUsageWithContext(ctx, mods...)
		m.WithOneShotUsages(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddOneShotUsages(number int, related *OneShotUsageTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.OneShotUsages = append(o.r.OneShotUsages, &catalogROneShotUsagesR{
			number: number,
			o:      related,
		})
	})
}

func (m catalogMods) AddNewOneShotUsages(number int, mods ...OneShotUsageMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewOneShotUsageWithContext(ctx, mods...)
		m.AddOneShotUsages(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddExistingOneShotUsages(existingModels ...*models.OneShotUsage) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		for _, em := range existingModels {
			o.r.OneShotUsages = append(o.r.OneShotUsages, &catalogROneShotUsagesR{
				o: o.f.FromExistingOneShotUsage(em),
			})
		}
	})
}

func (m catalogMods) WithoutOneShotUsages() CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.OneShotUsages = nil
	})
}

func (m catalogMods) WithSubscriptions(number int, related *SubscriptionTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Subscriptions = []*catalogRSubscriptionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m catalogMods) WithNewSubscriptions(number int, mods ...SubscriptionMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewSubscriptionWithContext(ctx, mods...)
		m.WithSubscriptions(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddSubscriptions(number int, related *SubscriptionTemplate) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Subscriptions = append(o.r.Subscriptions, &catalogRSubscriptionsR{
			number: number,
			o:      related,
		})
	})
}

func (m catalogMods) AddNewSubscriptions(number int, mods ...SubscriptionMod) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		related := o.f.NewSubscriptionWithContext(ctx, mods...)
		m.AddSubscriptions(number, related).Apply(ctx, o)
	})
}

func (m catalogMods) AddExistingSubscriptions(existingModels ...*models.Subscription) CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		for _, em := range existingModels {
			o.r.Subscriptions = append(o.r.Subscriptions, &catalogRSubscriptionsR{
				o: o.f.FromExistingSubscription(em),
			})
		}
	})
}

func (m catalogMods) WithoutSubscriptions() CatalogMod {
	return CatalogModFunc(func(ctx context.Context, o *CatalogTemplate) {
		o.r.Subscriptions = nil
	})
}
