// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	models "github.com/flora/api/internal/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type ServiceChargeMod interface {
	Apply(context.Context, *ServiceChargeTemplate)
}

type ServiceChargeModFunc func(context.Context, *ServiceChargeTemplate)

func (f ServiceChargeModFunc) Apply(ctx context.Context, n *ServiceChargeTemplate) {
	f(ctx, n)
}

type ServiceChargeModSlice []ServiceChargeMod

func (mods ServiceChargeModSlice) Apply(ctx context.Context, n *ServiceChargeTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ServiceChargeTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ServiceChargeTemplate struct {
	ID             func() types.Uint64
	AccountID      func() types.Uint64
	StartDate      func() time.Time
	EndDate        func() time.Time
	Amount         func() int64
	LatestStatusID func() sql.Null[types.Uint64]
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time

	r serviceChargeR
	f *Factory

	alreadyPersisted bool
}

type serviceChargeR struct {
	ServiceChargeItems              []*serviceChargeRServiceChargeItemsR
	ServiceChargeStatuses           []*serviceChargeRServiceChargeStatusesR
	Account                         *serviceChargeRAccountR
	LatestStatusServiceChargeStatus *serviceChargeRLatestStatusServiceChargeStatusR
}

type serviceChargeRServiceChargeItemsR struct {
	number int
	o      *ServiceChargeItemTemplate
}
type serviceChargeRServiceChargeStatusesR struct {
	number int
	o      *ServiceChargeStatusTemplate
}
type serviceChargeRAccountR struct {
	o *AccountTemplate
}
type serviceChargeRLatestStatusServiceChargeStatusR struct {
	o *ServiceChargeStatusTemplate
}

// Apply mods to the ServiceChargeTemplate
func (o *ServiceChargeTemplate) Apply(ctx context.Context, mods ...ServiceChargeMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ServiceCharge
// according to the relationships in the template. Nothing is inserted into the db
func (t ServiceChargeTemplate) setModelRels(o *models.ServiceCharge) {
	if t.r.ServiceChargeItems != nil {
		rel := models.ServiceChargeItemSlice{}
		for _, r := range t.r.ServiceChargeItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ServiceChargeID = o.ID // h2
				rel.R.ServiceCharge = o
			}
			rel = append(rel, related...)
		}
		o.R.ServiceChargeItems = rel
	}

	if t.r.ServiceChargeStatuses != nil {
		rel := models.ServiceChargeStatusSlice{}
		for _, r := range t.r.ServiceChargeStatuses {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ServiceChargeID = o.ID // h2
				rel.R.ServiceCharge = o
			}
			rel = append(rel, related...)
		}
		o.R.ServiceChargeStatuses = rel
	}

	if t.r.Account != nil {
		rel := t.r.Account.o.Build()
		rel.R.ServiceCharges = append(rel.R.ServiceCharges, o)
		o.AccountID = rel.ID // h2
		o.R.Account = rel
	}

	if t.r.LatestStatusServiceChargeStatus != nil {
		rel := t.r.LatestStatusServiceChargeStatus.o.Build()
		rel.R.LatestStatusServiceCharges = append(rel.R.LatestStatusServiceCharges, o)
		o.LatestStatusID = sql.Null[types.Uint64]{V: rel.ID, Valid: true} // h2
		o.R.LatestStatusServiceChargeStatus = rel
	}
}

// BuildSetter returns an *models.ServiceChargeSetter
// this does nothing with the relationship templates
func (o ServiceChargeTemplate) BuildSetter() *models.ServiceChargeSetter {
	m := &models.ServiceChargeSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *types.Uint64 { return &val }()
	}
	if o.AccountID != nil {
		val := o.AccountID()
		m.AccountID = func() *types.Uint64 { return &val }()
	}
	if o.StartDate != nil {
		val := o.StartDate()
		m.StartDate = func() *time.Time { return &val }()
	}
	if o.EndDate != nil {
		val := o.EndDate()
		m.EndDate = func() *time.Time { return &val }()
	}
	if o.Amount != nil {
		val := o.Amount()
		m.Amount = func() *int64 { return &val }()
	}
	if o.LatestStatusID != nil {
		val := o.LatestStatusID()
		m.LatestStatusID = func() *sql.Null[types.Uint64] { v := val; return &v }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.ServiceChargeSetter
// this does nothing with the relationship templates
func (o ServiceChargeTemplate) BuildManySetter(number int) []*models.ServiceChargeSetter {
	m := make([]*models.ServiceChargeSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ServiceCharge
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ServiceChargeTemplate.Create
func (o ServiceChargeTemplate) Build() *models.ServiceCharge {
	m := &models.ServiceCharge{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.AccountID != nil {
		m.AccountID = o.AccountID()
	}
	if o.StartDate != nil {
		m.StartDate = o.StartDate()
	}
	if o.EndDate != nil {
		m.EndDate = o.EndDate()
	}
	if o.Amount != nil {
		m.Amount = o.Amount()
	}
	if o.LatestStatusID != nil {
		m.LatestStatusID = o.LatestStatusID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ServiceChargeSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ServiceChargeTemplate.CreateMany
func (o ServiceChargeTemplate) BuildMany(number int) models.ServiceChargeSlice {
	m := make(models.ServiceChargeSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableServiceCharge(m *models.ServiceChargeSetter) {
	if !(m.AccountID != nil) {
		val := random_types_Uint64(nil)
		m.AccountID = func() *types.Uint64 { return &val }()
	}
	if !(m.StartDate != nil) {
		val := random_time_Time(nil)
		m.StartDate = func() *time.Time { return &val }()
	}
	if !(m.EndDate != nil) {
		val := random_time_Time(nil)
		m.EndDate = func() *time.Time { return &val }()
	}
	if !(m.Amount != nil) {
		val := random_int64(nil)
		m.Amount = func() *int64 { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ServiceCharge
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ServiceChargeTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ServiceCharge) error {
	var err error

	isServiceChargeItemsDone, _ := serviceChargeRelServiceChargeItemsCtx.Value(ctx)
	if !isServiceChargeItemsDone && o.r.ServiceChargeItems != nil {
		ctx = serviceChargeRelServiceChargeItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.ServiceChargeItems {
			if r.o.alreadyPersisted {
				m.R.ServiceChargeItems = append(m.R.ServiceChargeItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachServiceChargeItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isServiceChargeStatusesDone, _ := serviceChargeRelServiceChargeStatusesCtx.Value(ctx)
	if !isServiceChargeStatusesDone && o.r.ServiceChargeStatuses != nil {
		ctx = serviceChargeRelServiceChargeStatusesCtx.WithValue(ctx, true)
		for _, r := range o.r.ServiceChargeStatuses {
			if r.o.alreadyPersisted {
				m.R.ServiceChargeStatuses = append(m.R.ServiceChargeStatuses, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachServiceChargeStatuses(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isLatestStatusServiceChargeStatusDone, _ := serviceChargeRelLatestStatusServiceChargeStatusCtx.Value(ctx)
	if !isLatestStatusServiceChargeStatusDone && o.r.LatestStatusServiceChargeStatus != nil {
		ctx = serviceChargeRelLatestStatusServiceChargeStatusCtx.WithValue(ctx, true)
		if o.r.LatestStatusServiceChargeStatus.o.alreadyPersisted {
			m.R.LatestStatusServiceChargeStatus = o.r.LatestStatusServiceChargeStatus.o.Build()
		} else {
			var rel3 *models.ServiceChargeStatus
			rel3, err = o.r.LatestStatusServiceChargeStatus.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachLatestStatusServiceChargeStatus(ctx, exec, rel3)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a serviceCharge and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ServiceChargeTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ServiceCharge, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableServiceCharge(opt)

	if o.r.Account == nil {
		ServiceChargeMods.WithNewAccount().Apply(ctx, o)
	}

	var rel2 *models.Account

	if o.r.Account.o.alreadyPersisted {
		rel2 = o.r.Account.o.Build()
	} else {
		rel2, err = o.r.Account.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.AccountID = func() *types.Uint64 { return &rel2.ID }()

	m, err := models.ServiceCharges.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Account = rel2

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a serviceCharge and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ServiceChargeTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ServiceCharge {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a serviceCharge and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ServiceChargeTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ServiceCharge {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple serviceCharges and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ServiceChargeTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ServiceChargeSlice, error) {
	var err error
	m := make(models.ServiceChargeSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple serviceCharges and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ServiceChargeTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ServiceChargeSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple serviceCharges and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ServiceChargeTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ServiceChargeSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ServiceCharge has methods that act as mods for the ServiceChargeTemplate
var ServiceChargeMods serviceChargeMods

type serviceChargeMods struct{}

func (m serviceChargeMods) RandomizeAllColumns(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModSlice{
		ServiceChargeMods.RandomID(f),
		ServiceChargeMods.RandomAccountID(f),
		ServiceChargeMods.RandomStartDate(f),
		ServiceChargeMods.RandomEndDate(f),
		ServiceChargeMods.RandomAmount(f),
		ServiceChargeMods.RandomLatestStatusID(f),
		ServiceChargeMods.RandomCreatedAt(f),
		ServiceChargeMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m serviceChargeMods) ID(val types.Uint64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.ID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) IDFunc(f func() types.Uint64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetID() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomID(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.ID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) AccountID(val types.Uint64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.AccountID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) AccountIDFunc(f func() types.Uint64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.AccountID = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetAccountID() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.AccountID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomAccountID(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.AccountID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) StartDate(val time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.StartDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) StartDateFunc(f func() time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.StartDate = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetStartDate() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.StartDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomStartDate(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.StartDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) EndDate(val time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.EndDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) EndDateFunc(f func() time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.EndDate = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetEndDate() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.EndDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomEndDate(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.EndDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) Amount(val int64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.Amount = func() int64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) AmountFunc(f func() int64) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.Amount = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetAmount() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.Amount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomAmount(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.Amount = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) LatestStatusID(val sql.Null[types.Uint64]) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.LatestStatusID = func() sql.Null[types.Uint64] { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) LatestStatusIDFunc(f func() sql.Null[types.Uint64]) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.LatestStatusID = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetLatestStatusID() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.LatestStatusID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m serviceChargeMods) RandomLatestStatusID(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.LatestStatusID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m serviceChargeMods) RandomLatestStatusIDNotNull(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.LatestStatusID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) CreatedAt(val time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) CreatedAtFunc(f func() time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetCreatedAt() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomCreatedAt(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeMods) UpdatedAt(val time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeMods) UpdatedAtFunc(f func() time.Time) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m serviceChargeMods) UnsetUpdatedAt() ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeMods) RandomUpdatedAt(f *faker.Faker) ServiceChargeMod {
	return ServiceChargeModFunc(func(_ context.Context, o *ServiceChargeTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m serviceChargeMods) WithParentsCascading() ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		if isDone, _ := serviceChargeWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = serviceChargeWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAccountWithContext(ctx, AccountMods.WithParentsCascading())
			m.WithAccount(related).Apply(ctx, o)
		}
		{

			related := o.f.NewServiceChargeStatusWithContext(ctx, ServiceChargeStatusMods.WithParentsCascading())
			m.WithLatestStatusServiceChargeStatus(related).Apply(ctx, o)
		}
	})
}

func (m serviceChargeMods) WithAccount(rel *AccountTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.Account = &serviceChargeRAccountR{
			o: rel,
		}
	})
}

func (m serviceChargeMods) WithNewAccount(mods ...AccountMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewAccountWithContext(ctx, mods...)

		m.WithAccount(related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) WithExistingAccount(em *models.Account) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.Account = &serviceChargeRAccountR{
			o: o.f.FromExistingAccount(em),
		}
	})
}

func (m serviceChargeMods) WithoutAccount() ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.Account = nil
	})
}

func (m serviceChargeMods) WithLatestStatusServiceChargeStatus(rel *ServiceChargeStatusTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.LatestStatusServiceChargeStatus = &serviceChargeRLatestStatusServiceChargeStatusR{
			o: rel,
		}
	})
}

func (m serviceChargeMods) WithNewLatestStatusServiceChargeStatus(mods ...ServiceChargeStatusMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewServiceChargeStatusWithContext(ctx, mods...)

		m.WithLatestStatusServiceChargeStatus(related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) WithExistingLatestStatusServiceChargeStatus(em *models.ServiceChargeStatus) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.LatestStatusServiceChargeStatus = &serviceChargeRLatestStatusServiceChargeStatusR{
			o: o.f.FromExistingServiceChargeStatus(em),
		}
	})
}

func (m serviceChargeMods) WithoutLatestStatusServiceChargeStatus() ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.LatestStatusServiceChargeStatus = nil
	})
}

func (m serviceChargeMods) WithServiceChargeItems(number int, related *ServiceChargeItemTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeItems = []*serviceChargeRServiceChargeItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m serviceChargeMods) WithNewServiceChargeItems(number int, mods ...ServiceChargeItemMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewServiceChargeItemWithContext(ctx, mods...)
		m.WithServiceChargeItems(number, related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) AddServiceChargeItems(number int, related *ServiceChargeItemTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeItems = append(o.r.ServiceChargeItems, &serviceChargeRServiceChargeItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m serviceChargeMods) AddNewServiceChargeItems(number int, mods ...ServiceChargeItemMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewServiceChargeItemWithContext(ctx, mods...)
		m.AddServiceChargeItems(number, related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) AddExistingServiceChargeItems(existingModels ...*models.ServiceChargeItem) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		for _, em := range existingModels {
			o.r.ServiceChargeItems = append(o.r.ServiceChargeItems, &serviceChargeRServiceChargeItemsR{
				o: o.f.FromExistingServiceChargeItem(em),
			})
		}
	})
}

func (m serviceChargeMods) WithoutServiceChargeItems() ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeItems = nil
	})
}

func (m serviceChargeMods) WithServiceChargeStatuses(number int, related *ServiceChargeStatusTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeStatuses = []*serviceChargeRServiceChargeStatusesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m serviceChargeMods) WithNewServiceChargeStatuses(number int, mods ...ServiceChargeStatusMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewServiceChargeStatusWithContext(ctx, mods...)
		m.WithServiceChargeStatuses(number, related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) AddServiceChargeStatuses(number int, related *ServiceChargeStatusTemplate) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeStatuses = append(o.r.ServiceChargeStatuses, &serviceChargeRServiceChargeStatusesR{
			number: number,
			o:      related,
		})
	})
}

func (m serviceChargeMods) AddNewServiceChargeStatuses(number int, mods ...ServiceChargeStatusMod) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		related := o.f.NewServiceChargeStatusWithContext(ctx, mods...)
		m.AddServiceChargeStatuses(number, related).Apply(ctx, o)
	})
}

func (m serviceChargeMods) AddExistingServiceChargeStatuses(existingModels ...*models.ServiceChargeStatus) ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		for _, em := range existingModels {
			o.r.ServiceChargeStatuses = append(o.r.ServiceChargeStatuses, &serviceChargeRServiceChargeStatusesR{
				o: o.f.FromExistingServiceChargeStatus(em),
			})
		}
	})
}

func (m serviceChargeMods) WithoutServiceChargeStatuses() ServiceChargeMod {
	return ServiceChargeModFunc(func(ctx context.Context, o *ServiceChargeTemplate) {
		o.r.ServiceChargeStatuses = nil
	})
}
