// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	models "github.com/flora/api/internal/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type ServiceChargeItemMod interface {
	Apply(context.Context, *ServiceChargeItemTemplate)
}

type ServiceChargeItemModFunc func(context.Context, *ServiceChargeItemTemplate)

func (f ServiceChargeItemModFunc) Apply(ctx context.Context, n *ServiceChargeItemTemplate) {
	f(ctx, n)
}

type ServiceChargeItemModSlice []ServiceChargeItemMod

func (mods ServiceChargeItemModSlice) Apply(ctx context.Context, n *ServiceChargeItemTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ServiceChargeItemTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ServiceChargeItemTemplate struct {
	ID              func() types.Uint64
	Name            func() string
	Amount          func() int64
	ServiceChargeID func() types.Uint64
	OneShotUsageID  func() sql.Null[types.Uint64]
	SubscriptionID  func() sql.Null[types.Uint64]
	CreatedAt       func() time.Time
	UpdatedAt       func() time.Time

	r serviceChargeItemR
	f *Factory

	alreadyPersisted bool
}

type serviceChargeItemR struct {
	ServiceCharge *serviceChargeItemRServiceChargeR
	OneShotUsage  *serviceChargeItemROneShotUsageR
	Subscription  *serviceChargeItemRSubscriptionR
}

type serviceChargeItemRServiceChargeR struct {
	o *ServiceChargeTemplate
}
type serviceChargeItemROneShotUsageR struct {
	o *OneShotUsageTemplate
}
type serviceChargeItemRSubscriptionR struct {
	o *SubscriptionTemplate
}

// Apply mods to the ServiceChargeItemTemplate
func (o *ServiceChargeItemTemplate) Apply(ctx context.Context, mods ...ServiceChargeItemMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ServiceChargeItem
// according to the relationships in the template. Nothing is inserted into the db
func (t ServiceChargeItemTemplate) setModelRels(o *models.ServiceChargeItem) {
	if t.r.ServiceCharge != nil {
		rel := t.r.ServiceCharge.o.Build()
		rel.R.ServiceChargeItems = append(rel.R.ServiceChargeItems, o)
		o.ServiceChargeID = rel.ID // h2
		o.R.ServiceCharge = rel
	}

	if t.r.OneShotUsage != nil {
		rel := t.r.OneShotUsage.o.Build()
		rel.R.ServiceChargeItems = append(rel.R.ServiceChargeItems, o)
		o.OneShotUsageID = sql.Null[types.Uint64]{V: rel.ID, Valid: true} // h2
		o.R.OneShotUsage = rel
	}

	if t.r.Subscription != nil {
		rel := t.r.Subscription.o.Build()
		rel.R.ServiceChargeItems = append(rel.R.ServiceChargeItems, o)
		o.SubscriptionID = sql.Null[types.Uint64]{V: rel.ID, Valid: true} // h2
		o.R.Subscription = rel
	}
}

// BuildSetter returns an *models.ServiceChargeItemSetter
// this does nothing with the relationship templates
func (o ServiceChargeItemTemplate) BuildSetter() *models.ServiceChargeItemSetter {
	m := &models.ServiceChargeItemSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *types.Uint64 { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.Amount != nil {
		val := o.Amount()
		m.Amount = func() *int64 { return &val }()
	}
	if o.ServiceChargeID != nil {
		val := o.ServiceChargeID()
		m.ServiceChargeID = func() *types.Uint64 { return &val }()
	}
	if o.OneShotUsageID != nil {
		val := o.OneShotUsageID()
		m.OneShotUsageID = func() *sql.Null[types.Uint64] { v := val; return &v }()
	}
	if o.SubscriptionID != nil {
		val := o.SubscriptionID()
		m.SubscriptionID = func() *sql.Null[types.Uint64] { v := val; return &v }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.ServiceChargeItemSetter
// this does nothing with the relationship templates
func (o ServiceChargeItemTemplate) BuildManySetter(number int) []*models.ServiceChargeItemSetter {
	m := make([]*models.ServiceChargeItemSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ServiceChargeItem
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ServiceChargeItemTemplate.Create
func (o ServiceChargeItemTemplate) Build() *models.ServiceChargeItem {
	m := &models.ServiceChargeItem{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Amount != nil {
		m.Amount = o.Amount()
	}
	if o.ServiceChargeID != nil {
		m.ServiceChargeID = o.ServiceChargeID()
	}
	if o.OneShotUsageID != nil {
		m.OneShotUsageID = o.OneShotUsageID()
	}
	if o.SubscriptionID != nil {
		m.SubscriptionID = o.SubscriptionID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ServiceChargeItemSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ServiceChargeItemTemplate.CreateMany
func (o ServiceChargeItemTemplate) BuildMany(number int) models.ServiceChargeItemSlice {
	m := make(models.ServiceChargeItemSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableServiceChargeItem(m *models.ServiceChargeItemSetter) {
	if !(m.Name != nil) {
		val := random_string(nil, "255")
		m.Name = func() *string { return &val }()
	}
	if !(m.Amount != nil) {
		val := random_int64(nil)
		m.Amount = func() *int64 { return &val }()
	}
	if !(m.ServiceChargeID != nil) {
		val := random_types_Uint64(nil)
		m.ServiceChargeID = func() *types.Uint64 { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ServiceChargeItem
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ServiceChargeItemTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ServiceChargeItem) error {
	var err error

	isOneShotUsageDone, _ := serviceChargeItemRelOneShotUsageCtx.Value(ctx)
	if !isOneShotUsageDone && o.r.OneShotUsage != nil {
		ctx = serviceChargeItemRelOneShotUsageCtx.WithValue(ctx, true)
		if o.r.OneShotUsage.o.alreadyPersisted {
			m.R.OneShotUsage = o.r.OneShotUsage.o.Build()
		} else {
			var rel1 *models.OneShotUsage
			rel1, err = o.r.OneShotUsage.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachOneShotUsage(ctx, exec, rel1)
			if err != nil {
				return err
			}
		}

	}

	isSubscriptionDone, _ := serviceChargeItemRelSubscriptionCtx.Value(ctx)
	if !isSubscriptionDone && o.r.Subscription != nil {
		ctx = serviceChargeItemRelSubscriptionCtx.WithValue(ctx, true)
		if o.r.Subscription.o.alreadyPersisted {
			m.R.Subscription = o.r.Subscription.o.Build()
		} else {
			var rel2 *models.Subscription
			rel2, err = o.r.Subscription.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachSubscription(ctx, exec, rel2)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a serviceChargeItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ServiceChargeItemTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ServiceChargeItem, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableServiceChargeItem(opt)

	if o.r.ServiceCharge == nil {
		ServiceChargeItemMods.WithNewServiceCharge().Apply(ctx, o)
	}

	var rel0 *models.ServiceCharge

	if o.r.ServiceCharge.o.alreadyPersisted {
		rel0 = o.r.ServiceCharge.o.Build()
	} else {
		rel0, err = o.r.ServiceCharge.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ServiceChargeID = func() *types.Uint64 { return &rel0.ID }()

	m, err := models.ServiceChargeItems.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.ServiceCharge = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a serviceChargeItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ServiceChargeItemTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ServiceChargeItem {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a serviceChargeItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ServiceChargeItemTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ServiceChargeItem {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple serviceChargeItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ServiceChargeItemTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ServiceChargeItemSlice, error) {
	var err error
	m := make(models.ServiceChargeItemSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple serviceChargeItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ServiceChargeItemTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ServiceChargeItemSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple serviceChargeItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ServiceChargeItemTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ServiceChargeItemSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ServiceChargeItem has methods that act as mods for the ServiceChargeItemTemplate
var ServiceChargeItemMods serviceChargeItemMods

type serviceChargeItemMods struct{}

func (m serviceChargeItemMods) RandomizeAllColumns(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModSlice{
		ServiceChargeItemMods.RandomID(f),
		ServiceChargeItemMods.RandomName(f),
		ServiceChargeItemMods.RandomAmount(f),
		ServiceChargeItemMods.RandomServiceChargeID(f),
		ServiceChargeItemMods.RandomOneShotUsageID(f),
		ServiceChargeItemMods.RandomSubscriptionID(f),
		ServiceChargeItemMods.RandomCreatedAt(f),
		ServiceChargeItemMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m serviceChargeItemMods) ID(val types.Uint64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) IDFunc(f func() types.Uint64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetID() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomID(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) Name(val string) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) NameFunc(f func() string) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetName() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomName(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) Amount(val int64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Amount = func() int64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) AmountFunc(f func() int64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Amount = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetAmount() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Amount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomAmount(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.Amount = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) ServiceChargeID(val types.Uint64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ServiceChargeID = func() types.Uint64 { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) ServiceChargeIDFunc(f func() types.Uint64) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ServiceChargeID = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetServiceChargeID() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ServiceChargeID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomServiceChargeID(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.ServiceChargeID = func() types.Uint64 {
			return random_types_Uint64(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) OneShotUsageID(val sql.Null[types.Uint64]) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.OneShotUsageID = func() sql.Null[types.Uint64] { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) OneShotUsageIDFunc(f func() sql.Null[types.Uint64]) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.OneShotUsageID = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetOneShotUsageID() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.OneShotUsageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m serviceChargeItemMods) RandomOneShotUsageID(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.OneShotUsageID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m serviceChargeItemMods) RandomOneShotUsageIDNotNull(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.OneShotUsageID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) SubscriptionID(val sql.Null[types.Uint64]) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.SubscriptionID = func() sql.Null[types.Uint64] { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) SubscriptionIDFunc(f func() sql.Null[types.Uint64]) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.SubscriptionID = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetSubscriptionID() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.SubscriptionID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m serviceChargeItemMods) RandomSubscriptionID(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.SubscriptionID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m serviceChargeItemMods) RandomSubscriptionIDNotNull(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.SubscriptionID = func() sql.Null[types.Uint64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_Uint64(f)
			return sql.Null[types.Uint64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) CreatedAt(val time.Time) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) CreatedAtFunc(f func() time.Time) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetCreatedAt() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomCreatedAt(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m serviceChargeItemMods) UpdatedAt(val time.Time) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m serviceChargeItemMods) UpdatedAtFunc(f func() time.Time) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m serviceChargeItemMods) UnsetUpdatedAt() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m serviceChargeItemMods) RandomUpdatedAt(f *faker.Faker) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(_ context.Context, o *ServiceChargeItemTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m serviceChargeItemMods) WithParentsCascading() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		if isDone, _ := serviceChargeItemWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = serviceChargeItemWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewServiceChargeWithContext(ctx, ServiceChargeMods.WithParentsCascading())
			m.WithServiceCharge(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOneShotUsageWithContext(ctx, OneShotUsageMods.WithParentsCascading())
			m.WithOneShotUsage(related).Apply(ctx, o)
		}
		{

			related := o.f.NewSubscriptionWithContext(ctx, SubscriptionMods.WithParentsCascading())
			m.WithSubscription(related).Apply(ctx, o)
		}
	})
}

func (m serviceChargeItemMods) WithServiceCharge(rel *ServiceChargeTemplate) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.ServiceCharge = &serviceChargeItemRServiceChargeR{
			o: rel,
		}
	})
}

func (m serviceChargeItemMods) WithNewServiceCharge(mods ...ServiceChargeMod) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		related := o.f.NewServiceChargeWithContext(ctx, mods...)

		m.WithServiceCharge(related).Apply(ctx, o)
	})
}

func (m serviceChargeItemMods) WithExistingServiceCharge(em *models.ServiceCharge) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.ServiceCharge = &serviceChargeItemRServiceChargeR{
			o: o.f.FromExistingServiceCharge(em),
		}
	})
}

func (m serviceChargeItemMods) WithoutServiceCharge() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.ServiceCharge = nil
	})
}

func (m serviceChargeItemMods) WithOneShotUsage(rel *OneShotUsageTemplate) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.OneShotUsage = &serviceChargeItemROneShotUsageR{
			o: rel,
		}
	})
}

func (m serviceChargeItemMods) WithNewOneShotUsage(mods ...OneShotUsageMod) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		related := o.f.NewOneShotUsageWithContext(ctx, mods...)

		m.WithOneShotUsage(related).Apply(ctx, o)
	})
}

func (m serviceChargeItemMods) WithExistingOneShotUsage(em *models.OneShotUsage) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.OneShotUsage = &serviceChargeItemROneShotUsageR{
			o: o.f.FromExistingOneShotUsage(em),
		}
	})
}

func (m serviceChargeItemMods) WithoutOneShotUsage() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.OneShotUsage = nil
	})
}

func (m serviceChargeItemMods) WithSubscription(rel *SubscriptionTemplate) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.Subscription = &serviceChargeItemRSubscriptionR{
			o: rel,
		}
	})
}

func (m serviceChargeItemMods) WithNewSubscription(mods ...SubscriptionMod) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		related := o.f.NewSubscriptionWithContext(ctx, mods...)

		m.WithSubscription(related).Apply(ctx, o)
	})
}

func (m serviceChargeItemMods) WithExistingSubscription(em *models.Subscription) ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.Subscription = &serviceChargeItemRSubscriptionR{
			o: o.f.FromExistingSubscription(em),
		}
	})
}

func (m serviceChargeItemMods) WithoutSubscription() ServiceChargeItemMod {
	return ServiceChargeItemModFunc(func(ctx context.Context, o *ServiceChargeItemTemplate) {
		o.r.Subscription = nil
	})
}
